recipes-devtools/cdrtools/cdrtools_2.01.bb

Singed-off-by: Jed Lejosne <jed.openxt@gmail.com>

[cdrtools] fix URL

---

recipes-support/evtest/evtest_1.25.bb

Singed-off-by: Jed Lejosne <jed.openxt@gmail.com>

[evtest] the recipe in the OE repo is outdated, rewriting it

---

recipes-openxt/xctools/audio-helper/audio_helper_start
recipes-security/selinux/qemu-wrappers/qemu-dm-wrapper_alt
recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_system_stubdom-helpers.te.patch
recipes-security/selinux/refpolicy-mcs/policy.modules.contrib.qemu.diff

OXT-191
Singed-off-by: Jed Lejosne <jed.openxt@gmail.com>

Fix per-VM alsa config path and audio card

---

recipes-bsp/usbutils/usbutils/fix_lsusb-t.patch
recipes-bsp/usbutils/usbutils_0.82.bb

Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

[usbutils] fix a segfault in lsusb -t

---

recipes-security/selinux/svirt-interpose/svirt-interpose.c

by not closing stdin, stdout and stderr.
Also add a missing close (fd);

[svirt-interpose] be nice to qemu 1.4 in permissive mode

---

recipes-kernel/linux/linux-xenclient-dom0-3.11/0002-Add-thorough-reset-interface-to-pciback-s-sysfs.patch

Fix test for PCI AF FLR capabilities.

---

recipes-openxt/qemu-dm/files/0019-surfman-dcl.patch
recipes-openxt/qemu-dm/files/0020-audio-policy.patch
recipes-openxt/qemu-dm/qemu-dm.inc

This clears the way to introduce the new ACPI PM patch that is coming
and takes out a broken patch.
OXT-262 OXT-217
Signed-off-by: Ross Philipson philipsonr@ainfosec.com

Remove broken battery patch from the Qemu pq.

---

recipes-openxt/xenclient/xenclient-dom0-tweaks.inc
recipes-openxt/xenclient/xenclient-dom0-tweaks/firstboot.sh
recipes-openxt/xenclient/xenclient-dom0-tweaks_1.0.bb

Depends on oxt-271, and as such, is included in this pull (although available separately).

[OXT-272]+[OXT-271]

---

recipes-bsp/pciutils/pciutils.inc
recipes-core/udev/udev/05-db.rules
recipes-core/udev/udev_182.bbappend

Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

[udev] use pci.ids and usb.ids for providing complete device information

---

recipes-extended/xen/files/xc-xt-v4v-viptables.patch
recipes-extended/xen/files/xc-xt-v4v.patch

Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

[xen] fix leaks and formatting in v4v firewalls

---

recipes-openxt/qemu-dm/files/0030-xenfv-i440fx-max-ram-below-4g.patch

Format 0030-xenfv-i440fx-max-ram-below-4g.patch and remove debug print.

format and cleanup

---

recipes-openxt/qemu-dm/files/0005-logging-syslog.patch
recipes-openxt/qemu-dm/files/0009-acpi.patch

Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

[qemu] fix debug typo

---

recipes-extended/xen/files/acpi-pm-feature.patch
recipes-extended/xen/xen-firmware.bb

[xen-firmware] ACPI/hvmloader portion of the ACPI PM feature.

---

recipes-openxt/qemu-dm/files/0033-acpi-pm-feature.patch
recipes-openxt/qemu-dm/qemu-dm.inc

[acpi] QEMU portion of the ACPI PM feature.

---

recipes-openxt/qemu-dm/files/0033-acpi-pm-feature.patch

[acpi] Fix power button pressed event name.

---

recipes-openxt/xctools/xcpmd_git.bb

See https://github.com/OpenXT/xctools/pull/9

[xcpmd] remove dependency on libxenacpi

---

recipes-core/icedtea/icedtea6-native/icedtea-ecj-fix-currency-data.patch
recipes-core/icedtea/icedtea6-native_1.8.11.bbappend

Remove the remaining currency expirations from the icedtea utility.

---

recipes-kernel/linux/files/backport-config-Enable-NEED_DMA_MAP_STATE-by-default-when-SWIOTLB-is-selected.patch
recipes-kernel/linux/linux-xenclient-3.11.inc

See https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit?id=a6dfa128ce5c414ab46b1d690f7a1b8decb8526d
OXT-324

[linux] backport a DMA fix

---

recipes-openxt/qemu-dm/files/0035-xsa138-qemuu-1.patch
recipes-openxt/qemu-dm/files/0036-xsa138-qemuu-2.patch
recipes-openxt/qemu-dm/files/0037-xsa138-qemuu-3.patch
recipes-openxt/qemu-dm/qemu-dm.inc

OXT-339
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

qemu: patches for XSA-138 / CVE-2015-5154

---

recipes-kernel/linux-firmware/linux-firmware_git.bb

Move to linux-firmware top revision.

Upgrade linux-firmware

---

recipes-openxt/qemu-dm/qemu-dm-stubdom_1.4.0.bb

Directory names confusion... I'm sorry.

Fix patch-queue subdir

---

recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_services_xenpmd.te.patch
recipes-security/selinux/refpolicy-mcs_2.20130424.bbappend

Added support for xcpmd to send to dbusbouncer context to support adding
xcpmd to the UI

Added support for permitting xcpmd to send to dbus

---

recipes-core/tasks/task-xenclient-dom0.bb

remove upower from dom0

---

oe-addons/recipes/devilspie/devilspie_0.22.bb
recipes-connectivity/network-manager-applet/network-manager-applet_0.9.2.0.bbappend
recipes-core/busybox/busybox-static_1.11.3.bb
recipes-core/sysvinit/sysvinit_2.86.bb
recipes-graphics/vbetool/vbetool-xc_1.1.bb
recipes-graphics/xdotool/xdotool_2.inc
recipes-openxt/bootage/bootage_git.bb
recipes-openxt/tboot/tboot_1.8.3.bb
recipes-openxt/xclibs/libxclogging_git.bb
recipes-openxt/xclibs/libxcxenstore_git.bb
recipes-openxt/xctools/atapi-pt-helper_git.bb
recipes-openxt/xctools/audio-daemon_git.bb
recipes-openxt/xctools/audio-helper_git.bb
recipes-openxt/xctools/compleat_git.bb
recipes-openxt/xctools/pci-dm-helper.bb
recipes-openxt/xctools/pmutil_git.bb
recipes-openxt/xctools/xcpmd_git.bb
recipes-openxt/xenclient/dm-wrapper_git.bb
recipes-openxt/xenclient/libdmbus_git.bb
recipes-openxt/xenclient/libsurfman_git.bb
recipes-openxt/xenclient/surfman_git.bb
recipes-openxt/xenclient/xenclient-dbusbouncer_1.0.bb
recipes-openxt/xenclient/xenclient-input-daemon_git.bb
recipes-openxt/xenclient/xenclient-rpcgen_git.bb
recipes-openxt/xenclient/xenclient-sha1sum_1.0.bb
recipes-sato/midori/midori_0.1.8.bb
recipes-security/selinux/qemu-wrappers_1.0.bb
recipes-security/selinux/selinux-load_1.0.bb
recipes-security/selinux/svirt-interpose_1.0.bb

OXT-308
See https://github.com/OpenXT/xenclient-oe/pull/121

Push configuration data into recipes

---

recipes-core/rhino/rhino_1.7r2.bbappend

rhino: fix URL

---

recipes-kernel/linux/linux-xenclient-3.18/usbback-base.patch

[vusb] Return actual ISOCH error count from the back end.

---

recipes-extended/xen/files/xsa-156-cpu-lockup-during-exception-delivery.patch
recipes-extended/xen/xen.inc

Add XSA-156 patch to Xen patch-queue.
See: http://xenbits.xen.org/xsa/advisory-156.html

Backport XSA-156.

---

recipes-kernel/linux/4.1/linux-openxt_4.1.13.bb
recipes-kernel/linux/4.1/patches/xsa-155-qsb-023-add-RING_COPY_RESPONSE.patch
recipes-kernel/linux/4.1/patches/xsa-155-qsb-023-xen-blkfront-make-local-copy-of-response-before-usin.patch
recipes-kernel/linux/4.1/patches/xsa-155-qsb-023-xen-blkfront-prepare-request-locally-only-then-put-i.patch
recipes-kernel/linux/4.1/patches/xsa-155-qsb-023-xen-netfront-add-range-check-for-Tx-response-id.patch
recipes-kernel/linux/4.1/patches/xsa-155-qsb-023-xen-netfront-copy-response-out-of-shared-buffer-befo.patch
recipes-kernel/linux/4.1/patches/xsa-155-qsb-023-xen-netfront-do-not-use-data-already-exposed-to-back.patch

Qubes Security Bulleting #23:
https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-023-2015.txt
Original patches:
https://github.com/QubesOS/qubes-linux-kernel/tree/stable-3.18/patches.xen
OXT-461

XSA-155 Qubes OS frontend fixes for LInux 4.1

---

recipes-kernel/linux/4.1/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.1/patches/usbback-base.patch
recipes-kernel/linux/4.1/patches/xenbus-move-otherend-watches-on-relocate.patch

Same as https://github.com/OpenXT/xenclient-oe/pull/222 for Linux 4.1

Linux 4.1 missing bits

---

recipes-kernel/linux/4.4/patches/usbback-base.patch

Commit 7048bea53ef8ad3e22a79800dae6d2c5d5fdd36f lost during 4.4 uprev.

[linux-4.4] Add missing commit.

---

recipes-openxt/xenclient/xenclient-installer-tweaks/status-report
recipes-openxt/xenclient/xenclient-root-ro/init.root-ro

See OXT-508 for a description of the issue.

Update tpm path to the correct usage in 4.0 Kernel or later

---

recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.kernel.domain.diff
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/upstream-allow-loadkeys-to-read-usr_t-files.patch
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/upstream-enable-asound.state.lock-support.patch
recipes-security/refpolicy/refpolicy-mcs-2.20140311/policy/modules/admin/vhdutils.te
recipes-security/refpolicy/refpolicy-mcs-2.20140311/policy/modules/services/updatemgr.te
recipes-security/refpolicy/refpolicy-mcs_2.20140311.bbappend

Various fixes for SELinux denials seen in dom0.

Dom0 policy fixes

---

recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.conf.patch
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.contrib.dbus.diff
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.contrib.networkmanager.diff
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.kernel.files.diff
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.system.mount.diff
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.system.sysnetwork.patch
recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.system.udev.diff
recipes-security/refpolicy/refpolicy-mcs-2.20140311/policy/modules/apps/db-cmd.te

Policy fixes for denials in the ndvm.

Ndvm policy fixes

---

recipes-kernel/linux-libc-headers/linux-libc-headers_4.4.6.bb
recipes-kernel/linux/4.4/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.4/linux-openxt_4.4.6.bb
recipes-kernel/linux/4.4/patches/acpi-video-delay-init.patch
recipes-kernel/linux/4.4/patches/extra-mt-input-devices.patch
recipes-kernel/linux/4.4/patches/gem-foreign.patch
recipes-kernel/linux/4.4/patches/usbback-base.patch

Upgrade linux 4.4 kernel to latest micro.

[linux-4.4] Upgrade to 4.4.6.

---

recipes-kernel/linux-libc-headers/linux-libc-headers_3.18.28.bb
recipes-kernel/linux/3.18/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/3.18/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/3.18/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/3.18/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/3.18/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/3.18/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/3.18/linux-openxt_3.18.28.bb
recipes-kernel/linux/3.18/patches/bridge-carrier-follow-prio0.patch
recipes-kernel/linux/3.18/patches/gem-foreign.patch
recipes-kernel/linux/3.18/patches/usbback-base.patch
recipes-kernel/linux/3.18/patches/xsa-157-linux-pciback-missing-sanity-checks-leading-to-crash.patch

Upgrade linux 3.18 kernel to latest micro

[linux-3.18] Upgrade to 3.18.28.

---

recipes-extended/xen/xen-blktap.bb

[blktap2] Add split our recipe for blktap2 to avoid circular deps in OE.

---

recipes-extended/xen/xen-tools.bb

[blktap2] Do not continue to build blktap in the xen-tools recipe.

---

recipes-openxt/xctools/heimdallr_git.bb

Add proper license and checksum to heimdallr recipe

---

recipes-openxt/xctools/heimdallr_git.bb

Fix the SRCREV to point to the current tip rev.

---

recipes-core/packagegroups/packagegroup-xenclient-dom0.bb

dom0: re-add resize2fs

---

recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg

grub.cfg: don't show menu by default and fix indentation

---

recipes-bsp/grub/grub-git/no-multiboot-display-reset.patch
recipes-bsp/grub/grub-git/remove-editing-and-shell.patch
recipes-bsp/grub/grub_git.bbappend
recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg

Re-add grub patches to block edit and shell and show the splash screen.

Grub fixup

---

recipes-openxt/qemu-dm/qemu-dm-1.4/0006-dmbus.patch
recipes-openxt/qemu-dm/qemu-dm-1.4/0008-switcher.patch

Remove handling for defunct dmbus interfaces related to XenGFX.
OXT-560

Remove unsused dmbus RPC

---

recipes-kernel/linux/4.4/linux-openxt_4.4.10.bb
recipes-kernel/linux/4.4/patches/mm-Use-phys_addr_t-for-reserve_bootmem_region-argume.patch

linux: fix reserved bootmem

---

recipes-connectivity/openssh/openssh6.inc
recipes-connectivity/openssh/openssh_6.1p1.bb
recipes-extended/rsyslog/rsyslog_5.6.5.bb
recipes-openxt/xenclient/libsurfman_git.bb

Silence some warnings related to openssh, rsyslog, libsurfman.

Silence some QA warnings.

---

recipes-connectivity/openssh/files/scpv4v
recipes-connectivity/openssh/files/sshv4v

sshv4v, scpv4v: bind client socket to a specific port (12222)

---

recipes-core/initscripts/initscripts-1.0/finish.sh
recipes-core/initscripts/initscripts-1.0/populate-volatile.sh
recipes-core/initscripts/initscripts-1.0/xenclient-ndvm/finish.sh
recipes-core/sysvinit/sysvinit/rcS-default

initscripts: remove initscript code that's incompatible with read-only rootfs

---

recipes-extended/xen/files/xc-xt-v4v-viptables.patch

viptables: xen: fix list logic and add missing static

---

recipes-core/busybox/busybox-1.23.2/defconfig

busybox: enable cpio archive creation

---

recipes-core/images/xenclient-initramfs-image.bb

Make sure the trousers configuration file has correct file permissions

---

recipes-core/images/xenclient-uivm-image.bb
recipes-core/initscripts/initscripts-1.0/bootmisc.sh
recipes-core/initscripts/initscripts-1.0/xenclient-dom0/bootmisc.sh
recipes-core/initscripts/initscripts-1.0/xenclient-uivm/bootmisc.sh

uivm: remove hwclock

---

recipes-openxt/xenclient/vusb/vusb-daemon_git.bb

vusb-daemon: add missing udev dependency

---

recipes-openxt/qemu-dm/qemu-dm.inc

http://docs.openstack.org/security-guide/compute/hardening-the-virtualization-layers.html
Also use pixman from the QEMU tree since it is built.
OXT-604

Qemu hardening

---

recipes-extended/xen/files/xc-xt-xenconsoled-syslog.patch

xenconsoled: fix hypervisor logging

---

recipes-core/packagegroups/packagegroup-xenclient-extra.bb

extra packages: add lsof

---

recipes-core/images/xenclient-ndvm-image.bb

NDVM: disable getty on /dev/tty1

---

recipes-core/images/xenclient-syncvm-image.bb
recipes-core/images/xenclient-uivm-image.bb
recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
recipes-core/sysvinit/sysvinit/rc
recipes-core/udev/udev_182.bbappend
recipes-openxt/xenclient/sync-client_git.bb

Remove the bootage legacy initscript manager and revert to sysvinit
usual management.
OXT-59

Remove bootage

---

recipes-extended/iasl/iasl_20120215.bb

(cherry picked from commit acf055ffdda73277a96ce2bb5e6388057500a2df)

STABLE-5: iasl: switch to github for the source tarball

---

conf/distro/openxt-main.conf
recipes-extended/rsyslog/files/rsyslog.logrotate
recipes-extended/rsyslog/files/xenclient-dom0/rsyslog.conf
recipes-extended/rsyslog/files/xenclient-ndvm/rsyslog.conf
recipes-extended/rsyslog/files/xenclient-stubdomain/rsyslog.conf
recipes-extended/rsyslog/files/xenclient-syncvm/rsyslog.conf
recipes-extended/rsyslog/files/xenclient-uivm/rsyslog.conf
recipes-extended/rsyslog/rsyslog_%.bbappend

Upgrading addresses a couple of CVEs.
Also cleanup the configuration files.
OXT-670

OXT-670: rsyslog upgrade to follow OE revision

---

recipes-openxt/qemu-dm/qemu-dm-1.4/0024-Xenstore-based-ISO-media-change-detection-for-both-s.patch

qemu: fix iso media change code

---

recipes-openxt/qemu-dm/qemu-dm-1.4/0024-Xenstore-based-ISO-media-change-detection-for-both-s.patch

qemu: fix the iso media change code fix

---

recipes-openxt/qemu-dm/qemu-dm-1.4/0024-Xenstore-based-ISO-media-change-detection-for-both-s.patch

OXT-372
OXT-632
(cherry picked from commit 95161396585b2776a378be1656346cdce6eac50d)

STABLE-6: qemu: fix iso media change code

---

recipes-kernel/linux-libc-headers/linux-libc-headers_4.4.16.bb
recipes-kernel/linux/4.4/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/4.4/linux-openxt_4.4.16.bb

OXT-695: Linux: Upgrade to Linux 4.4.16

---

recipes-kernel/linux-libc-headers/linux-libc-headers_4.4.16.bb
recipes-kernel/linux/4.4/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/4.4/linux-openxt_4.4.16.bb

OXT-695
(cherry picked from commit 5b7e70e4f4b710fed4ee6d3a8946a41e11448145)

Stable-6: OXT-695: Upgrade to Linux 4.4.16

---

recipes-devtools/ocaml/ocaml-cross/finaliser-on-weak-array-gives-dangling-pointers.patch
recipes-devtools/ocaml/ocaml-cross_git.bb

(cherry picked from commit 96efced298fa5b0379f0b4ea2fba291c0ad21aca)

STABLE-6: ocaml: backport crash fix

---

recipes-core/packagegroups/packagegroup-xenclient-dom0.bb

STABLE-6: WORKAROUND: remove microcode tools and data

---

recipes-openxt/xenclient/xenclient-root-ro/init.root-ro

[ui] Change XenClient to OpenXT in the measured launch dialogs.

---

recipes-extended/xen/files/blktap2-libvhd-atomic-write-helpers.patch
recipes-extended/xen/files/blktap2-miscellaneous-oxt-fixes.patch
recipes-extended/xen/files/blktap2-tap-ctl-optional-pid-ro-mount.patch
recipes-extended/xen/files/blktap2-vhd-encryption-support.patch
recipes-extended/xen/files/blktap2-vhd-icbinn-support.patch
recipes-extended/xen/files/blktap2-vhd-keyhash-support.patch
recipes-extended/xen/files/blktap2-vhd-marker-flag.patch
recipes-extended/xen/files/blktap2-vhd-print-allocated-virtblock-list.patch
recipes-extended/xen/files/hvm-info.patch
recipes-extended/xen/files/v4v-viptables.patch
recipes-extended/xen/files/xsa-155-paravirtualized-drivers-incautious-about-shared-memory-contents.patch
recipes-extended/xen/files/xsa-182-x86-privilege-escalation-in-pv-guests.patch

xen: sanitize patchqueue

---

recipes-graphics/xdotool/xdotool_2.inc

xdotool: fix URL

---

recipes-graphics/xdotool/xdotool_2.inc

(cherry picked from commit b055dab83174788d2b2ebb8ab7639c0d94bdf70a)

STABLE-6: xdotool: fix URL

---

recipes-graphics/xdotool/xdotool_2.inc

(cherry picked from commit b055dab83174788d2b2ebb8ab7639c0d94bdf70a)

STABLE-5: xdotool: fix URL

---

recipes-extended/iasl/iasl_20120215.bb
recipes-graphics/xdotool/xdotool_2.inc

(cherry picked from commit b055dab83174788d2b2ebb8ab7639c0d94bdf70a)

STABLE-4: fix recipe URLs

---

recipes-core/rhino/rhino_1.7r2.bbappend

(cherry picked from commit 92bd42d7a895a48d3ecc808ab1bb5bd6b002c581)

STABLE-4: rhino: fix URL

---

recipes-security/selinux/refpolicy-mcs/policy.modules.contrib.networkmanager.diff

This a rebase of this PR:
https://github.com/OpenXT/xenclient-oe/pull/258
OXT-317

STABLE-5: Fix NDVMs losing custom settings in the domstore.

---

recipes-security/selinux/refpolicy-mcs/openxt-ota-fixes.patch
recipes-security/selinux/refpolicy-mcs_2.20130424.bbappend

[upgrade] STABLE-4: Fix updatemgr to allow access to /config files.

---

recipes-extended/xen/files/opt-disable-vmcs-shadowing.patch

[xen] Comments on VMCS disable shadowing option patch.

---

recipes-extended/xen/files/gpt-s3-resume-reason.patch

[xen] Document the ACPI PM1A resume status patch.

---

recipes-extended/xen/files/xsa-190-x86-hvm-instr-emul-guest-user-mode-missing-exception.patch
recipes-extended/xen/xen.inc

http://xenbits.xen.org/xsa/advisory-190.html

[xen] XSA-190

---

recipes-extended/xen/files/xsa-190-x86-hvm-instr-emul-guest-user-mode-missing-exception.patch
recipes-extended/xen/xen.inc

http://xenbits.xen.org/xsa/advisory-190.html

[xen] XSA-190 patch applied to Xen 4.3.4 for OpenXT stable-6

---

recipes-extended/xen/files/increase-ap-startup-time.patch
recipes-extended/xen/xen.inc

[xen] Increase AP startup timeout when TBOOT launches Xen.

---

recipes-core/base-files/base-files/fstab.xenclient-dom0
recipes-core/initscripts/initscripts_1.0.bbappend

initscripts: convert do_install to do_install_append

---

recipes-kernel/linux/4.4/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.4/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/4.4/linux-openxt_4.4.27.bb
recipes-kernel/linux/4.4/patches/xenstore-no-read-vs-write-atomicity.patch

[linux] Upgrade to Linux 4.4.27

---

recipes-core/images/xenclient-dom0-image.bb
recipes-core/packagegroups/packagegroup-openxt-test.bb
recipes-devtools/bats/bats_git.bb
recipes-openxt/bats-testsuite/bats-testsuite_git.bb

This adds a bash based test framework that can be used to do system checkout before submitting PRs.
Resolves: #OXT-788

Test framework

---

recipes-kernel/linux/4.4/linux-openxt_4.4.27.bb

Use cdn.kernel.org (https://www.kernel.org/introducing-fastly-cdn.html).

Linux change tarball source.

---

recipes-extended/xen/xen-blktap.bb

xen-blktap: install headers

---

recipes-core/initscripts/initscripts-1.0/populate-volatile.sh

OXT-814 : fix populate-volatile.sh link creation logic

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/acpi.patch

See the ticket and the comments for more information.
OXT-813

[QEMU-2.6.2] Fix broken Sx functionality.

---

recipes-openxt/xctools/qmp-helper_git.bb

Add qmp-helper recipe

---

recipes-extended/xen/files/allow-pat-cacheattrs-for-all-domains.patch

[xen] Comment allow PAT cacheattr patch.

---

recipes-extended/xen/files/hvm-rtc.patch

[xen] Comment HVM RTC patch as best as possible.

---

recipes-extended/xen/files/xsa-191-x86-null-segments-not-always-treated-as-unusable.patch
recipes-extended/xen/files/xsa-192-x86-task-switch-to-vm86-mode-mis-handled.patch
recipes-extended/xen/files/xsa-193-x86-segment-base-write-emulation-lacking-canonical-address-checks.patch
recipes-extended/xen/files/xsa-195-x86-64-bit-bit-test-instruction-emulation-broken.patch
recipes-extended/xen/files/xsa-196-x86-software-interrupt-injection-mis-handled.patch
recipes-extended/xen/xen.inc
recipes-openxt/qemu-dm/qemu-dm-2.6.2/xsa-197-qemu-incautious-about-shared-ring-processing.patch
recipes-openxt/qemu-dm/qemu-dm.inc

XSA-194: Xen 4.6 is not affected.
XSA-198: OpenXT does not use pygrub.
OXT-842

OXT-842: XSAs, november 2016

---

recipes-openxt/qemu-dm/qemu-dm-1.4/xsa-199-qemu-ioport-array-overflow.patch
recipes-openxt/qemu-dm/qemu-dm.inc

https://xenbits.xen.org/xsa/advisory-199.html
OXT-859

STABLE-6: OXT-859: XSA-199

---

recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg

Bump dom0 memory from 320M to 420M

---

recipes-openxt/qemu-dm/qemu-dm-1.4/0013-xenmou.patch

STABLE-6: qemu: xenmou: accept all scrolls, not just 1 and -1

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/xenmou.patch

qemu: xenmou: accept all scrolls, not just 1 and -1

---

recipes-extended/xen/files/xsa-200-x86-cmpxchg8b-emulation-fails-to-ignore-operand-size-override.patch
recipes-extended/xen/files/xsa-202-x86-pv-guests-may-be-able-to-mask-interrupts.patch
recipes-extended/xen/files/xsa-204-x86-mishandling-of-syscall-singlestep-during-emulation.patch
recipes-extended/xen/xen.inc

Port latest XSAs released in december 2016.
OXT-879

STABLE-6: OXT-879: XSA-200, XSA-202 and XSA-204

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/switcher.patch

qemu: implement scroll handling with the new api

---

recipes-extended/xen/files/libxl-RFC-4of7-Add-stubdomain-version-tools-domain-build-info.patch
recipes-extended/xen/files/libxl-RFC-5of7-Handle-Linux-stubdomain-specific-QEMUoptions.patch
recipes-extended/xen/files/libxl-RFC-6of7-Build-the-domain-with-a-Linux-based-stubdomain.patch
recipes-extended/xen/files/libxl-RFC-7of7-Wait-for-QEMU-startup-in-stubdomain.patch
recipes-extended/xen/files/libxl-RFC-fixes.patch
recipes-extended/xen/files/libxl-crypto-key-dir.patch
recipes-extended/xen/files/libxl-display-manager-support.patch
recipes-extended/xen/files/libxl-do-not-destroy-in-use-tapdevs.patch
recipes-extended/xen/files/libxl-domain-state.patch
recipes-extended/xen/files/libxl-fix-reboot.patch
recipes-extended/xen/files/libxl-fixup-cmdline-ops.patch
recipes-extended/xen/files/libxl-linux-stubdom-replace-disk-with-initramfs.patch
recipes-extended/xen/files/libxl-misc-fixes.patch
recipes-extended/xen/files/libxl-move-extra-qemu-args-to-the-end.patch
recipes-extended/xen/files/libxl-openxt-helpers.patch
recipes-extended/xen/files/libxl-openxt-qemu-args.patch
recipes-extended/xen/files/libxl-openxt-tweaks.patch
recipes-extended/xen/files/libxl-openxt-xci-cpuid-signature.patch
recipes-extended/xen/files/libxl-pass-qemu-options-through-linux-stubdom-cmdline.patch
recipes-extended/xen/files/libxl-stubdom-options.patch
recipes-extended/xen/files/libxl-syslog.patch
recipes-extended/xen/files/libxl-vif-make-ioemu-and-stubdom-mac-addresses-configurable.patch
recipes-extended/xen/files/libxl-xenmgr-support.patch
recipes-extended/xen/xen-libxl.bb
recipes-extended/xen/xen.inc

libxl: add xen patches for OpenXT compatibility

---

recipes-core/base-files/base-files/fstab.xenclient-dom0
recipes-core/images/xenclient-dom0-image.bb
recipes-core/initscripts/initscripts-1.0/xenclient-dom0/mountall.sh
recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
recipes-core/packagegroups/packagegroup-xenclient-installer.bb
recipes-openxt/initrdscripts/initramfs-xenclient/xenclient-stubdomain/init.sh
recipes-openxt/xenclient/xenclient-dom0-tweaks/xenstore-init
recipes-openxt/xenclient/xenmgr/xenmgr_git.bb

libxl: dom0 fixes

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/switcher.patch

Reverts OpenXT/xenclient-oe#498

Revert "qemu: implement scroll handling with the new api"

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/acpi-pm-feature.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/exit-mainloop-on-reset.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/openxt-misc-fixes.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/qmp-v4v-char-driver.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/surfman-dcl.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/switcher.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/use-relative-xenstore-nodes.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/write-acpi-state-to-xenstore.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/xsa-197-qemu-incautious-about-shared-ring-processing.patch
recipes-openxt/qemu-dm/qemu-dm-stubdom/qemu-ifup-stubdom
recipes-openxt/qemu-dm/qemu-dm.inc

libxl: add qemu patches for libxl compatibility

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/switcher.patch

Rebased mouse scroll fix originally from Jed.

---

recipes-core/images/xenclient-initramfs-image.bb
recipes-core/packagegroups/packagegroup-xenclient-installer.bb
recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
recipes-openxt/openxt/openxt-keymanagement/key-functions
recipes-openxt/openxt/openxt-keymanagement_1.0.bb
recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
recipes-openxt/openxt/openxt-measuredlaunch/seal-system
recipes-openxt/openxt/openxt-measuredlaunch_1.0.bb
recipes-openxt/tboot/tboot-1.8.3/0001-Add-a-PCR-calculator-to-predict-measurements.patch
recipes-openxt/tboot/tboot_1.8.3.bb
recipes-openxt/xenclient/xenclient-config-access/config-access.initscript
recipes-openxt/xenclient/xenclient-cryptdisks/crypttab
recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
recipes-openxt/xenclient/xenclient-tpm-setup/tpm-setup
recipes-openxt/xenclient/xenclient-tpm-setup_1.0.bb

This refactors the measured launch capability to enable a forward seal capability. This pull request is reliant on pull request #26 for the installer repository
OXT-536

Adding the new Measured Launch architecture

---

recipes-extended/xen/files/xen-init-dom0.initscript
recipes-extended/xen/xen-libxl.bb
recipes-openxt/xenclient/xenclient-dom0-tweaks/xenstore-init

libxl: install and run xen-init-dom0 at boot time

---

recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/network-daemon.te

refpolicy: allow nwd to call xl

---

recipes-connectivity/mobile-broadband-provider-info/mobile-broadband-provider-info_git.bb

Remove warning caused by OE not knowing about CCPD

---

recipes-extended/xen/files/libxl-pci-passthrough-fixes.patch
recipes-extended/xen/xen.inc

libxl: fix PCI passthrough with stubdoms

---

recipes-core/jamvm/jamvm_git.bbappend

jamvm: fix borken URL, switch from sf to github

---

recipes-core/init-ifupdown/init-ifupdown_1.0.bbappend
recipes-core/initscripts/initscripts_1.0.bbappend

unset SRC_URI_OVERRIDES_PACKAGE_ARCH in a couple of recipes

---

recipes-openxt/xctools/atapi-pt-helper_git.bb
recipes-openxt/xctools/audio-helper_git.bb
recipes-openxt/xctools/qmp-helper_git.bb

helpers: include debug symbols in -dbg packages

---

recipes-openxt/linux-input/linux-input_git.bb

linux-input: fix broken URI

---

recipes-openxt/xenclient/xenclient-toolstack_git.bb

[toolstack] Remove uneeded OCaml modules in libs.

---

recipes-extended/xen/files/libxl-syslog.patch

libxl: don't create logfiles for qemu instances

---

recipes-core/jdepend/jdepend_%.bbappend

jdepend: change URL to github

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/xenstore-based-ISO-media-change-detection-for-both-s.patch

Get the BlockBackend name directly from the device we have already.

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/acpi-pm-feature.patch

[acpi] Report lid always open on systems w/o lids (.e.g desktops).

---

recipes-core/jdepend/jdepend_%.bbappend

(cherry picked from commit c07478e6569f9a9adaa3ec5a6be5626aa7f41dff)

STABLE-6: jdepend: change URL to github

---

recipes-devtools/file/file_5.24.bbappend

file: use release tarball instead of git

---

recipes-devtools/file/file_5.24.bbappend

OXT-1021
(cherry picked from commit 9e8ab12c3bbdde057e1abda0ed06d40bc57f1b2e)

STABLE-6: file: use release tarball instead of git

---

recipes-extended/xen/files/libxl-vwif-support.patch
recipes-extended/xen/xen-common.inc
recipes-kernel/linux/4.9/linux-openxt_4.9.11.bb
recipes-kernel/linux/4.9/patches/netback-vwif-support.patch

Add VWIF support to libxl and Linux netback

---

recipes-extended/xen/files/libxl-atapi-pt.patch
recipes-extended/xen/xen-common.inc

libxl: add atapi-pt disk support

---

recipes-openxt/xenclient/xenclient-toolstack/vif
recipes-openxt/xenclient/xenclient-toolstack/xenclient-dom0/vif
recipes-openxt/xenclient/xenclient-toolstack/xenclient-ndvm/vif
recipes-openxt/xenclient/xenclient-toolstack/xenclient-nilfvm/vif

udev vif scripts: the opposite of "online" is "offline", not "remove"

---

recipes-extended/xen/files/libxl-atapi-pt.patch

libxl: atapi-pt: fix syntax and allow readwrite

---

recipes-extended/xen/files/libxl-do-not-destroy-in-use-tapdevs.patch

libxl: really destroy tapdevs when nothing else is using them

---

recipes-extended/xen/files/libxl-misc-fixes.patch
recipes-extended/xen/files/libxl-vwif-support.patch

libxl: do not wait for nic backend nodes to disappear, they wont

---

recipes-devtools/file/file_5.24.bbappend

OXT-1021: file: use source tarball from tagged releases.

---

recipes-devtools/file/file_5.24.bbappend

(cherry picked from commit 6e6d40b62ba9b72f98cf0509a0cf54e9d926f999)

STABLE-6: OXT-1021: file: use source tarball from tagged releases.

---

recipes-extended/xen/files/libxl-vwif-support.patch
recipes-extended/xen/files/libxl-xenmgr-support.patch

Merge of https://github.com/OpenXT/xenclient-oe/pull/603 and https://github.com/OpenXT/xenclient-oe/pull/591

OXT-1011 Fixes

---

recipes-kernel/linux-firmware/linux-firmware_git.bb

Add misc linux wifi firmware drivers

---

recipes-extended/xen/files/acpi-slic-support.patch
recipes-extended/xen/xen-common.inc

[acpi] Change OEM IDs in ACPI tables to allow OEM media installs.

---

recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
recipes-extended/xen/xen-libxl.bb
recipes-extended/xen/xen-ocaml-libs.bb
recipes-extended/xen/xen.bb
recipes-openxt/db-tools/db-tools_git.bb
recipes-openxt/xenclient/uid_git.bb
recipes-openxt/xenclient/xenclient-toolstack_git.bb

Remove dependency on xen-libxl for non-dom0 machines

---

recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
recipes-extended/xen/xen-libxl.bb
recipes-extended/xen/xen-ocaml-libs.bb
recipes-extended/xen/xen.bb
recipes-openxt/db-tools/db-tools_git.bb
recipes-openxt/xenclient/uid_git.bb
recipes-openxt/xenclient/xenclient-toolstack_git.bb

STABLE-7: Remove dependency on xen-libxl for non-dom0 machines

---

recipes-kernel/linux/4.9/linux-openxt_4.9.27.bb
recipes-kernel/linux/4.9/patches/extra-mt-input-devices.patch
recipes-kernel/linux/4.9/patches/gem-foreign.patch
recipes-kernel/linux/4.9/patches/pci-pt-flr.patch
recipes-kernel/linux/4.9/patches/realmem-mmap.patch
recipes-kernel/linux/4.9/patches/usbback-base.patch

linux-openxt: Version bump to 4.9.27

---

recipes-kernel/linux/4.9/linux-openxt_4.9.27.bb
recipes-kernel/linux/4.9/patches/extra-mt-input-devices.patch
recipes-kernel/linux/4.9/patches/gem-foreign.patch
recipes-kernel/linux/4.9/patches/pci-pt-flr.patch
recipes-kernel/linux/4.9/patches/realmem-mmap.patch
recipes-kernel/linux/4.9/patches/usbback-base.patch

STABLE-7: linux-openxt: Version bump to 4.9.27

---

recipes-openxt/xenclient/dbd_git.bb

dbd: re-add xenclient-toolstack dependency

---

recipes-openxt/xenclient/dbd_git.bb

OXT-1133
(cherry picked from commit 53d2918baabe0c73f4d73cc176171af2cdb03fd6)

STABLE-7: dbd: re-add xenclient-toolstack dependency

---

recipes-openxt/openxt/openxt-keymanagement/key-functions
recipes-openxt/openxt/openxt-measuredlaunch/seal-system
recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions

STABLE-7: [tpm2.0] Only support single bank sealing sha256

---

recipes-openxt/openxt/openxt-keymanagement/key-functions
recipes-openxt/openxt/openxt-measuredlaunch/seal-system
recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions

[tpm2.0] Only support single bank sealing sha256

---

recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.system.lvm.diff
recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.te
recipes-support/lvm2/lvm2/lvm.conf

Authorize updatemgr to read certificates and configuration required for
openssl.

OXT-1124: updatemgr: SELinux perms to read ssl certs files.

---

recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.system.lvm.diff
recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.te
recipes-support/lvm2/lvm2/lvm.conf

Authorize updatemgr to read certificates and configuration required for openssl.

STABLE-7: OXT-1124: updatemgr: SELinux perms to read ssl certs files.

---

recipes-core/images/xenclient-initramfs-image.bb
recipes-core/images/xenclient-initramfs-image/initramfs-lvm.conf
recipes-support/lvm2/lvm2/lvm.conf
recipes-support/lvm2/lvm2_%.bbappend

https://github.com/OpenXT/xenclient-oe/pull/701

STABLE-7: OXT-1159 & OXT-1160: Attend lvm errors and warnings

---

recipes-openxt/xenclient/surfman/surfman.initscript
recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/surfman.te

Allow surfman to coredump

---

recipes-openxt/tss/tpm2.0-tools/tpm2-fix-forward-seal.patch
recipes-openxt/tss/tpm2.0-tools_git.bb

[tpm2.0] Fix arg parsing when passing in hash for

---

recipes-openxt/tss/tpm2.0-tools/tpm2-extendpcr-support.patch

[tpm2.0-tools] Convert from ascii hash to binary

---

recipes-extended/xen/files/libxl-openxt-qemu-args.patch
recipes-extended/xen/files/libxl-vwif-support.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/nic-link-state-propagation.patch

Fix link state on emulated NICs

---

recipes-openxt/tss/tpm2.0-tools/tpm2-fix-forward-seal.patch
recipes-openxt/tss/tpm2.0-tools_git.bb

STABLE-7: [tpm2.0] Fix arg parsing when passing in hash for

---

recipes-openxt/tss/tpm2.0-tools/tpm2-extendpcr-support.patch

STABLE-7: [tpm2.0-tools] Convert from ascii hash to binary

---

recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions

[tpm2.0] Take ownership of lockout hierarchy

---

recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions

STABLE-7: [tpm2.0] Take ownership of lockout hierarchy

---

recipes-extended/xen/xen.bb
recipes-openxt/xenclient/ipxe_git.bb

(cherry picked from commit c01c1c692c936b8bf2ca0172229a6436fd75d627)

STABLE-7: ipxe: switch to e1000

---

recipes-extended/xen/xen.bb
recipes-openxt/xenclient/ipxe_git.bb

ipxe: switch to e1000

---

recipes-extended/xen/files/libxl-openxt-qemu-args.patch
recipes-extended/xen/files/libxl-vwif-support.patch
recipes-openxt/qemu-dm/qemu-dm-2.6.2/nic-link-state-propagation.patch

STABLE-7: Fix link state on emulated NICs

---

recipes-openxt/openxt/openxt-keymanagement/key-functions
recipes-openxt/xenclient/xenclient-config-access/config-access.initscript

OXT-1202: Increase LUKS iterations

---

recipes-openxt/openxt/openxt-keymanagement/key-functions
recipes-openxt/xenclient/xenclient-config-access/config-access.initscript

STABLE-7: OXT-1202: Increase LUKS iterations

---

recipes-extended/xen/files/evtchn-do-not-set-pending-if-s3.patch

No code change, documentation in comments only.

Add patch documentation to evtchn-do-not-set-pending-if-s3.patch

---

recipes-extended/xen/files/0001-gnttab-dont-use-possibly-unbounded-tail-calls.patch
recipes-extended/xen/files/0002-gnttab-fix-transitive-grant-handling.patch
recipes-extended/xen/files/xsa227-4.6.patch
recipes-extended/xen/files/xsa228-4.8.patch
recipes-extended/xen/files/xsa230.patch
recipes-extended/xen/xen-common.inc
recipes-kernel/linux/4.9/linux-openxt_4.9.40.bb
recipes-kernel/linux/4.9/patches/xsa229.patch

STABLE-7: OXT-1205: xsa: 226, 227, 228, 229, 230

---

recipes-extended/xen/files/xsa226-4.9/0001-gnttab-dont-use-possibly-unbounded-tail-calls.patch
recipes-extended/xen/files/xsa226-4.9/0002-gnttab-fix-transitive-grant-handling.patch
recipes-extended/xen/files/xsa227.patch
recipes-extended/xen/files/xsa228.patch
recipes-extended/xen/files/xsa230.patch
recipes-extended/xen/files/xsa235-4.9.patch
recipes-extended/xen/xen-common.inc
recipes-kernel/linux/4.9/linux-openxt_4.9.40.bb
recipes-kernel/linux/4.9/patches/xsa229.patch

OXT-1205: xsa: 226, 227, 228, 229, 230

---

recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg

xen: fix cmdline syntax to enforce flask

---

recipes-extended/xen/files/libxl-xenmgr-support.patch

xen-libxl: write "hotplug-status" for nics too

---

recipes-extended/xen/files/xsa231-4.9.patch
recipes-extended/xen/files/xsa232.patch
recipes-extended/xen/files/xsa233.patch
recipes-extended/xen/files/xsa234-4.9.patch
recipes-extended/xen/files/xsa235-4.9.patch
recipes-extended/xen/xen-common.inc

OXT-1215: xsa: 231, 232, 233, 234.

---

recipes-extended/xen/files/xsa231-4.7.patch
recipes-extended/xen/files/xsa232.patch
recipes-extended/xen/files/xsa233.patch
recipes-extended/xen/files/xsa234-4.6.patch
recipes-extended/xen/files/xsa235-4.6.patch
recipes-extended/xen/xen-common.inc

STABLE-7: OXT-1215: xsa: 231, 232, 233, 234, 235.

---

recipes-core/images/xenclient-installer-part2-image.bb

control.tar.bz2: remove new useless directories

---

recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/xc-files-interfaces.patch
recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/xc-files.if

selinux: allow udev to probe iso files

---

recipes-extended/xen/xen-blktap.bb
recipes-extended/xen/xen-libxl.bb
recipes-extended/xen/xen.bb

xen recipes: silence QA warnings and re-add xen-init-dom0

---

recipes-extended/xen/files/xsa226-4.6/0001-gnttab-dont-use-possibly-unbounded-tail-calls.patch
recipes-extended/xen/files/xsa226-4.6/0002-gnttab-fix-transitive-grant-handling.patch
recipes-extended/xen/files/xsa227-4.6.patch
recipes-extended/xen/files/xsa228-4.8.patch
recipes-extended/xen/files/xsa230.patch
recipes-extended/xen/files/xsa231-4.7.patch
recipes-extended/xen/files/xsa232.patch
recipes-extended/xen/files/xsa233.patch
recipes-extended/xen/files/xsa234-4.6.patch
recipes-extended/xen/files/xsa235-4.6.patch
recipes-extended/xen/xen.inc

STABLE-6: OXT-1214: xen: XSA 226-228 & 230-235

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/atapi-pass-through.patch

qemu: atapi-pt: fix burn issue

---

recipes-openxt/qemu-dm/qemu-dm-2.6.2/atapi-pass-through.patch

OXT-1055
(cherry picked from commit 02695ff6771c594705ca89cac8a358cef32fb72c)

STABLE-7: OXT-1055: qemu: atapi-pt: fix burn issue

---

recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/rpcproxy.te

refpolicy: rpc-proxy: allow to signal itself

---

recipes-extended/ustr/ustr/ustr-makefile-fix.patch
recipes-extended/ustr/ustr_1.0.4.bbappend

ustr: use github instead of unreliable and.org

---

recipes-devtools/python/python-ipy_0.83.bbappend

python-ipy: fix URL to use https and make wget happy

---

recipes-devtools/python/python-daemon_1.5.5.bb

STABLE-6: python-daemon: fix url

---

recipes-devtools/python/python-ipy_0.83.bbappend

(cherry picked from commit ae9d97a417c662d650de18e7dfc4c8162864a9f7)

STABLE-6: python-ipy: fix URL to use https and make wget happy

---

recipes-extended/xen/files/hvmloader-legacy-seabios-optionroms.patch
recipes-extended/xen/files/unmap-shared-info.patch
recipes-extended/xen/files/v4v.patch
recipes-extended/xen/files/xen-translate.patch

Xen with OpenXT patch-queue should pass typesafe.h verification used when building with debug (CONFIG_DEBUG=y -> #define NDEBUG).

xen: Xen debug builds.

---

recipes-devtools/python/python-ipy_0.83.bbappend

(cherry picked from commit ae9d97a417c662d650de18e7dfc4c8162864a9f7)
(cherry picked from commit d8fec4daaa9313489d0f9ff672b883cd1f4ee9dc)

STABLE-7: python-ipy: fix URL to use https and make wget happy

---

recipes-core/images/xenclient-dom0-image.bb
recipes-core/images/xenclient-installer-image.bb

OXT-1248: Add an build option to install ca-certificates in dom0 and the installer

---

recipes-core/images/xenclient-dom0-image.bb
recipes-core/images/xenclient-installer-image.bb

OXT-1248
(cherry picked from commit 410f61ace4d9194629564fa6921c6077db4e38ec)

STABLE-7: OXT-1248: Add an build option to install ca-certificates in dom0 and the installer

---

recipes-extended/xen/xen-ocaml-libs.bb
recipes-openxt/db-tools/db-tools_git.bb
recipes-openxt/xenclient/dbd_git.bb
recipes-openxt/xenclient/uid_git.bb
recipes-openxt/xenclient/xenclient-toolstack_git.bb

Use the bbclass ocaml & findlib and associated variables.
Take the opportunity to remove dead-code.

OXT-1253: ocaml: Use the refactored OpenXT layer.

---

recipes-extended/xen/files/libxl-disable-vnc-query-when-disabled.patch
recipes-extended/xen/xen-common.inc

xl: silence vnc error

---

recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/xc-files-interfaces.patch

selinux: add missing permission to run without a stubdom

---

recipes-extended/xen/files/libxl-iso-hotswap.patch

iso hotswap fix for guests with no stub domain

---

recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.fc

blktap3: add context for control file

---

recipes-core/packagegroups/packagegroup-xenclient-installer.bb

installer: uses parted but doesn't have it... adding.

---

recipes-core/packagegroups/packagegroup-xenclient-installer.bb

(cherry picked from commit c787e108f1f86962d48dfbef55fb5004d3d5a0a7)

STABLE-8: installer: uses parted but doesn't have it... adding.

---

recipes-extended/pam/libpam/pam.d/common-auth
recipes-extended/pam/libpam_1.%.bbappend

libpam: allow empty passwords

---

recipes-extended/pam/libpam/pam.d/common-auth
recipes-extended/pam/libpam_1.%.bbappend

(cherry picked from commit a1c6c94acac66f4d985765f06eb68967056d754c)

STABLE-8: libpam: allow empty passwords

---

recipes-security/selinux/svirt-interpose/svirt-interpose.c

svirt-interpose: fix domid "parsing"

---

recipes-security/selinux/svirt-interpose/svirt-interpose.c

(cherry picked from commit 96fe539ec92a7d98ba2a4f8fb8d317945ff6a30e)

STABLE-8: svirt-interpose: fix domid "parsing"

---

recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.te

refpolicy: fix some tapdisk AVCs

---

recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.te

(cherry picked from commit 9a5db466d7e2aa5f5024bb2f77e0136bd40b30bd)

STABLE-8: refpolicy: fix some tapdisk AVCs

---

recipes-extended/xen/files/libxl-atapi-pt.patch
recipes-extended/xen/files/libxl-vwif-support.patch

xl network-detach is currently broken, seems like changes were missed while porting to xen-4.9

OXT-1301: xl: fix network detach

---

recipes-extended/xen/blktap3.bb
recipes-extended/xen/blktap3/blktap3-vhd-icbinn-support.patch

OXT-1282: blktap3: add icbinn support

---

recipes-extended/xen/blktap3.bb
recipes-extended/xen/blktap3/blktap3-vhd-icbinn-support.patch

STABLE-8: OXT-1282: blktap3: add icbinn support

---

recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
recipes-openxt/xenclient/xenclient-config-access/config-access.initscript
recipes-openxt/xenclient/xenclient-root-ro/init.root-ro

Silence warning:
modprobe: FATAL: Module fbcon not found in directory /lib/modules/4.14.34

OXT-1321: fbcon: The module is now builtin.

---

recipes-openxt/xenclient/v4v-module-headers_git.bb
recipes-openxt/xenclient/v4v-module_git.bb

Stable-8 version of https://github.com/OpenXT/xenclient-oe/pull/900.
https://github.com/OpenXT/openxt/pull/306
https://github.com/OpenXT/v4v/pull/38

STABLE-8: OXT-1322: v4v: Refresh the recipes.

---

recipes-security/selinux/libsemanage_2.7.bbappend

libsemanage: remove runtime dependency on python

---

recipes-security/selinux/libsemanage_2.7.bbappend

(cherry picked from commit 64e31c2131f91ef09b8ca97cda3f00af92a1f96f)

STABLE-8: libsemanage: remove runtime dependency on python

---

classes/xenclient-customtask.bbclass

xenclient-customtask does not work with Python 3 recent versions:
https://docs.python.org/3/library/functools.html

customtask: python reduce was moved in functools.

---

recipes-extended/seabios/seabios_1.9.%.bbappend

Somebody decided to move where they host their files
Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

recipes-extended: fix seabios URL

---

recipes-extended/seabios/seabios_1.9.%.bbappend

Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

STABLE-8: recipes-extended: fix seabios URL

---

recipes-openxt/xenclient/xenclient-dom0-tweaks/firstboot.sh

OXT-1345: firstboot: the gconf VHD is preserved on upgrade, don't try to format it

---

recipes-openxt/xenclient/xenclient-dom0-tweaks/firstboot.sh

(cherry picked from commit 58dd513d5460e8250b18b5b40cc7b8f2c1a0bcde)

STABLE-8: OXT-1345: firstboot: the gconf VHD is preserved on upgrade, don't try to format it

---

recipes-openxt/openxt/openxt-measuredlaunch/seal-system

seal-system: fix check for all-zeros PCRs

---

recipes-openxt/openxt/openxt-measuredlaunch/seal-system

(cherry picked from commit e787b872bb4a35f64225806163c3fe8568ce22a1)

STABLE-8: seal-system: fix check for all-zeros PCRs

---

recipes-security/refpolicy/refpolicy-mcs-2.%/patches/storage-Add-fcontexts-for-NVMe-disks.patch
recipes-security/refpolicy/refpolicy-mcs_2.%.bbappend

refpolicy: backport NVMe support

---

recipes-security/refpolicy/refpolicy-mcs-2.%/patches/storage-Add-fcontexts-for-NVMe-disks.patch
recipes-security/refpolicy/refpolicy-mcs_2.%.bbappend

(cherry picked from commit dae1c0d4928b63acb25317f5eda8ff2152d54f56)

STABLE-8: refpolicy: backport NVMe support

---

recipes-openxt/openxt/openxt-measuredlaunch/seal-system

seal-system: fix the PCRs order

---

recipes-openxt/openxt/openxt-measuredlaunch/seal-system

(cherry picked from commit e4fd1edc21390f199b50ab81df9bba4820c6177e)

STABLE-8: seal-system: fix the PCRs order

---

recipes-core/base-files/files/fstab.early

fstab.early: mount the securityfs for the txt module

---

recipes-extended/xen/files/libxl-allow-save-vnuma.patch
recipes-extended/xen/xen-common.inc

Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

libxl: fix  "xl save" by allowing vNUMA-enabled guests to be saved

---

recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.contrib.tcsd.patch
recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.mount.diff

refpolicy: squash a couple AVCs

---

recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.contrib.tcsd.patch
recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.mount.diff

(cherry picked from commit eb4fe5ecdbc8026e7312fec449e2a4e704d75318)

STABLE-8: refpolicy: squash a couple AVCs

---

recipes-connectivity/openssh/files/xenclient-dom0/sshd_config

OXT-1389
(cherry picked from commit 7bef4f78cfe2f12003e6957177eaf033bbc0e0fb)

STABLE-8: sshd_config: use alternative auth method that handles empty passwords correctly

---

recipes-core/images/xenclient-installer-image/grub.cfg
recipes-openxt/xenclient/xenclient-dom0-tweaks/openxt.cfg

See master PR: https://github.com/OpenXT/xenclient-oe/pull/982

STABLE-8: OXT-1377: Work around sensitive EFI firmwares

---

recipes-extended/dialog/dialog_1.2-20150225.bb

dialog: fix URL

---

recipes-extended/dialog/dialog_1.2-20150225.bb

(cherry picked from commit 4cf5c589fa810f7159c9f3564d31c319c1cf50a3)

STABLE-8: dialog: fix URL

---

recipes-graphics/xorg-lib/xkeyboard-config_1.4.bb

xkeyboard-config: update URL

---

recipes-graphics/xorg-lib/xkeyboard-config_1.4.bb

(cherry picked from commit ada429796cc9bf0cbffc64ba4215be839ab436a6)

STABLE-8: xkeyboard-config: update URL

---

recipes-extended/xen/files/xsa269-4.10.patch
recipes-extended/xen/files/xsa272.patch
recipes-extended/xen/xen-common.inc

https://xenbits.xen.org/xsa/advisory-269.html
https://xenbits.xen.org/xsa/advisory-272.html
Duplicates former PR: https://github.com/OpenXT/xenclient-oe/pull/1025

STABLE-8: OXT-1420,OXT-1422: XSA-269, XSA-272

---

recipes-kernel/linux/4.14/linux-openxt_4.14.66.bb
recipes-kernel/linux/4.14/patches/xsa270.patch

https://xenbits.xen.org/xsa/advisory-270.html
This is not upstream yet.
OXT-1421
This is on top of https://github.com/OpenXT/xenclient-oe/pull/1031.  Once that is merged, it is just a single commit.

OXT-1421: XSA-270 Linux netback driver OOB access in hash handling 

---

recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
recipes-openxt/openxt/openxt-measuredlaunch/seal-system
recipes-openxt/openxt/openxt-measuredlaunch/seal-system.conf
recipes-openxt/openxt/openxt-measuredlaunch_1.0.bb
recipes-openxt/tboot/tboot-1.9.6/0015-pcr-calc-Add-pcr-calculator-tool.patch

See master PR: https://github.com/OpenXT/xenclient-oe/pull/1051

STABLE-8: OXT-1438: Allow pcr-calc to handle event-log overrides to forward-seal successfully

---

recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg

grub.cfg: sanitize xen console options

---

recipes-kernel/linux/4.14/patches/blktap2.patch

Signed-off-by: turnerr <turnerr@ainfosec.com>

Make sure there is buffer control on high memory pages

---

recipes-extended/xen/files/libxl-blktap3-do-not-destroy-in-use-tapdevs.patch

fix the patch which failed the build

---

recipes-core/images/xenclient-installer-image.bb
recipes-kernel/linux-firmware/linux-firmware_git.bb

OXT-1525: linux-firmware: update to latest rev

---

recipes-support/console-setup/console-setup-ckbcomp-native_1.188.bb

Signed-off-by: turnerr <turnerr@ainfosec.com>

Update console-setup to 1.188 while also updating the SRC_URI

---

conf/distro/openxt-main.conf
conf/machine/upgrade-compat.conf
recipes-core/images/xenclient-upgrade-compat-image.bb

upgrades from 32-bit versions of OpenXT
OXT-1539

STABLE-9: [upgrade] Build new 32-bit compat image to support

---

recipes-core/base-passwd/base-passwd_3.%.bbappend
recipes-extended/polkit/polkit_%.bbappend

passwd: set all non-root shells to false

---

recipes-core/base-passwd/base-passwd_3.%.bbappend
recipes-extended/polkit/polkit_%.bbappend

OXT-1585
OXT-1586
(cherry picked from commit 18c1e23b3ea7ff10b6ebee062d1d124aea1b46fb)

STABLE-9: passwd: set all non-root shells to false

---

recipes-core/microcode/intel-microcode_20190312.bb
recipes-core/microcode/intel-microcode_20190514a.bb

Add the 20190312 and 20190514 microcode.

---

recipes-kernel/linux/4.19/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/4.19/linux-openxt_4.19.44.bb
recipes-kernel/linux/4.19/patches/acpi-video-delay-init.patch
recipes-kernel/linux/4.19/patches/blktap2.patch
recipes-kernel/linux/4.19/patches/bridge-carrier-follow-prio0.patch
recipes-kernel/linux/4.19/patches/extra-mt-input-devices.patch
recipes-kernel/linux/4.19/patches/pci-pt-flr.patch
recipes-kernel/linux/4.19/patches/pci-pt-move-unaligned-resources.patch
recipes-kernel/linux/4.19/patches/usbback-base.patch
recipes-kernel/linux/4.19/patches/xen-txt-add-xen-txt-eventlog-module.patch

Uprev the Linux 4.19 kernel from 4.19.32 to 4.19.44

---

recipes-core/microcode/intel-microcode_20190312.bb
recipes-core/microcode/intel-microcode_20190514a.bb

(cherry picked from commit 2fd3ac6d35d37438f4efcb879284c32b6b63bad8)
OXT-1605

[Stable-9] Add the 20190312 and 20190514 microcode.

---

recipes-kernel/linux/4.19/defconfigs/openxt-installer/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/4.19/linux-openxt_4.19.53.bb
recipes-kernel/linux/4.19/patches/extra-mt-input-devices.patch
recipes-kernel/linux/4.19/patches/pci-pt-flr.patch

OXT-1630
Signed-off-by: Nicholas Tsirakis <tsirakisn@ainfosec.com>

[linux] Upgrade from 4.19.44 to 4.19.53

---

recipes-kernel/linux/4.19/defconfigs/openxt-installer/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-dom0/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-ndvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-nilfvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-stubdomain/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-syncvm/defconfig
recipes-kernel/linux/4.19/defconfigs/xenclient-uivm/defconfig
recipes-kernel/linux/4.19/linux-openxt_4.19.53.bb
recipes-kernel/linux/4.19/patches/extra-mt-input-devices.patch
recipes-kernel/linux/4.19/patches/pci-pt-flr.patch

OXT-1630
Signed-off-by: Nicholas Tsirakis <tsirakisn@ainfosec.com>

S9: [linux] Upgrade from 4.19.44 to 4.19.53

---

recipes-extended/xen/files/libxl-disable-json-updates.patch
recipes-extended/xen/files/libxl-disable-vnc-query-when-disabled.patch
recipes-extended/xen/files/libxl-fix-flr.patch
recipes-extended/xen/files/libxl-iso-hotswap.patch
recipes-extended/xen/files/libxl-openxt-helpers.patch
recipes-extended/xen/files/libxl-xenmgr-support.patch

OXT-1623
This check was missed when upgrading from xen-4.11
Signed-off-by: Mahantesh Salimath <salimathm@ainfosec.com>

OXT-1623: libxl: add back stubdom check for helper kill

---

recipes-extended/libtirpc/libtirpc_1.1.4.bb

Signed-off-by: turnerr <turnerr@ainfosec.com>

OXT-1628: Uprev libtirpc to 1.1.4

---

classes/openxt-image.bbclass

A couple of mistakes made it through development and review process. This PR is to rectify these two mistakes.

Class refactoring cleanup

---

conf/distro/openxt-main.conf
recipes-core/images/xenclient-dom0-image.bb
recipes-openxt/stubdomains/devicemodel-stubdom_1.0.bb
recipes-openxt/stubdomains/xenclient-stubdomain-kernel_1.0.bb

This PR enables packaging of the of stub domains so they can be incorporated under IMAGE_INSTALL and then converts dom0 image recipe.

Introduce stubdom recipes

---

recipes-core/images/xenclient-ndvm-image.bb
recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
recipes-extended/xen/files/ocamlfind-static.patch
recipes-extended/xen/xen-common.inc
recipes-extended/xen/xen-ocaml-libs.bb
recipes-openxt/xenclient-toolstack/xenclient-toolstack_git.bb

Required for: https://github.com/OpenXT/meta-openxt-ocaml-platform/pull/14.

OXT-1704: ocaml: Amend cross-compilation

---

recipes-extended/xen/files/unmap-shared-info.patch

Backport: https://github.com/OpenXT/xenclient-oe/pull/1363

ZEUS: xen: refresh unmap-shared-info context

---

recipes-core/coreutils/coreutils_%.bbappend

coreutils: remove bbappend adding xattr

---

recipes-connectivity/networkmanager/files/org.openxt.nmapplet.conf

That syntax is invalid, it should be a comment.

nmapplet: Fix bus configuration file

---

recipes-support/rng-tools/rng-tools/default
recipes-support/rng-tools/rng-tools_%.bbappend

pass `-q` to rngd at start and silence recurring logs.

rngd: silence recurrent messages

---

recipes-kernel/linux/5.4/patches/usbback-base.patch

This is two fixes for usbback locking issues identified by lockdep.

usbback lockdep fixes

---

recipes-support/dnsmasq/patches/dnsmasq_dnsout_interface.patch

[dnsmasq] Update patch to adjust for CVE in upstream

---

conf/distro/openxt-main.conf
recipes-extended/newt/libnewt/security-flags.patch
recipes-extended/newt/libnewt_%.bbappend
recipes-extended/qemu-dm/qemu-dm.inc
recipes-support/anthy/anthy_9100e.bb
recipes-support/anthy/files/format-security-fixes.patch

Fixup the build and have the openxt-main distro include security_flags.inc.
Depends on:
https://github.com/OpenXT/meta-openxt-haskell-platform/pull/21 for all the haskell components.
https://gitlab.com/vglass/glass/-/merge_requests/34 for vglass
https://github.com/OpenXT/xctools/pull/71

Security Flags

---

recipes-kernel/linux/5.15/linux-openxt_5.15.61.bb

Signed-off-by: Chris Rogers <crogers122@gmail.com>

[linux] Uprev kernel to 5.15.61

---

recipes-kernel/linux/5.15/linux-openxt_5.15.69.bb

Signed-off-by: Chris Rogers <crogers122@gmail.com>

[linux] Uprev Linux kernel to 5.15.69

---

recipes-security/acms/acms.bb

Change url slightly to account for pulling from the
openxt.ainfosec.com mirror.

[acms] Update SRC_URIs for ACMs

---

recipes-kernel/linux/6.1/linux-openxt_6.1.38.bb

linux: Uprev to 6.1.38 micro
