OpenXT/xenclient-oe

- recipes-core/icedtea/icedtea6-native_1.8.11.bbappend
This replaces the odd tabs with spaces and normalizes the number of
space to 4. http://www.openembedded.org/wiki/Styleguide
Signed-off-by: Philip Tricca <flihp@twobit.us>
> icedtea6-native: Normalize indentation.

- recipes-kernel/linux/files/usbback-map-ring-valloc.patch
- recipes-kernel/linux/linux-xenclient-3.11.inc
The comment in the code sums up what the problem is but I will recap here.
The existing code was calling alloc_vm_area which update the page tables
for the init process (init_mm). If the process context is not init, the
current process will not have updated page tables. These tables would be
updated through normal #PF faults later. But, since the next call here is
a hypercall, there is not chance to update those table and the hypercall
fails when it cannot find the page through a PT lookup. Thus the error:
(XEN) mm.c:3889:d0 Could not find L1 PTE for address f8684000
Using the xenbus mapping with valloc and vfree handles this by passing
the PTEs to the hypercall.
OXT-69
Signed-off-by: Ross Philipson <ross.philipson@gmail.com>
> [usbback|dom0] Use xenbus shared ring mapper functions.

- recipes-bsp/acpid/acpid/ac_actions
Petty change to silence acpid warning (no /etc/acpi/actions/ac* matching script).
> acpid warning

- recipes-kernel/linux/files/gem-foreign-debug.patch
- recipes-kernel/linux/files/gem-foreign.patch
- recipes-kernel/linux/linux-xenclient-3.11.inc
As some debug calls went into other i915 files, split the debug code
from the original functionality.
Use DRM print methods.
> [linux-i915] Silence gem-foreign debug.

- recipes-extended/xen/xen-tools.bb
Use Makefile variables instead of environment.
Removes redundancy and makes sure that Makefile's DESTDIR variable is
set.
It seems the comment is deprecated since ioemu is built outside of the xen-tools tree, hence disabling it.
> [xen-tools] Use EXTRA_OEMAKE for DESTDIR.

- recipes-openxt/vgabios/vgabios-0.7a/vbe-extended-edid-modes.patch
- recipes-openxt/vgabios/vgabios_0.7a.bb
Adds a collection of common supported "resolution" modes for HVM guest display.
These allow for a more natural-appearing display on many monitors. See
added patch for additional information.
Signed-off-by: Kyle Temkin <temkink@ainfosec.com>
> Add additional resolutions (back) to vgabios.

- recipes-openxt/xenclient/xenclient-boot-sound/xenclient-boot-sound.initscript
update-pcm-config fixes the alsa config, which is needed to be able to access the volumes.
> [xenclient-boot-sound] fix config before adjusting the volumes

- recipes-extended/xen/files/acpi-hvmloader-pm-xt.patch
We used to use the ACPI firmware for QEMU traditional but now we want the
version that matches our new QEMU. Note gpe0_blk_len = ACPI_GPE0_BLK_LEN_V1
is left intact. This matches the new QEMU and is 1/2 as big as the traditional
GPE space. This is also why all of the GPE's in the patch are changed to fit
in 16 bits now. Finally we let the Seabios ACPI builder use the new DSDT
version by removing where we patched it to use traditional.
OXT-259
> Use ACPI guest firmware that matches upstream QEMU

- recipes-openxt/qemu-dm/files/0001-readonly-ide.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
Upstream qemu does not support readonly IDE devices
other than CDROM, because they do not exist.
This patch will mimic the behavior used in legacy-ioemu
to provide read-only IDE disk support, by erroring out
on write commands.  Typically, these disks will be unplugged
in favor of the PV couterpart.
OXT-264
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
> qemu-dm: add patch to allow readonly IDE

- recipes-openxt/qemu-dm/files/0001-generic-xenstore-extensions.patch
- recipes-openxt/qemu-dm/files/0024-Stubdom-support-for-ISO-media-changes-after-boot.patch
- recipes-openxt/qemu-dm/files/0025-Enable-changing-of-ISO-media-in-non-stubdom-device-m.patch
- recipes-openxt/qemu-dm/files/0027-nic-link-state-propagation.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
Have the emulated NICs mirror the link-status of the network back-end, exposed through XenStore.
Add xenstore_remove_watch() in addition to the existing XenStore helpers.
I had to refresh patches 0024/0025 and took the opportunity to remove trailing white-spaces and tabs that went in. Also, there was a dependency on syslog in the patch, I choose to remove it since we make syslog logging optional by a configure flag.
OXT-254
> Qemu nic link state

- recipes-openxt/qemu-dm/files/0029-stubdom-read-gsi-from-device-config-space.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
See comments in the patch and the patch header.
OXT-269
> Fix USB (PCI in general) pass-through problems w/ stubdoms.

- recipes-openxt/xenclient-repo-certs/xenclient-repo-certs_1.0.bb
The previous recipe requires the source filenames to be
"prod-cacert.pem" and "dev-cacert.pem" otherwise do_install would fail
to find what it was expecting. This patch modifies do_install to use the
basename from the configuration file for these certificates and put them
into the package in their standardized format without requiring an
intermediate standard that was also different.
Signed-off-by: Kevin Pearson <kevin.pearson.4@us.af.mil>
> Allow custom source cert filenames

- recipes-openxt/qemu-dm/files/0030-xenfv-i440fx-max-ram-below-4g.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
Add max-ram-below-4g parameter to machine option. This option is only
implemented for xenfv machine using i440fx PCI bus controller. Emulation
will use the value to set up the PCI hole base at a lower address,
making it bigger.
This parameter makes the PCI hole consistent between the Xen memory
listener and the i440fx emulation. Also, hvmloader will process that
value again after QEMU is initialized, both have to match.
The full fix for OXT-243 includes the toolstack commit to process that value before starting QEMU and the modification in dm-agent to pass it from Xenstore to QEMU command line.
> [qemu-dm] add max-ram-below-4g parameter.

- recipes-openxt/qemu-dm/qemu-dm-stubdom/qemu-ifup-stubdom
- recipes-openxt/qemu-dm/qemu-dm-stubdom_1.4.0.bb
Use the xenstore to query for a list of vifs available to the stubdom
and match with the proper eth device.
OXT-275
> Use mac address to determine proper eth <-> vif pairing.

- recipes-openxt/xenclient/xenclient-dom0-tweaks/firstboot.sh
It really needs to be only on PS_FILE, PS_DIR is too broad. It also
appears to be unnecessary for two reasons:
1) this needs to be done in time for init.root-ro, which this is not.
2) and init.root-ro looks like it replaces every boot (if it is non-zero
sized) anyways.
In fact, as a result of 2, the firstboot install of the trousers files
can probably be safely removed altogether.
OXT-272
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
> firstboot: remove chown for tss:tss on PS_DIR

- recipes-openxt/qemu-dm/files/0024-Stubdom-support-for-ISO-media-changes-after-boot.patch
- recipes-openxt/qemu-dm/files/0025-Enable-changing-of-ISO-media-in-non-stubdom-device-m.patch
- recipes-openxt/qemu-dm/files/0027-nic-link-state-propagation.patch
Use NICInfo table instead of NetClientState for watch argument.
Refresh patches applied on top.
OXT-291
> Fix segv in NIC link state propagation

- recipes-openxt/qemu-dm/files/0031-bp-rt8139-net-queue-flush-fix-00b7ade807b5ce6779ddd86ce29c5521ec5c529a.patch
- recipes-openxt/qemu-dm/files/0032-bp-hub-net-queue-flush-fix-199ee608f0d08510b5c6c37f31a7fbff211d63c4.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
These should resolve issues with Windows 7 guests losing
network connectivity (receive) when using the rtl8139 emulated
nic.
Requires two patches, one to fix the flush for rtl8139
and another to fix the flush for the qemu "hub".
OXT-294
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
> qemu: backport qemu fixes for flushing net queues

- recipes-core/icedtea/icedtea6-native_1.8.11.bbappend
Icedtea has a hardcoded check for the kernel version prefix. We very
strongly suspect our host kernels are new enough to build icedtea,
so we'll disable the check (rather than having to change a constant
for every version).
> Fix build of Icedtea on newer linux kernels.

- recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
Follow "Xen best practice"
(http://wiki.xenproject.org/wiki/Xen_Project_Best_Practices) and make
sure to give dom0 a fixed amount of memory.
Having dom0_mem=320M leaves the possibility to dom0 to balloon up to 4G.
OXT-285
> Dedicate a fixed amount of memory to dom0

- recipes-extended/iasl/iasl_20120215.bb
- recipes-extended/xen/xen-firmware.bb
- recipes-extended/xen/xen-tools.bb
- recipes-openxt/seabios/seabios_1.7.5.bb
Add the iasl recipe so we don't require it to be on the build box.
Then moodify recipes to require the iasl-native package instead of
relying on the host to have the program.
OXT-210
Signed-off-by: David Quigley <drquigley@tycho.nsa.gov>
> [iasl]: Add iasl recipe and rework xentools and seabios

- recipes-kernel/linux/files/usbback-cancel-urb-support.patch
- recipes-kernel/linux/linux-xenclient-3.11.inc
The Linux usbfront driver must support an URB dequeue callback. When
invoked it is supposed to kill the URB in question if it can and complete
it. To do this an internal command is sent to usbback where it uses the anchor
list to find the URB and kill it if it is still being processed.
OXT-38
> [pvusb] Add usbback support for URB cancelation.

- recipes-openxt/qemu-dm/files/0033-acpi-pm-feature.patch
0033-acpi-pm-feature.patch:
* Add xenstore watch on a per domain basis that can trigger
a power button SCI to the guest.
OXT-212
> Qemu support for acpi shutdown without pv drivers.

- recipes-extended/xen/files/workaround-nehalem-igd-vtd.patch
- recipes-extended/xen/xen.bb
- recipes-extended/xen/xen.inc
This should correct graphics garbling on Dell 980 machines.
> Add VT-d workaround for IGD on Nehalem (Dell 980).

- recipes-core/icedtea/icedtea6-native/icedtea-ecj-fix-currency-data.patch
- recipes-core/icedtea/icedtea6-native_1.8.11.bbappend
This is a cherry-pick of a master commit that's needed for legacy-ioemu to build.
If you think this should be done a different way, please shout.
> Remove the remaining currency expirations from the icedtea utility.

- recipes-openxt/bootage/bootage/bootage.conf-xenclient_dom0
- recipes-openxt/xenclient/vusb/files/xenclient-vusb.initscript
- recipes-openxt/xenclient/vusb/vusb-daemon_git.bb
- recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_services_ctxusb.fc.patch
- recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_services_ctxusb.if.patch
- recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_services_ctxusb.te.patch
- recipes-support/monit/monit-5.5/monitrc
This pull request changes the vusb daemon recipe to build the new daemon, located there:
https://github.com/OpenXT/vusb-daemon (see https://github.com/OpenXT/vusb-daemon/pull/1)
A build that includes this pull request (and the related one in manager.git) can be found there:
http://openxt.ainfosec.com:81/builds/master/ext-dev-269-master/
The daemon code is well documented, but you can find some additional information there:
https://github.com/jean-edouard/vusb-daemon/wiki
If you have any interest in USB in OpenXT, whether you're a user or a developer, please give this a try and write a short comment here.
Most of the vusb daemon code was written from scratch and never reviewed, I'm sure there's bugs in it. If you can read C, please have a look and comment here.
> New vusb daemon

- recipes-openxt/qemu-dm/qemu-dm-stubdom_1.4.0.bb
- recipes-openxt/qemu-dm/qemu-dm_1.4.0.bb
Add the forgotten column separator to the FILESEXTRAPATHS_prepend.
> [qemu-dm] FILESEXTRAPATHS_prepend ':'

- classes/xenclient-customtask.bbclass
This will simplify working in OE.
It may not be the best way to implement it, please chime in if you know better.
> bbclasses: get makeclean to depend on force_rebuild

- recipes-openxt/initrdscripts/initramfs-xenclient/xenclient-stubdomain/init.sh
Change kernel cmdline parsing in the dmagent case so new parameters do
not affect dmagent argument recovery.
OXT-332
See related PR in:
- manager.git
- toolstack.git
- idl.git
> Allow Stubdomain configuration of a given VM through the toolstack

- recipes-kernel/linux/linux-xenclient-3.18/usbback-base.patch
pending_reqs and pending_segments are both allocated through kzalloc().
No need to memset() those to 0, also the size given to memset is invalid
and will cause recent gcc versions to output some warnings.
> [linux-pq] Remove incorrect memsets.

- recipes-core/images/xenclient-installer-image.bb
- recipes-core/images/xenclient-ndvm-image.bb
NDVM does not support USB, so remove the ralink USB Wifi dongle modules
and firmware from it.
This most likely belongs in the installer to allow PXE installation on
platforms without ethernet.
Discussion started in: https://github.com/OpenXT/xenclient-oe/pull/154, but changes in the branch have locked the PR.
> [ralink] Move from NDVM to installer.

- recipes-core/images/xenclient-installer-image.bb
rt2870/rt357x devices are USB Wifi dongles only.
There is no Wireless support in dom0's kernel shared by the installer. There is no claim to support installation through such means and no infrastructure in OpenXT either.
Currently, rt3572 will break the build in dom0's kernel (CONFIG_WIRELESS=n -> CONFIG_WEXT_PRIV=n).
> [ralink] Remove module and firmware.

- recipes-extended/xen/xen-tools.bb
This is needed to boot standard Debian kernels as PV guests.
All the credit goes to @rossphilipson for the find :)
> xen-tools: enable xz compression support

- recipes-kernel/linux/linux-xenclient-3.18/usbback-base.patch
> [vusb] URB_SHORT_NOT_OK should only be set on IN URBs

- classes/xenclient-deb-kernel.bbclass
The version of Lintian that is in Debian Wheezy doesn't seem to be compatible with Linux 3.18.
This override seems to make it work.
> xenclient-deb-kernel.bbclass: be nice to Linux 3.18

- recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_services_xenpmd.te.patch
Changes to SELinux policy required for [xctools PR15](https://github.com/OpenXT/xctools/pull/15).
> [selinux] Allow XCPMD to talk to DBD and xenmgr

- recipes-kernel/linux/linux-xenclient-3.18/xenbus-move-otherend-watches-on-relocate.patch
- recipes-kernel/linux/linux-xenclient-dom0_3.18.19.bb
- recipes-kernel/linux/linux-xenclient-ndvm_3.18.19.bb
- recipes-kernel/linux/linux-xenclient-stubdomain_3.18.19.bb
- recipes-kernel/linux/linux-xenclient-uivm_3.18.19.bb
Fixes a kernel OOPS that disrupts a VM's kernel if it winds up with XenBus device (backend or frontend) that it can't provide a driver for.
See https://openxt.atlassian.net/browse/OXT-420.
OXT-420
> Fix kernel OOPS when changing backend for XenBus device with no driver.

- recipes-security/selinux/refpolicy-mcs/openxt_policy_modules_services_ctxusb.te.patch
WARNING: this is stable-4, not master
Without this fix, the vusb daemon can't create and write to /config/etc/USB_always.conf, losing auto-assign settings on reboot.
This may not be the correct/best way to fix it, but that's my best shot and it seems to work.
> fix config file permissions for the vusb daemon

- conf/distro/openxt-main.conf
- conf/machine/xenclient-dom0.conf
- conf/machine/xenclient-ndvm.conf
- conf/machine/xenclient-nilfvm.conf
- conf/machine/xenclient-sbuild.conf
- conf/machine/xenclient-stubdomain.conf
- conf/machine/xenclient-syncui.conf
- conf/machine/xenclient-syncvm.conf
- conf/machine/xenclient-uivm.conf
PREFERRED_VERSION variables are split between the general local.conf
file (in openxt.git) and machine specific configurations.
Regroup everything under a distro configuration (openxt-main in this
case), leaving machine specific configuration with PREFERRED_PROVIDER.
This is only a small attempt at making recipe selection a little bit easier than it is using the DISTRO configuration of Bitbake. I might have missed the canonical way of doing so.
See related commit in https://github.com/OpenXT/openxt.
> Define recipes versions in distro.

- recipes-openxt/vgabios/vgabios-0.7a/vbe-xenvesa.patch
- recipes-openxt/vgabios/vgabios_0.7a.bb
Use IO ports 0x383A-0x383D from the shadow bda region defined in QEMU to
pass graphic information to windows guest driver.
This patch was left out during the QEMU 1.4 upgrade.
> Set XenVESA IO ports for xenvesa driver.

- recipes-openxt/qemu-dm/qemu-dm-1.4/0018-vga-shadow-bda.patch
The comments need to include a reference to the registers used to store
the xenvesa support structure too.
OXT-430
> [xenvesa] Improve comments and fix incorrect length of register block.

- recipes-openxt/xenclient/drm-surfman-plugin_git.bb
Trivial change to avoid:
QA Issue: non -staticdev package contains static .a library
> drm-plugin, Fix QA issue.

- recipes-openxt/qemu-dm/qemu-dm-1.4/0035-add-acpi-wakeup.patch
- recipes-openxt/qemu-dm/qemu-dm-stubdom_1.4.0.bb
- recipes-openxt/qemu-dm/qemu-dm.inc
- recipes-openxt/qemu-dm/qemu-dm_1.4.0.bb
**Test note:** Can be merged in any order, but should be tested with: https://github.com/OpenXT/toolstack/pull/11
Prior to this patch, QEMU requires a wake signal to be communicated
from the input server via the DMbus, but:
- This is nonideal, as it requires the input server to be running, and
requires the input server to circumvent the toolstack for waking guests.
- This means that guests are not woken properly when using toolstack calls,
such as "xec-vm -n <domain-name> resume".
This commit modifies QEMU to also respond to wake requests via a XenStore node.
Ideally, this information would be communicated via a protocol like QMP; this is
to be considered a stand-in until QMP support is integrated.
NOTE:
While the added patch could be merged into acpi.patch, in this case it seems to
make …
> Allow QEMU to be notified when guests wake from S3.

- recipes-openxt/vgabios/vgabios-0.7a/vbe-edid-interface.patch
- recipes-openxt/vgabios/vgabios-0.7a/vbe-extensions.patch
Remove the EDID copy on the stack and modify the returned EDID in place
seems to avoid memory corruption. The returned EDID is now correct,
though lack of a complete explanation makes this a work-around.
See associated ticket for more details.
OXT-445
> Make 4f15 01 returns a valid EDID.

- recipes-extended/xen/files/xsa-155-paravirtualized-drivers-incautious-about-shared-memory-contents.patch
- recipes-extended/xen/files/xsa-159-XENMEM_exchange-error-handling-issues.patch
- recipes-extended/xen/files/xsa-160-libxl-leak-of-pv-kernel-and-initrd-on-error.patch
- recipes-extended/xen/files/xsa-165-information-leak-in-legacy-x86-FPU-XMM-initialization.patch
- recipes-extended/xen/files/xsa-166-ioreq-handling-possibly-susceptible-to-multiple-read-issue.patch
- recipes-extended/xen/xen.inc
- recipes-kernel/linux-libc-headers/linux-libc-headers_3.18.25.bb
- recipes-kernel/linux/3.18/linux-openxt_3.18.25.bb
- recipes-kernel/linux/3.18/patches/extra-mt-input-devices.patch
- recipes-kernel/linux/3.18/patches/pci-pt-flr.patch
- recipes-kernel/linux/3.18/patches/thorough-reset-interface-to-pciback-s-sysfs.patch
- recipes-kernel/linux/3.18/patches/usbback-base.patch
- recipes-kernel/linux/3.18/patches/xsa-155-paravirtualized-drivers-incautious-about-shared-memory-contents.patch
- recipes-kernel/linux/3.18/patches/xsa-155-qsb-023-add-RING_COPY_RESPONSE.patch
- recipes-kernel/linux/3.18/patches/xsa-155-qsb-023-xen-blkfront-make-local-copy-of-response-before-usin.patch
- recipes-kernel/linux/3.18/patches/xsa-155-qsb-023-xen-blkfront-prepare-request-locally-only-then-put-i.patch
- recipes-kernel/linux/3.18/patches/xsa-155-qsb-023-xen-netfront-add-range-check-for-Tx-response-id.patch
- recipes-kernel/linux/3.18/patches/xsa-155-qsb-023-xen-netfront-copy-response-out-of-shared-buffer-befo.patch
- recipes-kernel/linux/3.18/patches/xsa-155-qsb-023-xen-netfront-do-not-use-data-already-exposed-to-back.patch
- recipes-kernel/linux/3.18/patches/xsa-157-linux-pciback-missing-sanity-checks-leading-to-crash.patch
- recipes-kernel/linux/4.1/linux-openxt_4.1.13.bb
- recipes-kernel/linux/4.1/patches/xsa-155-paravirtualized-drivers-incautious-about-shared-memory-contents.patch
- recipes-kernel/linux/4.1/patches/xsa-157-linux-pciback-missing-sanity-checks-leading-to-crash.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/xsa-155-paravirtualized-drivers-incautious-about-shared-memory-contents.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/xsa-162-heap-buffer-overflow-vulnerability-in-pcnet-emulator.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
Upgrade Linux 3.18 kernels to 3.18.25.
Add XSA-155, XSA-157, XSA-159, XSA-160, XSA-162, XSA-165 and XSA-166 to Xen, QEMU and Linux (3.18 and 4.1) patch-queues.
> Linux 3.18.25 & latest XSAs

- recipes-kernel/linux/3.18/linux-openxt_3.18.25.bb
- recipes-kernel/linux/3.18/patches/bp-dmi-scan-uuid-fix-endianess-for-smbios.patch
- recipes-kernel/linux/4.1/linux-openxt_4.1.13.bb
- recipes-kernel/linux/4.1/patches/bp-dmi-scan-uuid-fix-endianess-for-smbios.patch
Backport ff4319d to fix UUID endianness for SMBIOS >= 2.6
For test installations, product_uuid is used as passphrase to cipher /config. This regression broke upgrade to Linux 3.18 for OpenXT installs using Linux 3.11.
> Fix dmi product_uuid endianness for SMBIOS >= 2.6

- recipes-kernel/linux/3.11/patches/usbback-base.patch
- recipes-kernel/linux/3.18/patches/usbback-base.patch
- recipes-kernel/linux/4.1/patches/usbback-base.patch
This driver currently calls alloc_page() with flags that may return
lowmem *and* highmem pages. Throughout the remaining code,
pfn_to_kaddr() is used to produce virtual addresses for those pages, but
this function only produces valid addresses for lowmem pages. Calling it
for highmem pages produces an incorrect address that frequently lies
within the vmalloc range, potentially resulting in trashing another
piece of kernel memory. Requesting only lowmem pages prevents this from
happening.
> [usbback] Prevent usbback from trashing kernel memory. [OXT-481]

- recipes-core/glibc/glibc-2.22/cve-2015-7547.patch
- recipes-core/glibc/glibc_2.22.bbappend
Source: https://sourceware.org/ml/libc-alpha/2016-02/msg00416.html
"During upstream review of the public open bug 18665 for glibc, it was
discovered that the bug could lead to a stack-based buffer overflow."
This ports git://sourceware.org/git/glibc.git:e9db92d
> Port CVE-2015-7547 patch from upstream

- classes/selinux-image.bbclass
The old test relied on ls -Z to check for unlabeled files.
However, commit 7e6b232828130514fd38091a34e29a4c3c12f105
(selinux: Fix do_install failures on libsepol/libselinux) added
a dependency on coreutils-native to ensure support for ln --relative,
and coreutils-native is built without SELinux support, so ls -Z
was always reporting "?".  It doesn't appear to be supported to
build coreutils-native with SELinux support as this creates a
dependency loop.  So just switch the test to use getfattr instead
(and we already have attr-native as a dependency).  Unfortunately
this also has some false positives due to the handling of hard links
by upstream pseudo xattr support, but at least it isn't every file.
> Fix test for unlabeled files.

- recipes-openxt/seabios/seabios-1.7.5/avoid-iPXE-rom-init-when-not-required.patch
- recipes-openxt/seabios/seabios_1.7.5.bb
Use the ROM PNP extension header to avoid loading the iPXE ROM
automatically if we have no BEV to boot from it.
> Avoid iPXE ROM init when not required

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
- recipes-security/selinux/selinux-load/selinux-load.sh
There is no reason to do it prior to the switch_root, and
evidently this was not working correctly.  At the least, it would
have required passing -r /root to setfiles for an alternate root,
and even then it did not appear to work for some reason.  Just take
it to selinux-load.sh, where we can do it after loading policy
and use restorecon instead.
OXT-463
> Move labeling of /boot/system to selinux-load.sh.

- recipes-devtools/syslinux/syslinux/no-strip.patch
- recipes-devtools/syslinux/syslinux_4.04.bb
Packaging was incomplete, so add split packages for things left-over,
move static libraries in -staticdev and append PACKAGES to avoid globing
-dev/-staticdev/etc in -misc.
> Fix syslinux build/QA warningss

- recipes-kernel/linux/4.1/defconfigs/xenclient-dom0/defconfig
- recipes-kernel/linux/4.1/patches/usbback-base.patch
- recipes-kernel/linux/4.1/patches/xenbus-move-otherend-watches-on-relocate.patch
Commits went into 3.18 but were left out of 4.1.
Same as https://github.com/OpenXT/xenclient-oe/pull/224 in stable-5.
> Stable 5 linux 4.1 missing bits

- recipes-devtools/ghc-libs/ghc-haxml_1.20.2.bb
- recipes-devtools/ghc-libs/ghc-hunit_1.2.4.2.bb
- recipes-devtools/ghc-libs/ghc-lib-common.inc
- recipes-devtools/ocaml/ocaml-camomile/ocaml-camomile-destdir.patch
- recipes-devtools/ocaml/ocaml-camomile_0.8.1.bb
- recipes-devtools/ocaml/ocaml-dbus_0.24.bb
- recipes-extended/xen/xen.bb
- recipes-openxt/qemu-dm/qemu-dm.inc
- recipes-openxt/xclibs/udbus_git.bb
- recipes-security/selinux/libsemanage_2.4.bbappend
- recipes-security/selinux/qemu-wrappers_1.0.bb
This is only a starting effort to fix packaging in many of the xenclient-oe layer packages.
It makes a lots of noise mostly, making it harder to find important things in the output. So, deal with what is built in a better way:
- Split things into different packages (e.g, -dbg, -utils, -dev),
- do not leave things behind,
- try to make sure everything is where it belongs,
- Haskell binaries are stripped, silence the warnings about it,
- Missing RDEPENDS here and there...
> QA warnings: Packaging

- recipes-kernel/linux-firmware/linux-firmware_git.bb
- recipes-openxt/acms/acms.bb
Those licenses are "Proprietary", we could make them available in the layer as well. Also there is more than one license applying to those packages.
> QA warnings: Licences

- recipes-devtools/ocaml/ocaml-cross/config.patch
- recipes-devtools/ocaml/ocaml-cross/remove-absolute-linker-path-from-lib.patch
- recipes-devtools/ocaml/ocaml-cross_git.bb
- recipes-devtools/ocaml/ocaml-dbus_0.24.bb
- recipes-openxt/blktap/blktap_git.bb
Blktap does not need to override -fPIC.
OCAML-cross should generate position-independent code.
RPATH should not store absolute path from the build environment. Someone made a patch for that (http://caml.inria.fr/mantis/view.php?id=5943) as it is apparently not default.
> QA warnings: Linker

- recipes-security/refpolicy/refpolicy-mcs_2.20140311.bbappend
Linux 3.0 introduced /sys/fs/selinux as the preferred mount point
for selinuxfs instead of /selinux, so /selinux is no longer needed.
There are no ${datadir}/selinux/*/*.bz2 files to package, and this
directory is handled by the meta-selinux refpolicy recipe anyway, so
drop it.
The EXTRA_OEMAKE flags seem be some legacy of older recipes; removing
them seems to have no effect.
> Drop legacy cruft from refpolicy recipe.

- recipes-openxt/xenclient/xenclient-dom0-tweaks/firstboot.sh
- recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
/boot/system/tpm is created via install -d from init.root-ro.
coreutils install is supposed to look up the proper security context
and assign it but there seems to be a regression for directory creation,
leaving it in the parent directory type.
Several /config files are created by firstboot.sh via shell redirection.
These will default to the type of the parent directory without an explicit
label assignment.
Add restore calls as appropriate (restore is defined as a shell
wrapper for restorecon in /etc/init.d/functions).
The alternative would be to use name-based type transitions in policy,
but explicit restorecon seems more appropriate here given that these
are being created manually by an init script and are essentially one-time
operations.
OXT-486
Signed-off-by: Stephen Smalley …
> Fix labeling of files/directories created on firstboot.

- classes/xenclient-licences.bbclass
- recipes-core/images/xenclient-sysroot-image.bb
The directory containing package metadata information has moved
from /usr into /var in the current dom0 filesystem. This change
updates the licence collection step search path.
refs OXT-460
> xenclient-licenses : Fix the path searched for control files.

- recipes-security/selinux/libselinux/libselinux-mount-procfs-before-check.patch
- recipes-security/selinux/libselinux/libselinux-only-mount-proc-if-necessary.patch
- recipes-security/selinux/libselinux_2.4.bbappend
selinux upstream commits 9df4988 and 5a8d8c4.
Otherwise, when switching /etc/selinux/config to enforcing for dom0,
the installer fails when attempting to mount selinuxfs, with:
Mount failed for selinuxfs on /sys/fs/selinux:  No such file or directory
The scenario is that the installer is booted with selinux=0, but
has the same /etc/selinux/config as dom0, and thus has SELINUX=enforcing
if we make dom0 enforcing.  The expected behavior is that kernel
parameters take precedence (override) the /etc/selinux/config setting,
so this used to work.  When the preferred selinuxfs mount point moved from
/selinux to /sys/fs/selinux (in Linux 3.0), attempting to mount selinuxfs
on a kernel with SELinux disabled (via selinux=0 or via kernel config)
started returning ENOENT rather than ENODEV because …
> libselinux: Apply two upstream fixes required for installer.

- conf/layer.conf
- files/additional-licenses/GHCL
- recipes-devtools/ghc/ghc-native_6.12.1.bb
- recipes-devtools/ghc/ghc-runtime_6.12.1.bb
Add GHC License in the layer so it is provided for relevant packages.
INSANE_SKIP installed-vs-shipped:
Currently, install puts files in staging absolute path, making this very noisy in the logs. The fix should be to avoid that, the very loud logs are reporting a side effect of the real issue.
> GHC QA warnings

- recipes-kernel/linux/4.4/patches/usbback-base.patch
Commit 7048bea53ef8ad3e22a79800dae6d2c5d5fdd36f fixed OXT-481, but
never made it into stable-5.
> [linux-4.4] Add missing commit.

- classes/xenclient-customtask.bbclass
xenclient-customtasks.bbclass introduced two tasks for xenclient
recipes:
- do_force_rebuild: Remove stamps file of any tasks not in a whitelist
Currently, that will end up doing "bitbake -c clean <target>" in the
end.
- do_makeclean: Call "oe_runmake clean", and depends on force_rebuild
making it a bit misleading...
The first really looks like "bitbake -C compile <task>"
I am not sure what the second provides, it is fine to do make clean in
devshell.
> [conf] xenclient-customtasks

- recipes-security/refpolicy/refpolicy-mcs-2.20140311/config
This change restores dom0 to SELinux enforcing by default,
as it used to be prior to the jethro merge.  Depends on the dom0
policy fixes.
> Make dom0 default to SELinux enforcing.

- recipes-security/refpolicy/refpolicy-mcs-2.20140311/xenclient-ndvm/config
This change restores the ndvm to SELinux enforcing mode by default,
as it used to be prior to the jethro merge.   Depends on the ndvm
policy fixes.
> Make the ndvm default to SELinux enforcing.

- recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
After the jethro merge, / and /boot/system get mounted as ext2 instead of ext3.
I suspect it is due to a change in busybox, that now somehow defaults to ext2.
According to the man page (http://linux.die.net/man/1/busybox), mount will:
Mount a filesystem. Filesystem autodetection requires /proc be mounted.
Since the partition are mounted by busybox in the initramfs, /proc is probably missing at that point...
The initscript can use kernel options for choosing the filesystem, so I'm adding those to the Linux command line in Grub.
Maybe at some point we'll want the initscript to be able to figure things out by itself...
> grub: mount / and /boot/system as ext3

- recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.system.udev.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20140311/policy/modules/apps/db-cmd.te
- recipes-security/refpolicy/refpolicy-mcs-2.20140311/policy/modules/services/network-daemon.te
mmap(MAP_LOCKED) can trigger spurious ipc_lock denials because
can_do_mlock() performs the capable(CAP_IPC_LOCK) check first and
then checks whether the caller's RLIMIT_MEMLOCK is non-zero; in either
case, the operation can proceed.  This was fixed by
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a5a6579db33af91f4f5134e14be758dc71c1b694
to reorder the checks.
db-cmd may run under the caller's domain or in its own domain, depending
on policy.  Thus, we need to dontaudit this permission for several domains.
Resolves these denials:
avc:  denied  { ipc_lock } for  pid=1196 comm="db-cmd" capability=14  scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tclass=capability permissive=0
avc:  denied  { ipc_lock } for …
> Do not audit db-cmd ipc_lock denial.

- recipes-security/refpolicy/refpolicy-mcs-2.20140311/patches/policy.modules.contrib.networkmanager.diff
/etc/NetworkManager within the ndvm is a tmpfs mount populated by
network-slave and managed via NetworkManager.  The top-level directory
for this mount is assigned NetworkManager_etc_t via a rootcontext= mount
option in the fstab.  Normally read-only configuration files for
NetworkManager are labeled with NetworkManager_etc_t while read-write
configuration files are labeled NetworkManager_etc_rw_t.  There is an
automatic file type transition defined so that when NetworkManager creates
files under /etc/NetworkManager, they are assigned the NetworkManager_etc_rw_t
type.  However, network-slave lacked a corresponding type transition
definition, and thus the files it created were being left in
NetworkManager_etc_t, producing denials when manually configuring
networking (shown below).
Extend …
> Fix access to /etc/NetworkManager by NetworkManager and network-slave.

- recipes-extended/iasl/iasl_20120215.bb
Right now all of acpica.org redirects to 01.org...
GitHub should be more reliable.
> iasl: switch to github for the source tarball

- recipes-openxt/trousers/trousers_0.3.2-1.bb
tcsd depends on libgcc_s.so.1 for pthread_cancel.
The absence of libgcc_s.so.1 from the installer rootfs was
causing tcsd to abort during installation, and thereby
preventing installing with measured launch enabled.
libgcc_s.so.1 was already being included in the dom0 rootfs,
which is why tpm-setup could work.
With this fix and the luksCheckKey fix applied, one can
once again install with measured launch enabled.
OXT-473
OXT-518
> Add RDEPENDS for libgcc to trousers.

- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
configure_measured_launch() was invoking cryptsetup with a custom-defined
luksCheckKey action to test the key it just added.  The patch implementing
luksCheckKey was not forward-ported during the jethro merge, so this
was always failing.  As cryptsetup has changed its internal API and
data structures, the patch no longer applies, even manually, and would
require a rewrite.  However, research discovered that luksOpen now
supports a --test-passphrase option that seems to provide equivalent
functionality.  So simply switch from luksCheckKey to luksOpen
--test-passphrase.
With this change, I can successfully run tpm-setup after install
and transition to a measured launch.  This does not fix being
able to initially install with measured launch enabled; some other
issue is still breaking that …
> Change configure_measured_launch() to use luksOpen --test-passphrase.

- recipes-openxt/xenclient/linuxfb-surfman-plugin_git.bb
- recipes-openxt/xenclient/surfman_git.bb
Patches were introduced to the layer but really belong in the surfman.git repository. See related PR https://github.com/OpenXT/surfman/pull/9
> Surfman spring cleaning

- recipes-openxt/libxcdbus/libxcdbus_git.bb
There is already a LICENSE line indicating the correct LGPLv2.1
so this extra incorrect LICENSE line should be removed.
Signed-off-by: Christopher Clark <christopher.w.clark@gmail.com>
on behalf of BAE Systems.
> OXT-516 : Remove erroneous LICENSE line from libxcdbus bb file

- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
With the current do_compile_prepend there is no order precedence for derived projects to add their own modules or make changes before compile to existing upstream policies. By adding specific tasks for these steps, derived projects can better extend the module and policy changes.
> Move the do_compile_prepend to their own tasks

- conf/distro/openxt-linux-3.18.conf
- conf/distro/openxt-main.conf
Ignore the diff, all I did is:
xenclient-oe/conf/distro$ git mv openxt-main.conf openxt-linux-3.18.conf
xenclient-oe/conf/distro$ git mv openxt-linux-4.4.conf openxt-main.conf
OXT-476
> Linux: set 4.4 as the default kernel

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.apm.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/upstream-add-binder-security-class.patch
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/upstream-contrib-networkmanager.patch
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/upstream-update-netlink-classes.patch
- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
Linux 4.4 includes additional SELinux security classes that
are not defined by the refpolicy release used in OpenXT.
Consequently, on boot, one gets the following warnings in dmesg:
SELinux:  Class netlink_iscsi_socket not defined in policy.
SELinux:  Class netlink_fib_lookup_socket not defined in policy.
SELinux:  Class netlink_connector_socket not defined in policy.
SELinux:  Class netlink_netfilter_socket not defined in policy.
SELinux:  Class netlink_generic_socket not defined in policy.
SELinux:  Class netlink_scsitransport_socket not defined in policy.
SELinux:  Class netlink_rdma_socket not defined in policy.
SELinux:  Class netlink_crypto_socket not defined in policy.
SELinux:  Class binder not defined in policy.
SELinux: the above unknown classes and permissions will be allowed …
> refpolicy: Update SELinux definitions for Linux 4.4

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/stubdom-helpers.fc
atapi_pt_helper creates `/var/lock/xen-atapi-pt-lock-<a>_<b>_<c>_<d>`,
and policy defines a type transition to assign it atapi_helper_lock_t,
but there is no file_contexts (.fc) entry for it.  Thus, a restorecon
will incorrectly reset it to var_lock_t.  Add an entry for it.
After this change, restorecon -Rv /var/lock reports no changes.
OXT-306
> Preserve label of /var/lock/xen-atapi-pt-lock* on restorecon.

- recipes-core/images/xenclient-stubdomain-initramfs-image.bb
- recipes-openxt/dm-agent/dm-agent-stubdom_git.bb
Without dmbus there is no need to split dm-agent in two flavor.
OXT-544
> Have one dm-agent for both stubdom and dom0

- recipes-core/packagegroups/packagegroup-xenclient-extra.bb
icbinn-fuse, nfs-utils and valgrind failed to build.
Removed the first two and fixed valgrind.
> Fix xenclient-extra

- recipes-core/base-files/base-files/fstab.xenclient-dom0
- recipes-core/base-files/base-files/fstab.xenclient-ndvm
- recipes-core/base-files/base-files/fstab.xenclient-syncvm
- recipes-core/base-files/base-files/fstab.xenclient-uivm
> fstab: make /var/cache big enough for opkg downloads

- recipes-extended/xen/files/xen-fix-xsave.patch
- recipes-extended/xen/xen.inc
This patch was originally posted on the Qubes mailing list for Xen 4.4, and has been backported to Xen 4.3.4.
> [xen] Pull in upstream patch to support xsave on Skylake.

- recipes-kernel/linux/4.4/patches/konrad-microcode.patch
Linux 3.18 introduced a commit disabling microcode update logic for
paravirt guest since Xen support is not upstream.
As we have konrad's patch, we can remove that test.
OXT-418
> linux-4.4 microcode-xen.c failed to init

- recipes-core/images/xenclient-installer-image.bb
- recipes-core/images/xenclient-ndvm-image.bb
- recipes-kernel/linux-firmware/linux-firmware_git.bbappend
This PR is deliberately omitting installation of these two firmwares into the dom0 filesystem due to OXT-576. This should enable validation of correct functionality of the wifi device without the firmware present in dom0. If this succeeds, all wifi firmware can then be removed from the dom0 filesystem.
> OXT-575: package and install two iwlwifi firmwares in NDVM and installer filesystems

- recipes-openxt/qemu-dm/qemu-dm-1.4/cve-2014-3615-vbe-rework-sanity-checks.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/vbe-bochs-dispi-return-correct-mem-size-with-qxl.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/vga-add-sr_vbe-register-set.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/xsa-179-banked-access-to-vga-memory-uses-inconsistent-bounds-checks.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3615
Also backport a patch introducing a new field in VGACommonState that will be used by other upstream patches to ease the backport work.
Backport the upstream fix for XSA-179 regression with windows 7 installer hanging.
OXT-572
> Backport CVE-2014-3615 and fix XSA-179 regression

- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-openxt/xenclient/xenclient-toolstack/xenstored.initscript
- recipes-openxt/xenclient/xenclient-toolstack_git.bb
xen-tools installs and registers the xenstored initscript, which in the
end calls the xenstored binary shipped with the xenclient-toolstack
package.
As we currently use the forked OCAML implementation of xenstored, have a
split package xenclient-toolstack-xenstored that will install and
register its own xenstored initscript for the OCAML forked xenstored.
Fix the xen-tools xenstored initscript to use the C xenstored shipped
with xen-tools-xenstored.
In the end change the dom0 package-group to install the
xenclient-toolstack OCAML xenstored only.
> Clean-up Xenstored packaging & deployment

- recipes-core/images/xenclient-dom0-image.bb
- recipes-core/images/xenclient-installer-image.bb
- recipes-core/images/xenclient-ndvm-image.bb
using the BAD_RECOMMENDATIONS and PACKAGE_REMOVE macros when
building the dom0 rootfs.
libcurl and wget have RRECOMMENDS which were likely pulling it in.
refs: OXT-496
> OXT-496: remove ca-certificates package from dom0

- recipes-openxt/bootage/bootage/bootage.conf-xenclient_dom0
- recipes-openxt/bootage/bootage_git.bb
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/xenpmd.fc
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/xenpmd.te
- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
Required by [xctools PR29](https://github.com/OpenXT/xctools/pull/29).
> XCPMD boot dep update [OXT-434] and selinux policy for default rules [OXT-449]

- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
No known reason for wifi firmware to be present on the dom0
filesystem so remove it.
> OXT-576: remove wifi linux-firmware-* from dom0 packagegroup

- files/additional-licenses/Intel-ACMs
- recipes-core/images/xenclient-installer-image.bb
- recipes-openxt/acms/acms.bb
Add the Intel ACM software license to the layer's additional
licenses.
Indicate "Intel-ACMs" as the license in the recipe rather than the
generic "Proprietary".
Include the most recent ACM license file in the distributed package
as required by the license.
Add some descriptive package metadata to the recipe.
> OXT-588 : fix packaging of acms software license

- recipes-extended/xen/files/acpi-pm-feature.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/0033-acpi-pm-feature.patch
The original guest battery ACPI code had used port 0x90 as the BAT2 status
register. For years this was causing harmless messages in the system log but
nothing was done about it and it was forgotten. With Windows 10, use of this
port started causing endless AMLI debugger errors to trace out from the
guest. This moves the port to someplace that is not problematic to Windows.
OXT-606
> [acpi] Move BAT2 status port to prevent AMLI errors in Windows 10

- recipes-openxt/xenclient/rpc-proxy/rpc-proxy.rules
rpc-proxy.rules still contains a set of a rules permitting obsolete and
removed functionality such as the guest switcher functionality. These
rules were also allowed for all domains, not just guests, so they were
accessible from e.g. the ndvm. We need to remove these rules.
Tested by trying to send one of these messages from the ndvm before
and after the change and confirming that it failed after the change,
with a rpc-proxy: (1->0) DENY message in /var/log/messages.
Saw no other rpc-proxy DENY messages in /var/log/messages, so does not
appear to break any functionality but admittedly did not extensively test.
OXT-639
> Remove guest rules from rpc-proxy.rules.

- recipes-connectivity/libressl/libressl.inc
- recipes-connectivity/libressl/libressl_2.3.6.bb
LibreSSL is packaged as a provider of the openssl interface as an
alternative to the openssl package.
The certificate file cert.pem is packaged independently to allow
installation of the binaries without certificates.
Refs: OXT-637
Upstream: yes, this will also be rebased for submission upstream, independently of this PR.
If it is accepted and made available from upstream, the OpenXT copy should then be removed.
> OXT-637: Package libreSSL for OpenXT

- recipes-extended/xen/files/xc-xt-v4v.patch
Fixes to integer overflow handling, input validation and
signed/unsigned types in v4v hypervisor code.
Signed-off-by: James McKenzie <voreekf@madingley.org>
> OXT-653: v4v hypervisor code fixes

- recipes-connectivity/wpa-supplicant/wpa-supplicant/2014-1-0001-Add-os_exec-helper-to-run-external-programs.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2014-1-0002-wpa_cli-Use-os_exec-for-action-script-execution.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2015-2-0001-WPS-Fix-HTTP-chunked-transfer-encoding-parser.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2015-3-0001-AP-WMM-Fix-integer-underflow-in-WMM-Action-frame-par.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2015-5-0001-NFC-Fix-payload-length-validation-in-NDEF-record-par.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2016-1-0001-WPS-Reject-a-Credential-with-invalid-passphrase.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2016-1-0002-Reject-psk-parameter-set-with-invalid-passphrase-cha.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2016-1-0003-Remove-newlines-from-wpa_supplicant-config-network-o.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant_0.7.3.bbappend
OXT-667 : wpa-supplicant : apply CVE fixes
Motivated by fixes for:
CVE-2015-8041
CVE-2015-4141
Source material obtained from: http://w1.fi/security/
2014-1 through to 2016-1
with porting as necessary to apply patches to 0.7.3
> OXT-667 : wpa-supplicant : apply CVE fixes

- recipes-kernel/intel/intel-microcode.inc
- recipes-kernel/intel/intel-microcode_20130906.bb
- recipes-kernel/intel/intel-microcode_20160714.bb
Note: the OpenXT mirror needs to be updated before this PR can be accepted.
This recipe should be replaced by a dependency on the meta-intel
layer, but unfortunately at the moment the microcode version in
the upstream layer is not from 2016. An upstream patch has been
submitted to correct that and we update the OpenXT version here in
the meantime.
refs: OXT-668
> OXT-668: intel microcode update to 20160714

- recipes-extended/xen/files/openxt-xen-xsmv4vuse.patch
- recipes-extended/xen/xen.inc
Add a XSM/Flask v4v use permission check to control
the ability to invoke any of the v4v hypercalls.
The existing v4v send permission check only controls the
ability to send via v4v, but still allows use of other v4v
hypercalls, and a subset of the v4v send code path is still
reachable prior to the send check.  The use permission check can
be used to remove the v4v hypercall interface entirely from the
attack surface of the hypervisor for domains that have no legitimate
reason to use v4v.
This change depends on a separate change to xsm-policy to allow v4v
use by authorized domains.
Also update the xsm_v4v_send hook to follow the upstream convention
of including a XSM_DEFAULT_ARG parameter and returning the result of
xsm_default_action() when XSM is disabled; this convention was introduced …
> xen/v4v: add a XSM/Flask v4v use permission check

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/openxt-sysadm-lsusb.patch
- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
Running lsusb from a newrole'd root shell fails with
the following SELinux denials:
avc:  denied  { create } for  pid=1556 comm="lsusb" scontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tcontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tclass=netlink_kobject_uevent_socket
avc:  denied  { bind } for  pid=1556 comm="lsusb" scontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tcontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tclass=netlink_kobject_uevent_socket
avc:  denied  { read } for  pid=1556 comm="lsusb" scontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tcontext=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 tclass=netlink_kobject_uevent_socket
Permit this by allowing sysadm_t to create and use netlink sockets with the
NETLINK_KOBJECT_UEVENT protocol.  The alternative would be to introduce
a separate domain for …
> Allow running lsusb from a newrole'd root shell.

- recipes-connectivity/wpa-supplicant/wpa-supplicant/2014-1-0001-Add-os_exec-helper-to-run-external-programs.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2014-1-0002-wpa_cli-Use-os_exec-for-action-script-execution.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2015-2-0001-WPS-Fix-HTTP-chunked-transfer-encoding-parser.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2015-3-0001-AP-WMM-Fix-integer-underflow-in-WMM-Action-frame-par.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2015-5-0001-NFC-Fix-payload-length-validation-in-NDEF-record-par.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2016-1-0001-WPS-Reject-a-Credential-with-invalid-passphrase.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2016-1-0002-Reject-psk-parameter-set-with-invalid-passphrase-cha.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant/2016-1-0003-Remove-newlines-from-wpa_supplicant-config-network-o.patch
- recipes-connectivity/wpa-supplicant/wpa-supplicant_0.7.3.bbappend
Motivated by fixes for:
CVE-2015-8041
CVE-2015-4141
Source material obtained from: http://w1.fi/security/
2014-1 through to 2016-1
with porting as necessary to apply patches to 0.7.3
(cherry picked from commit d538c2e383e1868980dcef0cfdafbb8e76c2fe7c)
> Stable-6: OXT-667 : wpa-supplicant : apply CVE fixes

- recipes-kernel/intel/intel-microcode.inc
- recipes-kernel/intel/intel-microcode_20130906.bb
- recipes-kernel/intel/intel-microcode_20160714.bb
Note: the OpenXT mirror needs to be updated before this PR can be accepted.
This recipe should be replaced by a dependency on the meta-intel
layer, but unfortunately at the moment the microcode version in
the upstream layer is not from 2016. An upstream patch has been
submitted to correct that and we update the OpenXT version here in
the meantime.
refs: OXT-668
cherry-picked from commit: b6a172f18d2b28d4632b1b9b671607ed8fd44e40
> Stable-6: OXT-668: intel microcode update to 20160714

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/openxt-dbus-deny-send-unconfined.patch
- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
Upstream refpolicy commit 6bef7a14757124c56fadc08c255e9dd6c29a15f9
added a reverse rule for the existing rule that allowed dbus unconfined
domains to send to any dbus client in order to allow those dbus clients to
answer.  However, this exposes dbus unconfined domains (i.e. those domains
which are allowed to send to any dbus destination) to any regular
dbus client.  Remove this rule.  Explicit rules on individual domain
pairs can be added if needed.
In the specific case of OpenXT, this opened up D-BUS send from staff_t
or any other dbus client domain to xenmgr (xend_t), since the OpenXT policy
patches make xend_t an unconfined domain.  The user-visible effect was
that xec and xec-vm worked from a staff_t shell rather than requiring
a newrole.  This change restores the prior behavior of …
> refpolicy: Do not allow sending to dbus unconfined domains by default.

- recipes-extended/xen/files/xc-xt-v4v.patch
Fixes edge case error handling where page type is incorrect.
This fix is required to protect Xen's page reference counting from manipulation.
> OXT-688 : xen v4v: fix missing put_page in v4v_find_ring_mfns

- recipes-extended/xen/files/xc-xt-v4v.patch
Fixes edge case error handling where page type is incorrect.
> Stable 6: OXT-688 : xen v4v: fix missing put_page in v4v_find_ring_mfns

- recipes-kernel/linux/4.4/linux-openxt_4.4.16.bb
- recipes-kernel/linux/4.4/patches/cve-2016-0758-KEYS-Fix-ASN.1-indefinite-length-object-parsing.patch
- recipes-kernel/linux/4.4/patches/cve-2016-3135-netfilter-x_tables-check-for-size-overflow.patch
- recipes-kernel/linux/4.4/patches/cve-2016-3672-x86-mm-32-Enable-full-randomization-on-i386-and-X86_.patch
- recipes-kernel/linux/4.4/patches/cve-2016-3951-cdc_ncm-do-not-call-usbnet_link_change-from-cdc_ncm_.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4482-usbfs-fix-potential-infoleak-in-devio.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4568-media-videobuf2-v4l2-Verify-planes-array-in-buffer-d.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4569-ALSA-timer-Fix-leak-in-SNDRV_TIMER_IOCTL_PARAMS.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4578-1-ALSA-timer-Fix-leak-in-events-via-snd_timer_user_cca.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4578-2-ALSA-timer-Fix-leak-in-events-via-snd_timer_user_tin.patch
- recipes-kernel/linux/4.4/patches/cve-2016-5244-rds-fix-an-infoleak-in-rds_inc_info_copy.patch
- recipes-kernel/linux/4.4/patches/extra-mt-input-devices.patch
Address CVEs reported in 2016, but not upstream yet:
- CVE-2016-0758
- CVE-2016-3135
- CVE-2016-3672
- CVE-2016-3951
- CVE-2016-4482
- CVE-2016-4568
- CVE-2016-4569
- CVE-2016-4578
- CVE-2016-5244
OXT-697
> OXT-697: Backport missing CVEs for Linux kernel

- recipes-kernel/linux/4.4/linux-openxt_4.4.16.bb
- recipes-kernel/linux/4.4/patches/cve-2016-0758-KEYS-Fix-ASN.1-indefinite-length-object-parsing.patch
- recipes-kernel/linux/4.4/patches/cve-2016-3135-netfilter-x_tables-check-for-size-overflow.patch
- recipes-kernel/linux/4.4/patches/cve-2016-3672-x86-mm-32-Enable-full-randomization-on-i386-and-X86_.patch
- recipes-kernel/linux/4.4/patches/cve-2016-3951-cdc_ncm-do-not-call-usbnet_link_change-from-cdc_ncm_.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4482-usbfs-fix-potential-infoleak-in-devio.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4568-media-videobuf2-v4l2-Verify-planes-array-in-buffer-d.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4569-ALSA-timer-Fix-leak-in-SNDRV_TIMER_IOCTL_PARAMS.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4578-1-ALSA-timer-Fix-leak-in-events-via-snd_timer_user_cca.patch
- recipes-kernel/linux/4.4/patches/cve-2016-4578-2-ALSA-timer-Fix-leak-in-events-via-snd_timer_user_tin.patch
- recipes-kernel/linux/4.4/patches/cve-2016-5244-rds-fix-an-infoleak-in-rds_inc_info_copy.patch
- recipes-kernel/linux/4.4/patches/extra-mt-input-devices.patch
Address CVEs reported in 2016, but not upstream yet:
- CVE-2016-0758
- CVE-2016-3135
- CVE-2016-3672
- CVE-2016-3951
- CVE-2016-4482
- CVE-2016-4568
- CVE-2016-4569
- CVE-2016-4578
- CVE-2016-5244
OXT-697
(cherry picked from commit fd976eca603395c914dcf879dbc6b491106191bb)
> Stable-6: OXT-697: Backport missing CVEs for Linux kernel

- recipes-devtools/ocaml/ocaml-cross/finaliser-on-weak-array-gives-dangling-pointers.patch
- recipes-devtools/ocaml/ocaml-cross_git.bb
This backport seems to fix random dbd crashes that have been observed on machines with very fast disks (NVMe).
> ocaml: backport crash fix

- recipes-extended/xen/files/xc-xt-v4v.patch
Fix the code that replaces the MFNs of the existing ring.
Needs to hold the necessary L2 write lock to invoke
v4v_ring_remove_mfns.
Essential to prevent guests being able to apply excess decrements to the
page reference counts via concurrent accesses.
(cherry picked from commit add3711da445761425bce8e2a7d33a3e86e30536)
> Stable 6: OXT-689 : v4v: fix the locking on reregistering a ring

- recipes-extended/xen/files/xc-xt-v4v.patch
Fix the code that replaces the MFNs of the existing ring.
Needs to hold the necessary L2 write lock to invoke v4v_ring_remove_mfns.
Essential to prevent guests being able to apply excess decrements to the page reference counts via concurrent accesses.
The affected code after the change is pasted below for easier review since this is a change to a patch file.
```
write_lock (&d->v4v->lock);
ring_info = v4v_ring_find_info (d, &ring.id);
if (!ring_info)
{
ring_info = v4v_xmalloc (struct v4v_ring_info);
if (!ring_info)
{
ret = -ENOMEM;
break;
}
need_to_insert++;
spin_lock_init (&ring_info->lock);
INIT_HLIST_HEAD (&ring_info->pending);
ring_info->mfns = NULL;
} else {
/* Ring info already existed. If mfn list was already …
```
> OXT-689 : v4v: fix the locking on reregistering a ring

- recipes-openxt/xenclient/xenclient-input-daemon/input-daemon.initscript
start-stop-daemon will not remove the PID file, the initscript then might fail to restart the daemon.
OXT-680
The rest is just cosmetic.
> OXT-680: Input-server PIDfile handling in initscript

- recipes-kernel/linux/4.4/linux-openxt_4.4.16.bb
- recipes-kernel/linux/4.4/patches/cve-2016-5696-tcp-make-challenge-acks-less-predictable.patch
OXT-713
(cherry picked from commit 006993464afcd12efc0242e6a5494b4cb262a624)
> Stable-6: OXT-713: Backport cve-2016-5696

- recipes-security/selinux/refpolicy-mcs/openxt-ota-fixes.patch
- recipes-security/selinux/refpolicy-mcs_2.20130424.bbappend
Allow dmsetup and mount to statfs sysfs and proc filesystems.
Allow updatemgr to statfs ext4 filesystems.
Allow updatemgr to read /config/repo-cert.conf.
The last one should be allowed already but several /config files
are mislabeled in 5.x installs.  We aren't likely to fix that
now so we might as well just allow it here for OTA purposes.
> STABLE-5: refpolicy: fix OTA-related denials

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.te
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/xc-installer.fc
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/xc-installer.if
Allow updatemgr to trigger module auto-load if needed.
Allow updatemgr to manage the /storage/update/upgrade-data directory;
this was supposed to already be allowed but the wrong type was used in
the xc-installer.if and xc-installer.fc files.
Allow updatemgr to convey environment variables, signal
masks, and resource limits to the installer across a domain transition.
OXT-734
> STABLE-6: refpolicy: fix OTA-related denials

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.te
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/xc-installer.fc
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/xc-installer.if
Allow updatemgr to trigger module auto-load if needed.
Allow updatemgr to manage the /storage/update/upgrade-data directory;
this was supposed to already be allowed but the wrong type was used in
the xc-installer.if and xc-installer.fc files.
Allow updatemgr to convey environment variables, signal
masks, and resource limits to the installer across a domain transition.
OXT-734
> refpolicy: fix OTA-related denials

- recipes-extended/xen/files/xsa-185-x86-Disallow-L3-recursive-pagetable-for-32-bit-PV-guests.patch
- recipes-extended/xen/files/xsa-187-x86-hvm-overflow-of-sh_ctxt-seg_reg.patch
- recipes-extended/xen/xen.inc
XSA-183 does not affect Xen 4.3.4 (https://xenbits.xen.org/xsa/advisory-183.html)
XSA-184 is not in the scope of OpenXT (https://xenbits.xen.org/xsa/advisory-184.html).
XSA-186 does not affect Xen 4.3.4 (https://xenbits.xen.org/xsa/advisory-186.html)
OXT-742
> STABLE-6: Xen XSA-185 and 187.

- recipes-extended/xen/files/xsa-183-x86-missing-smap-whitelisting-in-32-bit-exception-event-delivery.patch
- recipes-extended/xen/files/xsa-185-x86-Disallow-L3-recursive-pagetable-for-32-bit-PV-guests.patch
- recipes-extended/xen/files/xsa-187-x86-hvm-overflow-of-sh_ctxt-seg_reg.patch
- recipes-extended/xen/xen.inc
XSA-184 is not in the scope of OpenXT (https://xenbits.xen.org/xsa/advisory-184.html).
XSA-186 does not affect Xen 4.6.1 (https://xenbits.xen.org/xsa/advisory-186.html)
OXT-742
> XSA 183, 185 and 187

- recipes-extended/xen/files/xenconsoled-syslog.patch
- Removed renable_core_dumps()
- Added Jed's fix from OXT-608 back in.
- Sanity checked the rebase.
OXT-587
> [xen-tools] Fixup the xenconsoled syslog patch post-4.6.1 merge.

- recipes-extended/xen/files/hvmloader-legacy-seabios-optionroms.patch
The force pop issue cannot be resolved cleanly and the reason
why is in the comments.
OXT-746
> [xen] Comment SEABIOS patch, remove dead VGA target.

- recipes-extended/xen/xen-blktap.bb
> Fix missing RDEPENDS that broke snapshot functionality.

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
xenconsoled attempts to increase its fd limit, triggering the following
SELinux denial:
avc:  denied  { sys_resource } for  pid=919 comm="xenconsoled" capability=24  scontext=system_u:system_r:xenconsoled_t:s0 tcontext=system_u:system_r:xenconsoled_t:s0 tclass=capability permissive=0
and the following log message from xenconsoled:
xenconsoled: Unable to increase fd limit from {1024, 4096} to {132008, 132008}: (Operation not permitted) - May run out with lots of domains
Allow this capability for xenconsoled.
OXT-784
> refpolicy: allow xenconsoled to increase fd limit

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/dbd.te
restorecon -Rnv /config reports one mislabeled file after a fresh
install:
restorecon reset /config/xenclient.conf context system_u:object_r:db_backup_t:s0->system_u:object_r:xc_config_t:s0
/config/xenclient.conf is created by upgrade-db, which simply does a:
cp /etc/xenclient.conf /config/xenclient.conf
However, the domain in which upgrade-db runs (db_upgrade_t)
has a file transition rule to label directories and files it
creates under /config with db_backup_t.  This rule is intended
for the /config/backups directory and its contents, but is also
applied when /config/xenclient.conf is created by upgrade-db.
Modify the rule to only apply to directory creation, since
once /config/backups is created in the right type, all files
created within it will also default to that type.  This leaves …
> refpolicy: fix default label of /config/xenclient.conf

- recipes-extended/xen/files/acpi-pm-feature.patch
I also reverted a couple of other miscellaneous changes that were really not
needed. The presumably came from upstream. It is better to keep ssdt_pm.asl the
way it has been tested and working for years. Since this stuff got completely
removed the latest Xen it doesn't really matter.
OXT-793
Signed-off-by: Ross Philipson philipsonr@ainfosec.com
> Fix the battery op region PRT4 to use correct port 0x84

- recipes-core/images/xenclient-initramfs-image.bb
Correcting the race condition if attempting to do a highly parallel
build.
Signed-off-by: Daniel P. Smith dpsmith@apertussolutions.com
OXT-764
> initramfs-image: fix race condition

- conf/distro/openxt-main.conf
- conf/machine/xenclient-common.conf
Selecting the kernel provider should be done in the distro config.
OXT-817
> openxt-oe: move kernel provider to distro config

- recipes-openxt/xenclient/hs-vhd_git.bb
This makes the hs-vhd recipe amenable to people that want to use the
enable the BB_GENERATE_MIRROR_TARBALLS variable to generate offline
download mirrors.
Singed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>
OXT-816
> hs-vhd: make recipe support offline mirroring

- recipes-openxt/bats-testsuite/bats-testsuite_git.bb
For now will allow bats testsuite to autorev, always pulling the latest tests
from the repository.
OXT-788
> bats: set autorev for the test suite

- recipes-kernel/linux-libc-headers/linux-libc-headers_4.4.27.bb
- recipes-kernel/linux/4.4/linux-openxt_4.4.27.bb
Use KERNELORG_MIRROR variable instead of static path.
Remove defunct and unmaintained linux versions.
Use MAJOR.MINOR linux-libc-headers tarball to make micro updates easier.
> STABLE-6: Linux recipes cleanup and mirror change

- recipes-openxt/xenclient/xenclient-dom0-tweaks.inc
Scripts #!/bin/bash require bash installed.
Silence QA warning.
> dom0-tweaks RDEPENDS on bash

- recipes-openxt/xenclient/surfman_git.bb
Surfman does not use the idl stubs, silence a warning.
> Remove idldir conf from surfman EXTRA_OECONF.

- recipes-kernel/linux/4.4/linux-openxt_4.4.27.bb
This is what OE does, so where we fetch linux-libc-headers already.
It makes it easier to change the mirror from local.conf if necessary.
> Use KERNELORG_MIRROR source.

- recipes-extended/xen/files/xsa-191-x86-null-segments-not-always-treated-as-unusable.patch
- recipes-extended/xen/files/xsa-192-x86-task-switch-to-vm86-mode-mis-handled.patch
- recipes-extended/xen/files/xsa-193-x86-segment-base-write-emulation-lacking-canonical-address-checks.patch
- recipes-extended/xen/files/xsa-195-x86-64-bit-bit-test-instruction-emulation-broken.patch
- recipes-extended/xen/xen.inc
- recipes-openxt/qemu-dm/qemu-dm-1.4/xsa-197-qemu-incautious-about-shared-ring-processing.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
XSA-194: Xen 4.4 is not affected.
XSA-196: Xen 4.4 is not affected.
XSA-198: OpenXT does not use pygrub.
OXT-843
> STABLE-6: XSAs, november 2016

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/switcher.patch
"XenInput:direct event handler"
"XenInput:send led keycode 0x0"
... are very noisy otherwise.
OXT-857
> Turn off switcher debug logging.

- recipes-openxt/qemu-dm/qemu-dm-1.4/0008-switcher.patch
"XenInput:direct event handler"
"XenInput:send led keycode 0x0"
... are very noisy otherwise.
OXT-857
(cherry picked from commit 75e19618263b8dda340398f990fe662dd05f6716)
> STABLE-6: Turn off switcher debug logging.

- recipes-extended/xen/files/blktap2-vhd-icbinn-support.patch
The snapshot and scan functions needed to use vhd_realpath to use icbinn when necessary. Without this commit the synchronizer will never create the snapshot disk after downloading the base vhd.
See OXT-785
To test this, run vhd-util for a dom0 snapshot from the synchronizer with the correct LIBVHD_ICBINN_VHD_SERVER and LIBVHD_ICBINN_KEY_SERVER set. Before this change, you will receive an error code ENOENT. After this change the vhd-util snapshot function should recognize the existence of the icbinn server set and execute the function using icbinn.
> Update the snapshot and scan functions to use the vhd realpath

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/surfman.te
surfman presents an attack surface that is exposed to stubdoms (via dmbus/v4v) and
to uivm (via dbus/rpc-proxy/v4v).  Audit and harden the SELinux policy for surfman
to limit the impact of a vulnerability in it.  In particular, surfman appears to
hold a number of dangerous permissions that would allow it to subvert dom0 kernel
integrity.
The following changes are made by this patch:
1. Remove init_domain() call.  This is not needed when using init_daemon_domain().
2. Remove domain_mmap_low() call.  This call was allowing surfman
to map low memory addresses, making it easier to exploit kernel NULL
pointer dereferences, and does not seem to be needed, based on testing.
3. Remove dev_rw_mtrr() call. This call was allowing surfman
to read and write /proc/mtrr or /dev/cpu/mtrr and thereby …
> refpolicy: Harden SELinux policy for surfman

- recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
OXT-855
(cherry picked from commit f4f28b72b0f4a7b559c4aea81a08a17890e9108a)
Conflicts:
recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
> STABLE-6: Bump dom0 memory from 320M to 420M

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/readonly-ide.patch
Without this fix you can't have readonly ide disks with the QEmu 2.6.2 uprev
> Fix the readonly-ide patch to write out the config option to the make file

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.qemu.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/blktap.te
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/stubdom-helpers.te
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/system/xc-files.if
Addresses the following denials:
avc:  denied  { use } for  pid=1126 comm="tap-ctl" path="/dev/console" dev="devtmpfs" ino=9226 scontext=system_u:system_r:tapctl_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=fd permissive=1
avc:  denied  { use } for  pid=1320 comm="tapdisk2" path="/dev/console" dev="devtmpfs" ino=9226 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=fd permissive=1
avc:  denied  { dac_override } for  pid=12517 comm="tapdisk2" capability=1  scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tclass=capability permissive=1
avc:  denied  { read write } for  pid=12517 comm="tapdisk2" name="xc-tools.iso" dev="dm-7" ino=17666 …
> refpolicy: Address denials triggered by libxl

- recipes-openxt/qemu-dm/qemu-dm.inc
> qemu-dm: RDEPENDS on relevant libraries.

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
use modprobe instead of insmods, TPM modules should be reported in
modules.dep, and depmod should have been run at initramfs image
creation.
The tpm_tis module will create the dev node.
tpm_bios no longer exist in recent kernels.
OXT-899
> STABLE-6: OXT-899: Silence TPM warnings.

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
use modprobe instead of insmods, TPM modules should be reported in
modules.dep, and depmod should have been run at initramfs image
creation.
The tpm_tis module will create the dev node.
OXT-899
> OXT-899: Silence TPM warnings.

- recipes-core/images/xenclient-dom0-image.bb
- recipes-core/images/xenclient-installer-image.bb
- recipes-kernel/linux-firmware/linux-firmware_git.bbappend
https://01.org/linuxgraphics/intel-linux-graphics-firmwares
New generations of Intel Graphics for Linux requires Firmware components
to be integreated in the kernel-mode driver.
(cherry picked from commit afe31372d1c880a2a0727f16eaa89747c71b070f)
> STABLE-6: OXT-897: Add SKL & BXT i915 firmware.

- recipes-core/images/xenclient-dom0-image.bb
- recipes-core/images/xenclient-installer-image.bb
- recipes-kernel/linux-firmware/linux-firmware_git.bbappend
https://01.org/linuxgraphics/intel-linux-graphics-firmwares
New generations of Intel Graphics for Linux requires Firmware components
to be integreated in the kernel-mode driver.
> OXT-897: Add SKL & BXT i915 firmware.

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.booleans.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.kernel.devices.diff
Adjust the policy for accesses qtdbd require.
OXT-787
> refpolicy: adjust for qtdbd

- recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
It is no longer necessary to use the FIXME postional holder.
OXT-920
> dom0-tweaks: remove FIXME from command lines

- recipes-extended/xen/files/libxl-add-cores-per-socket-support.patch
- recipes-extended/xen/xen.inc
New config option for libxl "cores_per_socket", during domain
creation, xc_domain_set_cores_per_socket is called to compact
multiple vcpus onto a socket. This is for OS's such as Win 7
that limit the total number of sockets available to the OS.
OXT-435
> [libxl] Add cores per socket support

- recipes-extended/xen/files/libxl-support-hvm-readonly-disks.patch
- recipes-extended/xen/xen.inc
linux-based stubdoms. There is an unnecessary restriction in xl
on enforcing rw for vhds.  As long as the filesystem in the guest
is ok with being mounted ro, there's no reason not to support it.
OXT-435
> [libxl] Support read-only vhds on domains with

- recipes-extended/xen/files/libxl-do-not-destroy-in-use-tapdevs.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
This commit fixes two issues. First, we remove the call to
clean the backend xenstore path in initiate_device_remove. When
the devices are actually called for removal, the xs path no longer
exists, so tapdisk destruction fails since it needs the tapdisk-params
xs entry.  Second, the tapdisk_is_shared really should only apply to
cdroms.  A domain and its stubdomain have the same value for
tapdisk-params; therefore, the function will think the vhd is shared and
the tap device will not be cleaned up.
OXT-435
> [libxl] Fix tapdisk cleanup

- recipes-devtools/dmidecode/dmidecode_3.0.bb
Original recipe has a type in LICENSE field (s|files://|file://).
Anyway, might as well use the upstream recipe. Since it is an upgrade
and there is not .inc, it requires a duplicate unfortunately.
OXT-580
> OXT-580: dmidecode: Use upstream recipe and upgrade to 3.0.

- recipes-core/util-linux/util-linux_2.26.2.bbappend
- recipes-openxt/xenclient/xenclient-preload-hs-libs_1.0.bb
No need to split the package if it is deployed anyway in dom0.
> OXT-580: ionice: Use util-linux recipe upstream.

- recipes-extended/xen/files/xenstat-disable-tmem-use.patch
about a variable declared but not used.
> OXT-980: fix xenstat-disable-tmem-use patch to avoid compile warning

- recipes-extended/xen/files/libxl-domain-state.patch
- recipes-extended/xen/files/libxl-misc-fixes.patch
Several xenstore entries were being left behind when a domain
is shutdown.  This commit cleans up the vifs in the ndvm xenstore
and the state nodes.
OXT-965
> [libxl] Clean up xenstore entries

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
There is no need to setup TPM if it is not used.
OXT-972
> OXT-972: initramfs: Setup TPM for measurement only.

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/blktap.te
This rule blocks service vms, such as the ndvm, from rebooting.
The blktapX node is unable to be removed, and thus the domain
remains in a 'creating' state indefinitely.
OXT-954
> [refpolicy] Allow tapctl to unlink xen_device_t

- recipes-extended/xen/files/libxl-domain-state.patch
After shutdown, immediately removing the state node caused a race
with listeners using xs_watch, the watch would never fire, sending
a state update notify. The xs_rm isn't really necessary here since
xenmgr can just cleanup the state node when/if the domain is deleted.
OXT-1003
> [libxl] Don't rm state node, causes xs race

- recipes-extended/xen/files/libxl-domain-state.patch
In testing, it seems much of the platform is dependent on seeing
a "shutdown" state update sent across dbus. This commit makes
sure we send that update before changing to the rebooted state.
OXT-1006
OXT-1005
OXT-990  
> [libxl] Send shutdown signal before rebooted.

- recipes-extended/xen/files/oxenstored.conf
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
Update OCaml Xenstored config file log settings.
Grant SELinux permissions required by the daemon.
> OXT-1026 : Configure Xenstored logging

- recipes-openxt/openxt/openxt-keymanagement/key-functions
The call into recovery_unlock in certain upgrade use cases from the
old xc scheme may have the target rootfs mounted on an alternative
location. Allow the passing of the alternative mount point as the
third argument.
OXT-955
> key-functions: make rsa key ref's relative

- recipes-openxt/initrdscripts/initramfs-xenclient/xenclient-stubdomain/init.sh
Silence warning and errors in the stub-domain output while using tools and binaries available in the stub-domain current initramfs.
Also change debug output to be configurable through "debug" kernel cmdline argument.
> OXT-1050: Attend errors in stub-domain init script

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/atapi-pass-through.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/xenstore-based-ISO-media-change-detection-for-both-s.patch
This fixes CD writing to what it is in stable-6 currently. Some things fail
like formatting the CD or dragging files/burning. Other things work like
right clicking an ISO and burning it to a CD. A separate ticket will be
opened to track those failures but this fixes the RO problem and the crash.
OXT-931
> Allow writable CDs and fix guest crash on write.

- recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
The grub_parse function in ml-functions is susceptible to having embedded shell
command being executed. The functon was refactored to hopefully eliminate this
attack vector.
OXT-1046
> opext-measurelaunch: refactor grub_parse

- recipes-extended/xen/files/acpi-pm-feature.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/acpi-pm-feature.patch
These two changes fix up the ACPI power button support in Xen hvmloader's ASL and QEMU's emulation.  Shutdown is more consistent with these changes.
Note, Windows guests must have "When I press the power button" set to "Shut down" to actually trigger a shutdown.  This is not always the case on install.  Specifically, Windows 10 can leave the option unset when installed and not respond to the button.
OXT-1025
> ACPI Fixes

- recipes-connectivity/network-manager-applet/network-manager-applet/always-use-psk-hash.patch
- recipes-connectivity/network-manager-applet/network-manager-applet/disable-show-password.patch
- recipes-connectivity/network-manager-applet/network-manager-applet_0.9.2.0.bb
- recipes-connectivity/network-manager-applet/network-manager-applet_0.9.2.0.bbappend
This patches network-manager-applet so that PSK passwords are only ever dealt with in their hashed form. A separate commit also disables the "show password" checkboxes.
> OXT-923: Do not store WPA PSK keys in plaintext in the dom-store.

- recipes-extended/xen/files/acpi-pm-feature.patch
- recipes-openxt/qemu-dm/qemu-dm-1.4/0033-acpi-pm-feature.patch
These two changes fix up the ACPI power button support in Xen hvmloader's ASL and QEMU's emulation. Shutdown is more consistent with these changes.
Note, Windows guests must have "When I press the power button" set to "Shut down" to actually trigger a shutdown. This is not always the case on install. Specifically, Windows 10 can leave the option unset when installed and not respond to the button.
OXT-1025
> STABLE-6: ACPI Fixes

- recipes-openxt/openxt/openxt-keymanagement/key-functions
Under legacy key management different LUKS slots where used for key storage.
Since we are not remapping LUKS slots when upgrading from a system using the
legacy slots, make the new key managent attempt a general unlock if the unlock
using the expected slot fails.
OXT-1054
> keymanagement: handle non-ml upgrade from legacy

- conf/distro/openxt-main.conf
- recipes-core/images/xenclient-dom0-image.bb
- recipes-core/images/xenclient-ndvm-image.bb
- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-extended/xen/xen-libxl.bb
- recipes-extended/xen/xen.bb
- recipes-openxt/xenclient/uid_git.bb
- recipes-openxt/xenclient/xenclient-toolstack_git.bb
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
This PR for OXT-1056 builds upon the related PR #604 for OXT-1067 (to unfork the OCaml libraries), so  includes those commits. This PR is fine to go in and the other just be retired.
There's a minor interaction between the OE standard behaviour for update-rc.d and update-alternatives that becomes evident when packaging alternative versions of the same init script, so there's a workaround for that in this PR, in the xenclient-dom0-image.bb section. OE also needed more convincing than would be expected to only install a single xenstored package, so that's enforced in the same file.
The results are correct: C daemon installed and working; OCaml daemon packaged but not installed.
> OXT-1056: Package both C and OCaml xenstored. Default to C.

- recipes-extended/logrotate/logrotate/act-as-mv-when-rotate.patch
- recipes-extended/logrotate/logrotate/disable-check-different-filesystems.patch
- recipes-extended/logrotate/logrotate/update-the-manual.patch
- recipes-extended/logrotate/logrotate_3.9.1.bb
From: Choong YinThong
Date: Sun, 9 Apr 2017 16:33:18 -0700
Subject: [PATCH] logrotate: replace fedorahosted.org SRC_URI with github.com
source
fedorahosted.org was retired on March 1st, 2017. This is to
update the SRC_URI to point to github.com.
Update the ${PN} to ${BPN} in order to pass the autobuilder
mulitlib enable configuration.
[YOCTO #11226]
OXT-1081
> OXT-1081: logrotate: replace fedorahosted.org SRC_URI with github.com

- recipes-openxt/libv4v/libv4v_git.bb
Some dynamic libraries will link against the static libv4v*.a. By
default, libtool will generate PIC dynamic libraries and non-PIC static
libraries.
libvhd.so (through libicbinn) links against libv4v.a, and the SELinux
does not allow execmod. In the end, tapdisk will fail to create
service-vm tapdisk from vhds with avc:
avc:  denied  { execmod } for  pid=1071 comm="tapdisk2" path="/usr/lib/libvhd.so.1.0.0" dev="dm-3" ino=6354 scontext=system_u:system_r:tapdisk_t:s0-s0:c0.c1023 tcontext=system_u:object_r:lib_t:s0 tclass=file permissive=0
OXT-978
> OXT-978: libv4v: Produce PIC static libraries.

- recipes-extended/xen/xen-libxl.bb
Add CONFIG_TESTS=n to avoid building tests when building xen tools.
> OXT-1047: xen-libxl: Do not build tests.

- recipes-extended/xen/files/libxl-vwif-support.patch
shutdown. Just check and make sure tmp != NULL before calling
strstr.
OXT-1086
> [libxl] Fix segfault caused by strstr on domain

- recipes-extended/xen/files/libxl-vwif-support.patch
shutdown. Just check and make sure tmp != NULL before calling
strstr.
OXT-1086
> STABLE-7: [libxl] Fix segfault caused by strstr on domain

- recipes-extended/xen/files/libxl-xenmgr-support.patch
Move the jump label for the domain reboot case to also include
the config parse code, since xenmgr just writes a new config
to the same filename.  This fixes the bug where config value
changes such as changing the memory amount aren't taking effect
on reboot
OXT-1090
> [xl] On reboot, have xl reparse the config

- recipes-extended/xen/files/libxl-iso-hotswap.patch
- recipes-extended/xen/xen-common.inc
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/set-blockdev-ro.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
while guest is on. Make sure we set readonly flags for blockdev
in qemu when set to 'preserved'. Attempting to open xvdc fails
because open flags have writable set.
OXT-1068
>   Support swapping isos in virtual cd drive

- recipes-extended/xen/files/libxl-iso-hotswap.patch
- recipes-extended/xen/xen-common.inc
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/set-blockdev-ro.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
while guest is on. Make sure we set readonly flags for blockdev
in qemu when set to 'preserved'. Attempting to open xvdc fails
because open flags have writable set.
OXT-1068
>   STABLE-7: Support swapping isos in virtual cd drive

- recipes-extended/xen/files/libxl-xenmgr-support.patch
Move the jump label for the domain reboot case to also include
the config parse code, since xenmgr just writes a new config
to the same filename.  This fixes the bug where config value
changes such as changing the memory amount aren't taking effect
on reboot
OXT-1090
> STABLE-7: [xl] On reboot, have xl reparse the config

- recipes-extended/xen/xen-common.inc
- recipes-openxt/libv4v/libv4v_git.bb
- recipes-openxt/xenclient/v4v-module-headers_git.bb
- recipes-openxt/xenclient/v4v-module_git.bb
Remove the MACHINE-specific dependencies affecting the Xen recipes so that they no longer have to be recompiled per MACHINE.
PRs for: xenclient-oe, openxt and meta-openxt-ocaml-platform.
> OXT-1016: Only build the Xen recipes once per build

- recipes-extended/xen/xen-common.inc
- recipes-openxt/libv4v/libv4v_git.bb
- recipes-openxt/xenclient/v4v-module-headers_git.bb
- recipes-openxt/xenclient/v4v-module_git.bb
Remove the MACHINE-specific dependencies affecting the Xen recipes so that they no longer have to be recompiled per MACHINE.
PRs for: xenclient-oe, openxt and meta-openxt-ocaml-platform.
Signed-off-by: Christopher Clark christopher.clark6@baesystems.com
> STABLE-7 : Only build the Xen recipes once per build

- recipes-extended/xen/files/libxl-xenmgr-support.patch
This option uses xc_shutdown_domain to turn off the guest. Used
when no pv drivers and acpi interface in qemu is not listening.
OXT-1091
> [libxl] Add hypercall shutdown option.

- recipes-extended/xen/files/libxl-xenmgr-support.patch
This option uses xc_shutdown_domain to turn off the guest. Used
when no pv drivers and acpi interface in qemu is not listening.
OXT-1091
> STABLE-7: [libxl] Add hypercall shutdown option.

- recipes-openxt/trousers/files/trousers-tcsd-conf.patch
Dom0 does not have ipv6 support and the SELinux policy does not give
tcsd the permission to try and load the module, which it will try to do.
OXT-1084
> OXT-1084: tcsd: Disable ipv6

- recipes-openxt/trousers/files/trousers-tcsd-conf.patch
Dom0 does not have ipv6 support and the SELinux policy does not give
tcsd the permission to try and load the module, which it will try to do.
OXT-1084
> STABLE-7: OXT-1084: tcsd: Disable ipv6

- recipes-extended/xen/files/xsm-for-vtd.patch
- recipes-extended/xen/xen-common.inc
Enable policy to express control over device access:
* Allow only when an IOMMU is active, or not.
* Option to require an IOMMU capable of interrupt remapping.
> STABLE-7: OXT-826 : XSM: Add distinct device use permissions with and without IOMMU

- recipes-extended/xen/files/xsm-for-vtd.patch
- recipes-extended/xen/xen-common.inc
This is a revised implementation in response to the feedback from @stephensmalley and @dgdegraaf  on PR #619 . (Also mentioning @dpsmith here to trigger mail notification.) This version has the requested three distinct use_* bits:
* resource__use_iommu
* resource__use_iommu_nointremap
* resource__use_noiommu
==
Enable policy to express control over device access:
* Allow only when an IOMMU is active, or not.
* Option to require an IOMMU capable of interrupt remapping.
> OXT-826  [ alternative ] : XSM: Add distinct device use permissions with and without IOMMU

- recipes-extended/xen/files/gcc6-compilation.patch
- recipes-extended/xen/files/iommu-make-page-table-deallocation-preemptible.patch
- recipes-extended/xen/files/iommu-make-page-table-population-preemptible.patch
- recipes-extended/xen/files/xen-arm-fully-implement-multicall-interface.patch
- recipes-extended/xen/files/xsa-207-memory-leak-when-destroying-guest-without-PT-devices.patch
- recipes-extended/xen/files/xsa-212-x86-broken-check-in-memory_exchange.patch
- recipes-extended/xen/files/xsa-213-x86-64bit-PV-guest-breakout-via-pagetable-use-after-mode-change.patch
- recipes-extended/xen/files/xsa-214-grant-transfer-allows-pv-guest-to-elevate-privileges.patch
- recipes-extended/xen/files/xsa-215-possible-memory-corruption-via-failsafe-callback.patch
- recipes-extended/xen/xen.inc
Since Xen 4.3.4 is EOL, also add required commits to keep the XSA
patches sane.
> STABLE-6: OXT-1094: xen: Backport XSA-{207,212,213,214,215}

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
This is in response to observed avcs when libxl releases a watch.
C xenstored has pipe handling code which includes managing a response
to SIGPIPE. Allow that signal to be triggered by the xenstored process.
> OXT-1095: SELinux policy: allow xenstored to signal itself

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
Upstream refpolicy has already removed these permissions from xenstored.
> OXT-1104: SELinux policy: remove storage permissions from xenstored

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
This is in response to observed avcs when libxl releases a watch.
C xenstored has pipe handling code which includes managing response
to SIGPIPE. Allow that signal to be triggered by the xenstored process.
> STABLE-7 : OXT-1095: SELinux policy: allow xenstored to signal itself

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
Upstream refpolicy has already removed these permissions from xenstored.
> STABLE-7 : OXT-1104: SELinux policy: remove storage permissions from xenstored

- recipes-core/base-files/base-files/fstab.xenclient-dom0
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.kernel.files.diff
Label /var/cores and the files inside it.
> SELinux: add coredump support

- recipes-extended/xen/files/xenstored.initscript
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
> xenstored: enable core dumps to help diagnose crashes

- recipes-core/base-files/base-files/fstab.xenclient-dom0
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.kernel.files.diff
Label /var/cores and the files inside it.
> STABLE-7: SELinux: add coredump support

- recipes-extended/xen/files/xenstored.initscript
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.contrib.xen.diff
(cherry picked from commit 14104e514a259af1d356d831ad242f5d8a007676)
> STABLE-7: xenstored: enable core dumps to help diagnose crashes

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/block-remove-unused-block-format-support.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/net-Remove-unused-network-options.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
This minimizes the set of QEMU emulated devices.
1) configure --disables many options
2) deselects many devices in the device configuration
3) patches out some block format and network functionality.
Size shrank from ~8.1MB to 6.3MB
> OXT 782 QEMU minimization

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/block-remove-unused-block-format-support.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/net-Remove-unused-network-options.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
This minimizes the set of QEMU emulated devices.
1. configure --disables many options
2. deselects many devices in the device configuration
3. patches out some block format and network functionality.
Size shrank from ~8.1MB to 6.3MB
> STABLE-7: OXT-782: QEMU minimization

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-8669-char-serial-check-divider-value-against-baud-base.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-8909-audio-intel-hda-check-stream-entry-count-during-tran.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-8910-net-rtl8139-limit-processing-of-ring-descriptors.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-9923-char-Fix-Possible-use-after-free.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-5525-audio-ac97-add-exit-function.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-5579-serial-fix-memory-leak-in-serial-exit.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-8284-tcg-i386-Check-the-size-of-instruction-being-transla.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-8309-audio-release-capture-buffers.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-8379-input-limit-kbd-queue-depth.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
CVE fixes for the minimized QEMU configuration.
OXT-776
This is intended to apply on top of my other PR #641 oxt-782-qemu-mini-hda.  As it is, this includes both sets of commits together.
> OXT-776: QEMU CVEs

- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-8669-char-serial-check-divider-value-against-baud-base.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-8909-audio-intel-hda-check-stream-entry-count-during-tran.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-8910-net-rtl8139-limit-processing-of-ring-descriptors.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2016-9923-char-Fix-Possible-use-after-free.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-5525-audio-ac97-add-exit-function.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-5579-serial-fix-memory-leak-in-serial-exit.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-8284-tcg-i386-Check-the-size-of-instruction-being-transla.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-8309-audio-release-capture-buffers.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/CVE-2017-8379-input-limit-kbd-queue-depth.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
CVE fixes for the minimized QEMU configuration.
This is the STABLE-7 version of PR #651
OXT-776
> STABLE-7: OXT-776: QEMU CVEs

- recipes-extended/xen/files/libxl-atapi-pt.patch
> libxl: atapi-pt: use incremental device numbers instead of 0

- recipes-extended/xen/files/libxl-atapi-pt.patch
OXT-1102
(cherry picked from commit 27d8a52e891c250e96818f7181006e0d96e6038b)
> STABLE-7: libxl: atapi-pt: use incremental device numbers instead of 0

- recipes-extended/xen/files/xsa-155-xen-0001-xen-Add-RING_COPY_REQUEST.patch
- recipes-extended/xen/files/xsa-155-xen-0002-blktap2-Use-RING_COPY_REQUEST.patch
- recipes-extended/xen/xen-common.inc
http://xenbits.xen.org/xsa/advisory-155.html
While the rest of the XSA is upstream or patched in the kernel
(patches from QSB-23), the blktap part is missing in 4.6.5 upstream and
the OpenXT patch-queue.
> OXT-1125: blktap: Backport XSA-155

- recipes-openxt/xenclient/dbd_git.bb
This removes the xenclient-toolstack depend that is no longer needed and
adds xen-ocaml-libs.
OXT-1133
> dbd: fix depends line

- recipes-openxt/xenclient/dbd_git.bb
This removes the xenclient-toolstack depend that is no longer needed and
adds xen-ocaml-libs.
OXT-1133
> [STABLE-7] dbd: fix depends line

- recipes-extended/xen/files/xsa-155-xen-0001-xen-Add-RING_COPY_REQUEST.patch
- recipes-extended/xen/files/xsa-155-xen-0002-blktap2-Use-RING_COPY_REQUEST.patch
- recipes-extended/xen/xen-common.inc
http://xenbits.xen.org/xsa/advisory-155.html
While the rest of the XSA is upstream or patched in the kernel
(patches from QSB-23), the blktap part is missing in 4.6.5 upstream and
the OpenXT patch-queue.
> STABLE-7: OXT-1125: blktap: Backport XSA-155

- recipes-core/images/xenclient-dom0-image.bb
- recipes-core/images/xenclient-installer-image.bb
- recipes-core/images/xenclient-installer-part2-image.bb
- recipes-kernel/linux/4.9/defconfigs/xenclient-dom0/defconfig
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/lvmetad-add-rules.patch
- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
- recipes-support/lvm2/lvm2/yocto-initscripts.patch
- recipes-support/lvm2/lvm2_%.bbappend
- Add initscripts compatible with the dom0 fs (and busybox binaries in general) for lvm2 ```lvmetad```, ```dmeventd``` and ```dmpolld```.
- Run lvmetad at std runlevel in dom0 and the installer to silence lvm2 utils warnings.
- Add dm-mirror to be able to ```pvmove``` during installation.
> OXT-1107: Add lvmetad to dom0 & installer

- recipes-connectivity/openssh/files/sshd_config
- recipes-connectivity/openssh/files/sshd_config_v4v
- recipes-extended/xen/files/xl.conf
- recipes-extended/xen/xen-libxl.bb
- ```xen-dom0-init```, run at startup, will log a warning if xl.conf is not present (xl binary seems to as well), so ship a default one.
- ```sshd``` configuration currently used contains deprecated options.
> Silence warnings during installation.

- recipes-connectivity/openssh/files/sshd_config
- recipes-connectivity/openssh/files/sshd_config_v4v
- recipes-extended/xen/files/xl.conf
- recipes-extended/xen/xen-libxl.bb
- ```xen-dom0-init```, run at startup, will log a warning if xl.conf is not present (xl binary seems to as well), so ship a default one.
- ```sshd``` configuration currently used contains deprecated options.
> STABLE-7: Silence warnings during installation.

- recipes-core/images/xenclient-dom0-image.bb
- recipes-core/images/xenclient-installer-image.bb
- recipes-core/images/xenclient-installer-part2-image.bb
- recipes-kernel/linux/4.9/defconfigs/xenclient-dom0/defconfig
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/lvmetad-add-rules.patch
- recipes-security/refpolicy/refpolicy-mcs_2.20141203.bbappend
- recipes-support/lvm2/lvm2/yocto-initscripts.patch
- recipes-support/lvm2/lvm2_%.bbappend
- Add initscripts compatible with the dom0 fs (and busybox binaries in general) for lvm2 lvmetad, dmeventd and dmpolld.
- Run lvmetad at std runlevel in dom0 and the installer to silence lvm2 utils warnings.
- Add dm-mirror to be able to pvmove during installation.
> STABLE-7: OXT-1107: Add lvmetad to dom0 & installer

- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Fix backwards logic for tpm_is_owned call from installer.
OXT-1116
> [tpm2.0] Set the correct flag if detected tpm_own

- recipes-extended/xen/files/xsa217.patch
- recipes-extended/xen/files/xsa218-4.6/0001-IOMMU-handle-IOMMU-mapping-and-unmapping-failures.patch
- recipes-extended/xen/files/xsa218-4.6/0002-gnttab-fix-unmap-pin-accounting-race.patch
- recipes-extended/xen/files/xsa218-4.6/0003-gnttab-Avoid-potential-double-put-of-maptrack-entry.patch
- recipes-extended/xen/files/xsa218-4.6/0004-gnttab-correct-maptrack-table-accesses.patch
- recipes-extended/xen/files/xsa219-4.6.patch
- recipes-extended/xen/files/xsa220-4.6.patch
- recipes-extended/xen/files/xsa221.patch
- recipes-extended/xen/files/xsa222-1-4.6.patch
- recipes-extended/xen/files/xsa222-2-4.6.patch
- recipes-extended/xen/files/xsa224-4.6/0001-gnttab-Fix-handling-of-dev_bus_addr-during-unmap.patch
- recipes-extended/xen/files/xsa224-4.6/0002-gnttab-never-create-host-mapping-unless-asked-to.patch
- recipes-extended/xen/files/xsa224-4.6/0003-gnttab-correct-logic-to-get-page-references-during-m.patch
- recipes-extended/xen/files/xsa224-4.6/0004-gnttab-__gnttab_unmap_common_complete-is-all-or-noth.patch
- recipes-extended/xen/xen-common.inc
- recipes-kernel/linux/4.9/linux-openxt_4.9.27.bb
- recipes-kernel/linux/4.9/patches/xsa216-linux-4.11.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/xsa216-qemuu-4.7.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
XSAs were released 2017-06-20, see https://xenbits.xen.org/xsa.
XSA-223 & XSA-225 are ARM specific, and were not ported in OpenXT
patch-queue for that reason.
> OXT-1152: xsa: 216,217,218,219,220,221,222,224

- recipes-extended/xen/files/libxl-domain-state.patch
- recipes-extended/xen/files/libxl-fix-reboot.patch
OpenXT's libxl-domain-state.patch and libxl-fix-reboot.patch both
contained incorrectly sized arrays on the stack.
The arrays are used for manipulating xenstore strings and were overrun
by string operations. Testing with Xen 4.8 showed junk state in xenstore
and broken guest VM reboot function, revealing these preexisting
defects.
This commit also corrects edge case control flow in libxl-fix-reboot logic.
> [OXT-1154] Fix buffer overflows in libxl patches

- recipes-support/lvm2/lvm2_%.bbappend
do_install() was creating a spurious /etc/init.d/init.d directory.
> lvm2: Amend initscript install.

- recipes-extended/xen/files/xsa217.patch
- recipes-extended/xen/files/xsa218-4.6/0001-IOMMU-handle-IOMMU-mapping-and-unmapping-failures.patch
- recipes-extended/xen/files/xsa218-4.6/0002-gnttab-fix-unmap-pin-accounting-race.patch
- recipes-extended/xen/files/xsa218-4.6/0003-gnttab-Avoid-potential-double-put-of-maptrack-entry.patch
- recipes-extended/xen/files/xsa218-4.6/0004-gnttab-correct-maptrack-table-accesses.patch
- recipes-extended/xen/files/xsa219-4.6.patch
- recipes-extended/xen/files/xsa220-4.6.patch
- recipes-extended/xen/files/xsa221.patch
- recipes-extended/xen/files/xsa222-1-4.6.patch
- recipes-extended/xen/files/xsa222-2-4.6.patch
- recipes-extended/xen/files/xsa224-4.6/0001-gnttab-Fix-handling-of-dev_bus_addr-during-unmap.patch
- recipes-extended/xen/files/xsa224-4.6/0002-gnttab-never-create-host-mapping-unless-asked-to.patch
- recipes-extended/xen/files/xsa224-4.6/0003-gnttab-correct-logic-to-get-page-references-during-m.patch
- recipes-extended/xen/files/xsa224-4.6/0004-gnttab-__gnttab_unmap_common_complete-is-all-or-noth.patch
- recipes-extended/xen/xen-common.inc
- recipes-kernel/linux/4.9/linux-openxt_4.9.27.bb
- recipes-kernel/linux/4.9/patches/xsa216-linux-4.11.patch
- recipes-openxt/qemu-dm/qemu-dm-2.6.2/xsa216-qemuu-4.7.patch
- recipes-openxt/qemu-dm/qemu-dm.inc
XSAs were released 2017-06-20, see https://xenbits.xen.org/xsa.
XSA-223 & XSA-225 are ARM specific, and were not ported in OpenXT
patch-queue for that reason.
> STABLE-7: OXT-1152: xsa: 216,217,218,219,220,221,222,224

- recipes-support/lvm2/lvm2_%.bbappend
do_install() was creating a spurious /etc/init.d/init.d directory.
Original PR: https://github.com/OpenXT/xenclient-oe/pull/686
> STABLE-7: lvm2: Amend initscript install.

- recipes-extended/xen/files/libxl-domain-state.patch
- recipes-extended/xen/files/libxl-fix-reboot.patch
OpenXT's libxl-domain-state.patch and libxl-fix-reboot.patch both
contained incorrectly sized arrays on the stack.
The arrays are used for manipulating xenstore strings and were overrun
by string operations. Testing with Xen 4.8 showed junk state in xenstore
and broken guest VM reboot function, revealing these preexisting
defects.
This commit also corrects edge case control flow in libxl-fix-reboot logic.
> STABLE 7 : [OXT-1154] Fix buffer overflows in libxl patches

- recipes-core/images/xenclient-initramfs-image.bb
- recipes-core/images/xenclient-initramfs-image/initramfs-lvm.conf
- recipes-support/lvm2/lvm2/lvm.conf
- recipes-support/lvm2/lvm2_%.bbappend
- commit https://github.com/OpenXT/xenclient-oe/commit/a9f50f4b39ada135f65f6cb4b2e3f2b1583d22cb failed to have the expected initscript installed.
- Avoid using lvmetad during early-boot (initramfs).
- Add wipe_signatures_when_zeroing_new_lvs = 1 to lvm.conf to wipe the detected signatures on created lvs when zeroing (default).
> OXT-1159 & OXT-1160: Attend lvm errors and warnings.

- recipes-extended/xen/xen-libxl.bb
The dummy configuration file is not installed.
Amend that to silence:
Failed to read config file: /etc/xen/xl.conf: No such file or directory
> OXT-1164: xen-libxl: Install xl.conf.

- recipes-extended/xen/xen-libxl.bb
The dummy configuration file is not installed.
Amend that to silence:
Failed to read config file: /etc/xen/xl.conf: No such file or directory
Origin: https://github.com/OpenXT/xenclient-oe/pull/702
> STABLE-7: OXT-1164: xen-libxl: Install xl.conf.

- recipes-extended/xen/files/libxl-fixup-cmdline-ops.patch
When a domain crashes and for some reason its resources can't
be released, xl lists it as (null). This is similar to xenvm
and the deadbeef uuids. Since they still have a domid, xenmgr
gets hung up on them, preventing that guest from booting again
until a host reset.
This patch will ignore the dead domain when xenmgr asks for a
domid, providing better fault tolerance and allow the platform
to continue to be usable.
OXT-1176
> [libxl] Ignore dead domains in uuid_to_domid

- recipes-extended/xen/files/libxl-fixup-cmdline-ops.patch
When a domain crashes and for some reason its resources can't
be released, xl lists it as (null). This is similar to xenvm
and the deadbeef uuids. Since they still have a domid, xenmgr
gets hung up on them, preventing that guest from booting again
until a host reset.
This patch will ignore the dead domain when xenmgr asks for a
domid, providing better fault tolerance and allow the platform
to continue to be usable.
OXT-1176
> STABLE-7: [libxl] Ignore dead domains in uuid_to_domid

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.te
Authorize updatemgr to read certificates and configuration required for
openssl.
> STABLE-6: OXT-1161: updatemgr: SELinux perms to read ssl certs files.

- recipes-openxt/tboot/tboot-1.9.5/tboot-export-of-tpm-event-log.patch
TBoot handles a copy of the E820 until post_launch() completes and
passes control to the next module (launch_kernel()). export_evtlog() has
to be called before replace_e820_map(), which writes the final e820 in
the MBI structures.
> OXT-1182: tboot: Write-back the e820 after reserving evtlog.

- recipes-openxt/tboot/tboot-1.9.5/tboot-export-of-tpm-event-log.patch
TBoot handles a copy of the E820 until post_launch() completes and
passes control to the next module (launch_kernel()). export_evtlog() has
to be called before replace_e820_map(), which writes the final e820 in
the MBI structures.
(cherry picked from commit 50ddf29bb17ae2191216c7bd56eb7ec25796f4b2)
> STABLE-7: OXT-1182: tboot: Write-back the e820 after reserving evtlog.

- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Fix backwards logic for tpm_is_owned call from installer.
OXT-1116
> STABLE-7: [tpm2.0] Set the correct flag if detected tpm_own

- recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
This splits up the launch failure recovery dialogs for the types of failures
that can be differentiated.
OXT-1135
> init-ro: differentiate between launch failures

- recipes-openxt/openxt/openxt-measuredlaunch/recovery-method
- recipes-openxt/openxt/openxt-measuredlaunch_1.0.bb
- recipes-openxt/xenclient/xenclient-pcrdiff/pcr-data
- recipes-openxt/xenclient/xenclient-pcrdiff/pcr-state
This fixes the existing pcrdiff utils to provide reports on PCR changes and adds a utility to report the recovery key scheme that is in use on the device.
OXT-1062
> Update measured launch status checks

- recipes-extended/xen/files/libxl-crypto-key-dir.patch
Fixes toolstack memory corruption when parsing VM configuration data and during disk attach.
* Don't omit the string termination character in length calculations, especially when allocating a buffer to be immediately overwritten.
* Don't ignore the string handling functions already provided.
* Make the existing code that performs a deep struct copy also duplicate the new string that was added to the struct.
* Prefer the length-constrained string functions. eg. strncmp rather than strcmp.
* Respect the formatting conventions of the code being patched.
* Add notes relevant for upstreaming to the patch.
> OXT-1189: fix libxl memory corruption from string handling in disk crypto dir patch

- recipes-core/glibc/glibc_2.22.bbappend
- recipes-core/glibc/patches/CVE-2017-1000366.patch
Backport upstream patch:
f6110a8fee CVE-2017-1000366: Ignore LD_LIBRARY_PATH for AT_SECURE=1 programs [BZ #21624]
> OXT-1191: glibc: CVE-2017-1000366

- recipes-core/glibc/glibc_2.22.bbappend
- recipes-core/glibc/patches/CVE-2017-1000366.patch
Amongst other things:
4d3d3a1690c2 x86/xen: allow userspace access during hypercalls
21f79ae43fd2 xen-netfront: Rework the fix for Rx stall during OOM and network stress
CVE-2017-1000370 & CVE-2017-1000371
63c2f8f8c41b binfmt_elf: use ELF_ET_DYN_BASE only for PIE
> STABLE-7: OXT-1191: glibc: CVE-2017-1000366

- recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
This splits up the launch failure recovery dialogs for the types of failures
that can be differentiated.
OXT-1135
(cherry-pick of 6e101b4)
> STABLE-7: init-ro: differentiate between launch failures

- recipes-openxt/openxt/openxt-measuredlaunch/recovery-method
- recipes-openxt/openxt/openxt-measuredlaunch_1.0.bb
- recipes-openxt/xenclient/xenclient-pcrdiff/pcr-data
- recipes-openxt/xenclient/xenclient-pcrdiff/pcr-state
This fixes the existing pcrdiff utils to provide reports on PCR changes and adds a utility to report the recovery key scheme that is in use on the device.
OXT-1062
(cherry-pick of a7ae51d..d0ff016)
Signed-off-by: Daniel P. Smith dpsmith@apertussolutions.com
> STABLE-7: Update measured launch status checks

- recipes-extended/xen/files/libxl-crypto-key-dir.patch
Fixes toolstack memory corruption when parsing VM configuration data
and during disk attach.
* Don't omit the string termination character in length calculations.
* Don't ignore the string handling functions already provided.
* Make the existing code that performs a deep struct copy also
duplicate the new string that was added to the struct.
* Adhere to the formatting conventions of the code being patched.
* Add notes relevant for upstreaming to the patch.
> STABLE-7: OXT-1189: fix libxl memory corruption in disk crypto dir patch

- recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
This PR provides TPM2 support for re-using an owned TPM2.  When a TPM2 is already owned, we take care to verify the Owner, Endorsement, and Lockout passwords.  Later, if the needed key object handles or NVRAM indices do not match expectations, new ones are defined using the TPM password.
OXT-1130
> OXT-1130: Reuse owned TPM2

- recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Stable-7 version.
This PR provides TPM2 support for re-using an owned TPM2. When a TPM2 is already owned, we take care to verify the Owner, Endorsement, and Lockout passwords. Later, if the needed key object handles or NVRAM indices do not match expectations, new ones are defined using the TPM password.
OXT-1130
> STABLE-7: OXT-1130: Reuse owned TPM2

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.system.mount.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/updatemgr-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/xc-installer-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.if
- Allow mount to stat tmpfs,
- don't audit lvcreate search in updatemgr storage,
- allow mount to getattr on filesystem devices.
> OXT-1199: SELinux AVCs during OTA upgrade.

- recipes-openxt/xenclient/xenclient-installer_git.bb
Scripts using /bin/ash rely on busybox to provide it.
Silence the following QA warnings:
WARNING: QA Issue: /install/part1/stages/Iscsi-confirm-repo_xenclient-installer contained in package xenclient-installer requires /bin/ash, but no providers found in its RDEPENDS [file-rdeps]
WARNING: QA Issue: /stages/TPM-BadSrk_xenclient-installer-part2 contained in package xenclient-installer-part2 requires /bin/ash, but no providers found in its RDEPENDS [file-rdeps]
Arrange the recipe to be more in compliance with:
https://www.openembedded.org/wiki/Styleguide
> layer: Add busybox to RDEPENDS (/bin/ash provider)

- recipes-openxt/xenclient/xenclient-tpm-scripts/hashstart-detect.sh
Remove pointless disruption during interactive installation.
Depends on: https://github.com/OpenXT/installer/pull/56
> installer: Remove tpm2.0 quirk prompt to user

- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/policy.modules.system.mount.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/updatemgr-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/patches/xc-installer-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.20141203/policy/modules/services/updatemgr.if
- Allow mount to stat tmpfs,
- don't audit lvcreate search in updatemgr storage,
- allow mount to getattr on filesystem devices.
> STABLE-7: OXT-1199: SELinux AVCs during OTA upgrade

- recipes-openxt/xenclient/xenclient-tpm-scripts/hashstart-detect.sh
Remove pointless disruption during interactive installation.
Depends on: https://github.com/OpenXT/installer/pull/57
> STABLE-7: OXT-1194: installer: Remove tpm2.0 quirk prompt to user

- recipes-extended/xen/files/libxl-domain-state.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
The most recent version of libxl-xenmgr-support.patch included hunks that
revised code introduced in libxl-domain-state.patch. This commit corrects that
by updating libxl-domain-state.patch with the intended final code and removing
the amend hunks from libxl-xenmgr-support.patch.
No code change to the end result of applying the patch queue,
just tidier patches.
> xen: remove patch-patching in libxl-xenmgr-support and libxl-domain-state

- recipes-extended/xen/files/libxl-iso-hotswap.patch
> libxl-iso-hotswap: "physical-device" is hex, not dec

- recipes-extended/xen/files/libxl-iso-hotswap.patch
> STABLE-7: libxl-iso-hotswap: "physical-device" is hex, not dec

- recipes-core/base-passwd/base-passwd_3.%.bbappend
> base-passwd: use /bin/false instead of /bin/sh for system users

- recipes-extended/xen/files/xsa226-4.9/0003-gnttab-fix-don-t-use-possibly-unbounded-tail-calls.patch
- recipes-extended/xen/xen-common.inc
https://xenbits.xen.org/xsa/advisory-226.html requires a fix that has
been backported in the stable branches upstream[1].
[1] https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=9bf14bbf990843bfec16a5d69d36cf46c7593d88
> OXT-1216: xen: backport XSA-226 fix from upstream.

- recipes-extended/xen/files/0003-gnttab-fix-don-t-use-possibly-unbounded-tail-calls.patch
- recipes-extended/xen/xen-common.inc
https://xenbits.xen.org/xsa/advisory-226.html requires a fix that has
been backported in the stable branches upstream[1].
[1] https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=b4660b4d4a35edac715c003c84326de2b0fa4f47
> STABLE-7: OXT-1216: xen: backport XSA-226 fix from upstream.

- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Some BIOSes allow the TPM2 to be "on" but disabled.  In that case we need
to verify actual usability of the TPM2 to proceed with installation.  By returning inactive, the installer will allow the user to downgrade to a non-measured launch installation.
This needs testing on a machine that allows for an "on-but-disabled" TPM2.
OXT-1212
> OXT-1212: Fix TPM2 active status check

- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Some BIOSes allow the TPM2 to be "on" but disabled. In that case we need
to verify actual usability of the TPM2 to proceed with installation. By returning inactive, the installer will allow the user to downgrade to a non-measured launch installation.
This needs testing on a machine that allows for an "on-but-disabled" TPM2.
OXT-1212
> STABLE-7: OXT-1212: Fix TPM2 active status check

- recipes-extended/xen/files/xsa237-4.9/0001-x86-dont-allow-MSI-pIRQ-mapping-on-unowned-device.patch
- recipes-extended/xen/files/xsa237-4.9/0002-x86-enforce-proper-privilege-when-mapping-pIRQ-s.patch
- recipes-extended/xen/files/xsa237-4.9/0003-x86-MSI-disallow-redundant-enabling.patch
- recipes-extended/xen/files/xsa237-4.9/0004-x86-IRQ-conditionally-preserve-irq-pirq-mapping-on-error.patch
- recipes-extended/xen/files/xsa237-4.9/0004-x86-IRQ-conditionally-preserve-irq-pirq-mapping-on-error.patch.1
- recipes-extended/xen/files/xsa237-4.9/0005-x86-FLASK-fix-unmap-domain-IRQ-XSM-hook.patch
- recipes-extended/xen/files/xsa238.patch
- recipes-extended/xen/files/xsa239.patch
- recipes-extended/xen/files/xsa240-4.9/0001-x86-limit-linear-page-table-use-to-a-single-level.patch
- recipes-extended/xen/files/xsa240-4.9/0002-x86-mm-Disable-PV-linear-pagetables-by-default.patch
- recipes-extended/xen/files/xsa241-4.9.patch
- recipes-extended/xen/files/xsa242-4.9.patch
- recipes-extended/xen/files/xsa243.patch
- recipes-extended/xen/files/xsa244.patch
- recipes-extended/xen/xen-common.inc
https://xenbits.xen.org/xsa/
Released 2017-10-12 12:00.
XSA-245 is ARM specific, so left out of the OpenXT layer for now.
> OXT-1227: xen: XSA 237-244.

- recipes-extended/xen/files/xsa237-4.6/0001-x86-dont-allow-MSI-pIRQ-mapping-on-unowned-device.patch
- recipes-extended/xen/files/xsa237-4.6/0002-x86-enforce-proper-privilege-when-mapping-pIRQ-s.patch
- recipes-extended/xen/files/xsa237-4.6/0003-x86-MSI-disallow-redundant-enabling.patch
- recipes-extended/xen/files/xsa237-4.6/0004-x86-IRQ-conditionally-preserve-irq-pirq-mapping-on-error.patch
- recipes-extended/xen/files/xsa237-4.6/0005-x86-FLASK-fix-unmap-domain-IRQ-XSM-hook.patch
- recipes-extended/xen/files/xsa238-4.6.patch
- recipes-extended/xen/files/xsa239.patch
- recipes-extended/xen/files/xsa240-4.6/0001-x86-limit-linear-page-table-use-to-a-single-level.patch
- recipes-extended/xen/files/xsa240-4.6/0002-x86-mm-Disable-PV-linear-pagetables-by-default.patch
- recipes-extended/xen/files/xsa241-4.8.patch
- recipes-extended/xen/files/xsa242-4.9.patch
- recipes-extended/xen/files/xsa243-4.6-1.patch
- recipes-extended/xen/files/xsa243-4.6-2.patch
- recipes-extended/xen/files/xsa244-4.6.patch
- recipes-extended/xen/files/xsa245/0001-xen-page_alloc-Cover-memory-unreserved-after-boot-in.patch
- recipes-extended/xen/files/xsa245/0002-xen-arm-Correctly-report-the-memory-region-in-the-du.patch
- recipes-extended/xen/xen-common.inc
https://xenbits.xen.org/xsa/
Released 2017-10-12 12:00.
XSA-245 is ARM specific, so left out of the OpenXT layer for now.
> STABLE-7: OXT-1227: xen: XSA 237-244.

- recipes-openxt/seabios/seabios.inc
Wget will fail to fetch from the http URL after receiving a 308. Use the
https source instead.
This seems to fail when building a new tree without cache.
> seabios: Change URL to avoid HTTP 308.

- recipes-extended/xen/files/libxl-fix-flr.patch
- recipes-extended/xen/xen-common.inc
Use correct sysfs node for the flr and perform it after the pci
device is released from the domain and the domain has been
destroyed.  This fixes the bug where certain AMD GPU passthru
devices would crash the host without a proper flr on subsequent
guest boots.
Also fixes the expected xenbus state for pci to avoid a timeout
on guest shutdown.
OXT-1217
> [libxl] Fix flr for pci passthru devices

- recipes-extended/xen/files/xsa237-4.6/0001-x86-dont-allow-MSI-pIRQ-mapping-on-unowned-device.patch
- recipes-extended/xen/files/xsa237-4.6/0002-x86-enforce-proper-privilege-when-mapping-pIRQ-s.patch
- recipes-extended/xen/files/xsa237-4.6/0003-x86-MSI-disallow-redundant-enabling.patch
- recipes-extended/xen/files/xsa237-4.6/0004-x86-IRQ-conditionally-preserve-irq-pirq-mapping-on-error.patch
- recipes-extended/xen/files/xsa237-4.6/0005-x86-FLASK-fix-unmap-domain-IRQ-XSM-hook.patch
- recipes-extended/xen/files/xsa238-4.6.patch
- recipes-extended/xen/files/xsa239.patch
- recipes-extended/xen/files/xsa240-4.6/0001-x86-limit-linear-page-table-use-to-a-single-level.patch
- recipes-extended/xen/files/xsa240-4.6/0002-x86-mm-Disable-PV-linear-pagetables-by-default.patch
- recipes-extended/xen/files/xsa241-4.8.patch
- recipes-extended/xen/files/xsa242-4.9.patch
- recipes-extended/xen/files/xsa243-4.6-1.patch
- recipes-extended/xen/files/xsa243-4.6-2.patch
- recipes-extended/xen/files/xsa244-4.6.patch
- recipes-extended/xen/files/xsa245/0001-xen-page_alloc-Cover-memory-unreserved-after-boot-in.patch
- recipes-extended/xen/files/xsa245/0002-xen-arm-Correctly-report-the-memory-region-in-the-du.patch
- recipes-extended/xen/xen.inc
https://xenbits.xen.org/xsa/
Released 2017-10-12 12:00.
XSA-245 is ARM specific, so left out of the OpenXT layer for now.
> STABLE-6: OXT-1227: xen: XSA 237-244.

- recipes-extended/xen/files/libxl-fix-flr.patch
- recipes-extended/xen/xen-common.inc
Use correct sysfs node for the flr and perform it after the pci
device is released from the domain and the domain has been
destroyed.  This fixes the bug where certain AMD GPU passthru
devices would crash the host without a proper flr on subsequent
guest boots.
Also fixes the expected xenbus state for pci to avoid a timeout
on guest shutdown.
OXT-1217
> STABLE-7: [libxl] Fix flr for pci passthru devices

- recipes-extended/xen/files/x86-hvm-do-not-register-hpet-mmio-during-s3-cycle.patch
- recipes-extended/xen/xen-common.inc
mmio handler exhaustion will have Xen destroy the domain instead of
letting it suspend.
> OXT-1236: xen: do not register hpet mmio during s3 cycle

- recipes-extended/xen/files/x86-hvm-do-not-register-hpet-mmio-during-s3-cycle.patch
- recipes-extended/xen/xen-common.inc
mmio handler exhaustion will have Xen destroy the domain instead of
letting it suspend.
(master: https://github.com/OpenXT/xenclient-oe/pull/802)
> STABLE-7: OXT-1236: xen: do not register hpet mmio during s3 cycle

- recipes-extended/xen/files/xsa246-4.7.patch
- recipes-extended/xen/files/xsa247-4.6/0001-p2m-Always-check-to-see-if-removing-a-p2m-entry-actu.patch
- recipes-extended/xen/files/xsa247-4.6/0002-p2m-Check-return-value-of-p2m_set_entry-when-decreas.patch
- recipes-extended/xen/xen-common.inc
This adds the patches for XSA 246 and 247.  While in there, I re-ordered the patch queue to keep all the XSAs at the end.  I made a separate commit for the refresh of xsa246-4.7.patch to clearly distinguish adding the upstream patch and making a modification to apply cleanly.
OXT-1255
> STABLE-7: OXT-1255: XSA 246 & 247

- recipes-openxt/xenclient/xenclient-toolstack_git.bb
This should have been part of the original commit as it was defined in
the local.conf which got move to the bbclass.
Also use the correct variable to find xen headers.
> OXT-1253: toolstack: Use the ocamlincdir from the bbclass.

- recipes-kernel/linux/4.9/patches/xen-txt-add-xen-txt-eventlog-module.patch
Xen-4.9 added a new HYPERCALL_dm_op that uses the current id
for the txt evtlog hypercall.  This commit adjusts the patch
to account for that new hypercall.
> [linux] Adjust Hypercall id for txt evtlog

- recipes-devtools/python/python-daemon_1.5.5.bb
Fix builds without cache, python-daemon still uses the deprecated http:// interfaces, switch to https as other recipes did.
> python-daemon: Fetch from https source.

- recipes-openxt/xenclient/xenmgr-data_git.bb
xenmgr-data got through OXT-1265. It uses xc-rpcgen for javascript stubs
though and should use the variables defined in the configuration/bbclass
files.
OXT-1265
Depends on:
https://github.com/OpenXT/toolstack-data/pull/48
> OXT-1265: xenmgr-data: Use xc-rpcgen.bbclass.

- recipes-extended/xen/files/xl-uivm-reboot-fix.patch
- recipes-extended/xen/xen-common.inc
OXT-1270
Instead of sleeping for random amount of time, watch on xenstore node
for xenmgr state update and proceed accordingly.
> uivm reboot fix : remove sleep(), instead perform xs_watch()

- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
The correct ESP path is \EFI\OpenXT after commit 99adcb9f1aeec3940b9ad0eb42b74a0f7570b0f7
Signed-off-by: Tamas K Lengyel <lengyelt@ainfosec.com>
> Use correct ESP path during forward-sealing

- conf/machine/xenclient-ndvm.conf
- conf/machine/xenclient-stubdomain.conf
- conf/machine/xenclient-uivm.conf
Following https://github.com/OpenXT/xenclient-oe/pull/839, add `USE_VT = "0"`, as recommended by @jandryuk, to UIVM, NDVM and stub-domains (not required but seems consistent).
> service-vms: Remove getty on consoles.

- recipes-extended/xen/files/libxl-avoid-creating-unusable-cdrom-vbd-xs-nodes.patch
- recipes-extended/xen/files/libxl-disable-json-updates.patch
- recipes-extended/xen/files/libxl-iso-hotswap.patch
- recipes-extended/xen/xen-common.inc
blkfront doesn't support CDROMs in HVMs. However, XL creates guest CDROM VBD
nodes for the virtual CD, when it only makes sense for their stubdoms. XL also
creates stubdom and guest nodes for atapi-pt drives, which doesn't make sense.
To summarize, the creation of guest virtual cd nodes and all atapi-pt nodes
should be removed from XL.
OXT-1259
> remove useless cdrom VBD nodes from xenstore

- recipes-extended/ipxe/ipxe_%.bbappend
- recipes-extended/xen/xen.bb
This was lost with xenclient-oe.git:
808a27be ipxe: Use meta-virt recipe.
The upstream ipxe intel driver got replaced:
945e4281 [intel] Replace driver for Intel Gigabit NICs
... Replace the e1000*.rom statement with the new intel.rom.
Sneak in a fix for a silly typo as well.
> OXT-1290: ipxe: Add back intel PXE rom to hvmloader.

- recipes-core/busybox/busybox_%.bbappend
No reason to update ALTERNATIVE_%s or ALTERNATIVE_LINK_NAME. Attend
following warning:
[log_check] Warn: update-alternatives: lbracket has multiple providers with the same priority, please check /home/build/openxt/master-3/tmp-glibc/work/xenclient_dom0-oe-linux/xenclient-dom0-image/1.0-r0/rootfs/usr/lib/opkg/alternatives/lbracket for details
[log_check] Warn: update-alternatives: [[ has multiple providers with the same priority, please check /home/build/openxt/master-3/tmp-glibc/work/xenclient_dom0-oe-linux/xenclient-dom0-image/1.0-r0/rootfs/usr/lib/opkg/alternatives/[[ for details
Remove remaning True option to getVar, see oe-core commits:
5b53b34dcb meta: remove remaining True option to getVarFlag calls
87d03ffe03 meta: remove remaining True option to getVar calls
This should silence …
> OXT-1293: busybox_selinux: Attend warning, update recipe.

- recipes-core/busybox/busybox_%.bbappend
No reason to update ALTERNATIVE_%s or ALTERNATIVE_LINK_NAME. Attend
following warning:
[log_check] Warn: update-alternatives: lbracket has multiple providers with the same priority, please check /home/build/openxt/master-3/tmp-glibc/work/xenclient_dom0-oe-linux/xenclient-dom0-image/1.0-r0/rootfs/usr/lib/opkg/alternatives/lbracket for details
[log_check] Warn: update-alternatives: [[ has multiple providers with the same priority, please check /home/build/openxt/master-3/tmp-glibc/work/xenclient_dom0-oe-linux/xenclient-dom0-image/1.0-r0/rootfs/usr/lib/opkg/alternatives/[[ for details
Remove remaning True option to getVar, see oe-core commits:
5b53b34dcb meta: remove remaining True option to getVarFlag calls
87d03ffe03 meta: remove remaining True option to getVar calls
(cherry picked from …
> STABLE-8: OXT-1293: busybox_selinux: Attend warning, update recipe.

- recipes-devtools/rsync/rsync_%.bbappend
- recipes-graphics/xorg-driver/xorg-driver-video.inc
- recipes-graphics/xorg-lib/libxi_1.4.5.bb
- recipes-graphics/xorg-lib/xorg-lib-common.inc
More low priority warnings:
```
WARNING: rsync-3.1.2-r0 do_configure: QA Issue: rsync: invalid PACKAGECONFIG: xattr [invalid-packageconfig]
WARNING: libxrandr-1_1.3.2-r0 do_configure: QA Issue: libxrandr: configure was passed unrecognised options: --with-fop --without-xmlto [unknown-configure-option]
WARNING: xf86-video-fbdev-2_0.4.2-r17.0.1 do_package_qa: QA Issue: Package xf86-video-fbdev contains Xorg driver (fbdev_drv.so) but no xorg-abi- dependencies [xorg-driver-abi]
```
> layer: Attend left-over QA warnings (pass 3)

- recipes-kernel/linux/4.14/linux-openxt_4.14.22.bb
- recipes-kernel/linux/linux-openxt-copy-objtool.inc
- recipes-kernel/linux/linux-openxt.inc
CONFIG_STACK_VALIDATION=y will require objtool available for out-of-tree
modules to generate object files.
Taken from commit:
https://patchwork.openembedded.org/patch/148047/
> OXT-1297: linux-4.14: objtool for out-of-tree modules.

- recipes-kernel/linux/4.14/linux-openxt_4.14.22.bb
- recipes-kernel/linux/linux-openxt-copy-objtool.inc
- recipes-kernel/linux/linux-openxt.inc
CONFIG_STACK_VALIDATION=y will require objtool available for out-of-tree
modules to generate object files.
Taken from commit:
https://patchwork.openembedded.org/patch/148047/
> STABLE-8: OXT-1297: linux-4.14: objtool for out-of-tree modules.

- recipes-extended/xen/files/libxl-atapi-pt.patch
- recipes-extended/xen/files/libxl-vwif-support.patch
xl network-detach is currently broken, seems like changes were missed
while porting to xen-4.9
OXT-1301
(cherry picked from commit bf22feff03a04e80f186a52fdbe8e183699d4c0c)
> STABLE-8: OXT-1301: xl: fix network detach

- recipes-core/dbus/dbus_1.%.bbappend
DEPENDS applies for the whole recipe, giving it an `"_<PACKAGE>"` will
have Bitbake ignore it.
DBus does not require xen as depend (libv4v does).
Since libv4v is optional for that recipe, depend on it only for the
target build. DBus recipe provides native tools, and libv4v is not
needed for that.
> OXT-1306: dbus: Fix recipe DEPENDS statement.

- recipes-core/dbus/dbus_1.%.bbappend
DEPENDS applies for the whole recipe, giving it an "_<PACKAGE>" will
have Bitbake ignore it.
DBus does not require xen as depend (libv4v does).
Since libv4v is optional for that recipe, depend on it only for the
target build. DBus recipe provides native tools, and libv4v is not
needed for that.
> STABLE-8: OXT-1306: dbus: Fix recipe DEPENDS statement.

- recipes-core/microcode/intel-microcode_20180312.bb
This brings in most of the Spectre ucode support.  We want this so Xen 4.9.2 can take advantage of the ucode features.
Part of OXT-1267, OXT-1268
> intel-microcode: Update to 20180312

- recipes-core/microcode/intel-microcode_20180312.bb
This brings in most of the Spectre ucode support.
Part of OXT-1267, OXT-1268
(cherry picked from commit 53d4455a50203ad2812b6a5c776d2a36c6b8031b)
This is the Stable-8 version of https://github.com/OpenXT/xenclient-oe/pull/873
> STABLE-8: intel-microcode: Update to 20180312

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Using /sys/class/tpm/tpm0/device/description is unreliable as the entry
might not be populated by the driver.
From:
https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-tpm
It is recommended to use /sys/class/tpm/tpmX/device/caps instead. One
caveat though is documented in the TPM module sources:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/drivers/char/tpm/tpm-sysfs.c?h=v4.14.34#n296
TPM 2.0 devices will not expose /sys/class/tpm/tpmX/device/caps (this is
still the case to this day in Linux 4.16 line). So assuming a
TPM is detected, the absence of this file reveals a TPM 2.0 version.
(cherry picked from commit 4a1b0c75031099eab155f3c241cf5d963d2dcb91)
> STABLE-8: OXT-1311: tpm: Detect TPM version from sysfs caps entry.

- recipes-openxt/tss/tpm2-tools/0001-tpm2_listpcrs-use-TPM2_GetCapability-to-determine-PC.patch
- recipes-openxt/tss/tpm2-tools/0002-listpcrs-remove-one-redundant-call-to-tpm-get-cap.patch
- recipes-openxt/tss/tpm2-tools/0003-listpcrs-fix-for-unsupported-disabled-alg-in-L.patch
- recipes-openxt/tss/tpm2-tools_git.bb
As suggested on:
- https://github.com/tpm2-software/tpm2-tools/pull/294
- https://github.com/tpm2-software/tpm2-tools/pull/295
Backport the following fixes:
tpm2_listpcrs: use TPM2_GetCapability to determine PCRs
listpcrs: remove one redundant call to tpm get cap
listpcrs: fix for unsupported/disabled alg in -L
(cherry picked from commit b6e5145e7b89af57178ee41fc314a93c66bd2924)
> STABLE-8: OXT-1313: tpm2-tools: backport fixes for tpm2_listpcrs.

- recipes-core/sysvinit/sysvinit-inittab_%.bbappend
- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
- recipes-openxt/xenclient/surfman/surfman.initscript
- recipes-openxt/xenclient/surfman_git.bb
- recipes-openxt/xenclient/updatemgr_git.bb
- recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
- recipes-openxt/xenclient/xenclient-dom0-tweaks/openxt.cfg
- recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
- recipes-openxt/xenclient/xenmgr/xenmgr_git.bb
This is the stable-8 version of https://github.com/OpenXT/xenclient-oe/pull/858
We only want to run a getty on tty1 in console mode, and suppress the getty for graphical boots. Use init runlevels to differentiate between text console (runlevel 3) and graphical (5) boots.
More discussion is here https://github.com/OpenXT/xenclient-oe/pull/858
> STABLE-8: OXT-1300: Use runlevels to control console login

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
- recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
Using /sys/class/tpm/tpm0/device/description is unreliable as the entry
might not be populated by the driver.
From:
https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-tpm
It is recommended to use /sys/class/tpm/tpmX/device/caps instead. One
caveat though is documented in the TPM module sources:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/drivers/char/tpm/tpm-sysfs.c?h=v4.14.34#n296
TPM 2.0 devices will not expose /sys/class/tpm/tpmX/device/caps (this is
still the case to this day in Linux 4.16 line). So assuming a
TPM is detected, the absence of this file reveals a TPM 2.0 version.
This is an alternative to other propositions:
- https://github.com/OpenXT/xenclient-oe/pull/844 using dmesg
- https://github.com/OpenXT/xenclient-oe/pull/853 …
> OXT-1311: tpm: Detect TPM version from sysfs caps entry.

- recipes-openxt/tss/tpm2-tools/0001-tpm2_listpcrs-use-TPM2_GetCapability-to-determine-PC.patch
- recipes-openxt/tss/tpm2-tools/0002-listpcrs-remove-one-redundant-call-to-tpm-get-cap.patch
- recipes-openxt/tss/tpm2-tools/0003-listpcrs-fix-for-unsupported-disabled-alg-in-L.patch
- recipes-openxt/tss/tpm2-tools_git.bb
As suggested on:
- https://github.com/tpm2-software/tpm2-tools/pull/294
- https://github.com/tpm2-software/tpm2-tools/pull/295
Backport the following fixes:
tpm2_listpcrs: use TPM2_GetCapability to determine PCRs
listpcrs: remove one redundant call to tpm get cap
listpcrs: fix for unsupported/disabled alg in -L
> OXT-1313: tpm2-tools: backport fixes for tpm2_listpcrs.

- recipes-extended/xen/files/efi-load-option-support.patch
- recipes-extended/xen/files/shim-support-for-shim-lock-measure.patch
Make Xen query the firmware for the status of SecureBoot to determine whether to use `shim_lock->Measure` or `shim_lock->Verify` on the dom0 kernel.
Move definition of `elo_active` to the efi-load-option-support.patch where it belongs.
Signed-off-by: Tamas K Lengyel <lengyelt@ainfosec.com>
> OXT-1314: Update Xen patches: support for SecureBoot and minor fixes

- recipes-core/images/xenclient-installer-image/grub.cfg
Right now, there is no timeout, so grub waits forever.  Add a default
timeout so we boot into the installer and wait there instead.  This
matches the legacy isolinux boot behaviour.
> installer-image: Add timeout to UEFI grub.cfg

- recipes-core/images/xenclient-installer-image/grub.cfg
This is the Stable-8 version of https://github.com/OpenXT/xenclient-oe/pull/875
Right now, there is no timeout, so grub waits forever.  Add a default
timeout so we boot into the installer and wait there instead.  This
matches the legacy isolinux boot behaviour.
(cherry picked from commit 1d8fa36e52ab54f3114b54edf855234615599a48)
> STABLE-8: installer-image: Add timeout to UEFI grub.cfg

- recipes-extended/xen/files/v4v.patch
The original change didn't fix v4v for HVMs with SMAP on Xen 4.9.  It
relied on smap_check_policy in guest_walk_tables to skip the SMAP check,
but that was removed between Xen 4.6 and 4.9.  Upstream NACK-ed
re-introducing support in guest_walk_tables and suggested wrapping the
v4v hypercall in the guest kernel with stac/clac.  We'll do that in the
v4v module: https://github.com/OpenXT/v4v/pull/36
This reverts commit 816157744a05a32e206ddf2eddd504bc0cb09587.
OXT-1304
(cherry picked from commit bfd1cf097cc55504cc2c68513ad940e46cae8bbd)
> STABLE-8: Revert "v4v: Fix SMAP & HVM guest use"

- recipes-extended/xen/files/xen-translate.patch
PGC_pinned_by_tools is a flag in page->count_info field, hence
PGC_count_width should be incremented to accomodate for it. Ref-count
has to be quite high to make this fail, which is why no misbehavior was
seen until now.
XenServer maintains an equivalent hunk in one patch:
https://github.com/xenserver/xen-4.7.pg/blob/1b778262c1b4a3c7c8e504d50e0149fe5909d670/master/nvidia-hypercalls.patch#L487
OXT-1258
> STABLE-8: OXT-1258:  xen: Ammend PGC_pinned_by_tools declaration

- recipes-extended/rsyslog/patches/0001-core-bugfix-segfault-after-configuration-errors.patch
- recipes-extended/rsyslog/patches/CVE-2017-12588.patch
- recipes-extended/rsyslog/rsyslog_%.bbappend
- Fix logrorate configuration not installed in the correct `/etc/logrorate.d` directory;
- Backport CVE-2017-12588;
- Backport fix for segfault after configuration errors.
Until sent upstream for `pyro-next`.
> OXT-1325, OXT-1326: rsyslog fix for logrorate and other backports.

- recipes-extended/rsyslog/patches/0001-core-bugfix-segfault-after-configuration-errors.patch
- recipes-extended/rsyslog/patches/CVE-2017-12588.patch
- recipes-extended/rsyslog/rsyslog_%.bbappend
- Fix logrorate configuration not installed in the correct `/etc/logrorate.d` directory;
- Backport CVE-2017-12588;
- Backport fix for segfault after configuration errors.
Until sent upstream for `pyro-next`.
> STABLE-8: OXT-1325, OXT-1326: rsyslog fix for logrorate and other backports.

- recipes-openxt/xenclient/v4v-module-headers_git.bb
- recipes-openxt/xenclient/v4v-module_git.bb
- Use `module.bbclass` to build the out-of-tree V4V module.
- Use `headers_install` Makefile rules to deploy headers. Inherit `allarch.bbclass` since they are arch independent.
- Remove deprecated deb packaging statements, these are no longer used.
- Use `COPYING` file to check the license.
- https://github.com/OpenXT/pv-linux-drivers/pull/44
- https://github.com/OpenXT/v4v/pull/37
- https://github.com/OpenXT/openxt/pull/304
> OXT-1322: v4v: Refresh the recipes.

- recipes-openxt/initrdscripts/initramfs-xenclient/init.sh
- recipes-openxt/xenclient/xenclient-config-access/config-access.initscript
- recipes-openxt/xenclient/xenclient-root-ro/init.root-ro
Silence warning:
modprobe: FATAL: Module fbcon not found in directory /lib/modules/4.14.34
(cherry picked from commit 09917750cd3f614ba7f77fda2da7e6a39e872bc7)
Relates to: https://github.com/OpenXT/installer/pull/75
> STABLE-8: OXT-1321: fbcon: The module is now builtin.

- recipes-openxt/xenclient/uid/uid.initscript
UID does not create a pidfile by itself.
Use start-stop-daemon --background to start uid non-daemonized and use
--make-pidfile to track the process life-cycle with start-stop-daemon.
This should avoid noisy warning at restart and shutdown:
>Stopping UID server
>BusyBox v1.24.1 (2018-05-14 11:50:53 EDT) multi-call binary.
>
>Usage: start-stop-daemon [OPTIONS] [-S|-K] ... [-- ARGS...]
> OXT-1332: uid: pidfile for uid in initscript.

- recipes-openxt/xenclient/uid/uid.initscript
UID does not create a pidfile by itself.
Use start-stop-daemon --background to start uid non-daemonized and use
--make-pidfile to track the process life-cycle with start-stop-daemon.
This should avoid noisy warning at restart and shutdown:
>Stopping UID server
>BusyBox v1.24.1 (2018-05-14 11:50:53 EDT) multi-call binary.
>
>Usage: start-stop-daemon [OPTIONS] [-S|-K] ... [-- ARGS...]
(cherry picked from commit f1c53185687141e3e88cf13bc50024fad1d902d1)
> STABLE-8: OXT-1332: uid: pidfile for uid in initscript.

- classes/xenclient-customtask.bbclass
xenclient-customtask does not work with Python 3 recent versions:
https://docs.python.org/3/library/functools.html
(cherry picked from commit 1e0472694326152af785cae12999d13fc2a7f52c)
> STABLE-8: customtask: python reduce was moved in functools.

- recipes-kernel/linux/4.14/patches/usbback-base.patch
usbback can be led to BUG() if allocated pages to handle requests from the frontend get exhausted. This is easy to achieve using isochronous devices (webcam, microphones?) that will use indirect requests.
The BUG() crash can be avoided altogether. Increasing the pool of pages should take care of most devices. This is already a module parameter, these changes double the default value.
> OXT-1319: usbback: Fix dom0 crash when assigning greedy devices.

- recipes-kernel/linux/4.14/patches/usbback-base.patch
usbback can be led to BUG() if allocated pages to handle requests from the frontend get exhausted. This is easy to achieve using isochronous devices (webcam, microphones?) that will use indirect requests.
The BUG() crash can be avoided altogether. Increasing the pool of pages should take care of most devices. This is already a module parameter, these changes double the default value.
> STABLE-8: OXT-1319: usbback: Fix dom0 crash when assigning greedy devices.

- recipes-support/dnsmasq/patches/dnsmasq_dnsout_interface.patch
Upstream upgrade to 2.78:
[a9c2ab5e7 dnsmasq: upgrade to 2.78](https://github.com/openembedded/meta-openembedded/commit/a9c2ab5e7527c2ccdb9fc375a9bf3b1faa57bb57)
Refresh the patch since new options were introduced.
Fix master builds.
> dnsmasq: Refresh patch against new minor version.

- recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
Currently, /config/config.pcrs is only written during installation. If we are upgrading, we must write out /config/config.pcrs to ensure new values are used if the PCR selection changed.
configure_measured_launch() is only called on install, so changes to the
pcr sealing set don't take affect on upgrate.  Split out writing
/config/config.pcrs so it can be used on upgrade.
OXT-1351
> OXT-1351: Change PCR Sealing selection on upgrade

- recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
This is the stable-8 version of https://github.com/OpenXT/xenclient-oe/pull/925
Currently, /config/config.pcrs is only written during installation. If we are upgrading, we must write out /config/config.pcrs to ensure new values are used if the PCR selection changed.
configure_measured_launch() is only called on install, so changes to the
pcr sealing set don't take affect on upgrate.  Split out writing
/config/config.pcrs so it can be used on upgrade.
OXT-1351
(cherry picked from commit a9e0ffaa20a5a52d29acfcc71bd0163da3705208)
> STABLE-8: OXT-1351: Change PCR Sealing selection on upgrade

- recipes-support/dnsmasq/patches/dnsmasq_dnsout_interface.patch
Upstream upgrade to 2.78:
a9c2ab5e7 dnsmasq: upgrade to 2.78
Refresh the patch since new options were introduced.
(cherry picked from commit 4f45e6125b97750acd40bf587436ab633c27d1cf)
> STABLE-8: OXT-1350: dnsmasq: Refresh patch against new minor version.

- recipes-core/dbus/dbus_1.%.bbappend
- recipes-core/dbus/patches/fix-segfault-bus_connection_disconnected.patch
Running /etc/init.d/dbus-1 stop will segfault consistently on OpenXT:
```
dbus-daemon[728]: segfault at 0 ip b7eb170a sp bf8468a8 error 6 in libdbus-1.so.3.14.9[b7e83000+5a000]
```
Here is a trace:
```
Thread 1 "dbus-daemon" received signal SIGSEGV, Segmentation fault.
0xb7ee970a in _dbus_list_unlink (list=0x8c78580, link=0x8c8e200) at /usr/src/debug/dbus/1.10.14-r0/dbus-1.10.14/dbus/dbus-list.c:510
510           link->next->prev = link->prev;
(gdb) bt
```
It seems that bus_context_unref can re-use a cleared list in its path:
```
-> bus_context_unref
-> bus/connection.c:544: _dbus_list_clear (&connections->monitors);
-> bus/connection.c:555: bus_connection_disconnected (connection);
-> bus/connection.c:305: _dbus_list_remove_link (&d->connections->monitors, d->link_in_monitors); …
```
> OXT-1361: dbus: Avoid segfault when stopping dbus-daemon.

- recipes-core/dbus/dbus_1.%.bbappend
- recipes-core/dbus/patches/fix-segfault-bus_connection_disconnected.patch
Running /etc/init.d/dbus-1 stop will segfault consistently on OpenXT:
dbus-daemon[728]: segfault at 0 ip b7eb170a sp bf8468a8 error 6 in libdbus-1.so.3.14.9[b7e83000+5a000]
Here is a trace:
```
Thread 1 "dbus-daemon" received signal SIGSEGV, Segmentation fault.
0xb7ee970a in _dbus_list_unlink (list=0x8c78580, link=0x8c8e200) at /usr/src/debug/dbus/1.10.14-r0/dbus-1.10.14/dbus/dbus-list.c:510
510           link->next->prev = link->prev;
(gdb) bt
```
It seems that bus_context_unref can re-use a cleared list in its path:
```
-> bus_context_unref
-> bus/connection.c:544: _dbus_list_clear (&connections->monitors);
-> bus/connection.c:555: bus_connection_disconnected (connection);
-> bus/connection.c:305: _dbus_list_remove_link (&d->connections->monitors, d->link_in_monitors); …
```
> STABLE-8: OXT-1361: dbus: Avoid segfault when stopping dbus-daemon.

- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
Select correct TPM version and TPM_DEV already includes /device in the
TPM1.2 path
Signed-off-by: Tamas K Lengyel <lengyelt@ainfosec.com>
> OXT-1362: Fix UEFI forward-seal

- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
Select correct TPM version and TPM_DEV already includes /device in the
TPM1.2 path
Signed-off-by: Tamas K Lengyel <lengyelt@ainfosec.com>
> OXT-1362: Fix UEFI forward-seal (stable-8)

- recipes-kernel/linux/4.14/patches/xen-txt-add-xen-txt-eventlog-module.patch
Without text, the tristate option is not displayed in menuconfig and
cannot be disabled. Add text to allow disabling, but also default to
disabled.  Also, slightly improve the help text.
The Dom0 and Installer kernels already select this in their respective
defconfigs, so it doesn't change for them.
OXT-1363
> OXT-1363: linux: Allow disabling txt event log in Kconfig

- recipes-kernel/linux/4.14/patches/xen-txt-add-xen-txt-eventlog-module.patch
This is the stable-8 version of https://github.com/OpenXT/xenclient-oe/pull/940
Without text, the tristate option is not displayed in menuconfig and
cannot be disabled. Add text to allow disabling, but also default to
disabled. Also, slightly improve the help text.
The Dom0 and Installer kernels already select this in their respective
defconfigs, so it doesn't change for them.
OXT-1363
Signed-off-by: Jason Andryuk jandryuk@gmail.com
> STABLE-8: OXT-1363: linux: Allow disabling txt event log module in Kconfig

- recipes-extended/xen/blktap3/tapback.initscript
- recipes-openxt/xctools/xcpmd/xcpmd.initscript
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.fc
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.te
Use pidfiles to track daemons processes and stop them with `start-stop-daemon`.
- https://github.com/OpenXT/blktap3/pull/8
- https://github.com/OpenXT/xctools/pull/46
> STABLE-8: OXT-1352, OXT-1353: tapback, xcpmd: Fixes to initscript to use pidfiles.

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.iptables.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.lvm.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.modutils.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/input-server.te
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/updatemgr.te
- recipes-security/refpolicy/refpolicy-mcs_2.%.bbappend
Backport one upstream modification to the refpolicy-mcs and attend a few other AVC that regularly trigger on OpenXT.
> STABLE-8: OXT-136{4,5,6,7}: avc denials.

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.iptables.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.lvm.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.modutils.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/input-server.te
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/updatemgr.te
- recipes-security/refpolicy/refpolicy-mcs_2.%.bbappend
Backport one upstream modification to the refpolicy-mcs and attend a few other AVC that regularly trigger on OpenXT.
> OXT-136{4,5,6,7}: avc denials. 

- recipes-kernel/linux/4.14/defconfigs/openxt-installer/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-dom0/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-ndvm/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-nilfvm/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-stubdomain/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-syncvm/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-uivm/defconfig
- recipes-kernel/linux/4.14/linux-openxt_4.14.53.bb
- recipes-kernel/linux/4.14/patches/extra-mt-input-devices.patch
- recipes-kernel/linux/4.14/patches/usbback-base.patch
No significant change to the patch-queue of defconfig.
```
d08dfdeaf49d xen: Remove unnecessary BUG_ON from __unbind_from_irq()
dbb37d98b93d x86/xen: Add call of speculative_store_bypass_ht_init() to PV paths
CVE-2018-10840  21542545990c ext4: correctly handle a zero-length xattr with a non-zero e_value_offs
CVE-2018-11412  02d45ec6e770 ext4: bubble errors from ext4_find_inline_data_nolock() up to ext4_iget()
CVE-2018-11412  e81d371dac30 ext4: do not allow external inodes for inline data
a951cf4da896 x86/xen: Reset VCPU0 info pointer after shared_info remap
ff3080bab10d xen: xenbus_dev_frontend: Really return response string
53e4b19fcd0c kvm: x86: use correct privilege level for sgdt/sidt/fxsave/fxrstor access
```
> OXT-1373: linux: micro upgrade to 4.14.53

- recipes-kernel/linux/4.14/defconfigs/openxt-installer/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-dom0/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-ndvm/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-nilfvm/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-stubdomain/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-syncvm/defconfig
- recipes-kernel/linux/4.14/defconfigs/xenclient-uivm/defconfig
- recipes-kernel/linux/4.14/linux-openxt_4.14.53.bb
- recipes-kernel/linux/4.14/patches/extra-mt-input-devices.patch
- recipes-kernel/linux/4.14/patches/usbback-base.patch
No significant change to the patch-queue of defconfig.
```
d08dfdeaf49d xen: Remove unnecessary BUG_ON from __unbind_from_irq()
dbb37d98b93d x86/xen: Add call of speculative_store_bypass_ht_init() to PV paths
CVE-2018-10840  21542545990c ext4: correctly handle a zero-length xattr with a non-zero e_value_offs
CVE-2018-11412  02d45ec6e770 ext4: bubble errors from ext4_find_inline_data_nolock() up to ext4_iget()
CVE-2018-11412  e81d371dac30 ext4: do not allow external inodes for inline data
a951cf4da896 x86/xen: Reset VCPU0 info pointer after shared_info remap
ff3080bab10d xen: xenbus_dev_frontend: Really return response string
53e4b19fcd0c kvm: x86: use correct privilege level for sgdt/sidt/fxsave/fxrstor access
```
(cherry picked from commit ad9d37b46958cdbbd247cd46173fd486509026d7)
> STABLE-8: OXT-1373: linux: micro upgrade to 4.14.53

- recipes-extended/xen/blktap3/tapback.initscript
- recipes-openxt/xctools/xcpmd/xcpmd.initscript
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.fc
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.te
Use pidfiles to track daemons processes and stop them with `start-stop-daemon`.
https://github.com/OpenXT/blktap3/pull/7
https://github.com/OpenXT/xctools/pull/44
> OXT-1352, OXT-1353: tapback, xcpmd: Fixes to initscript to use pidfiles.

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.lvm.diff
This will allow proper transition when creating pidfile.
Silence `lvmetad.socket` related AVCs.
> OXT-1364: lvm: lvmetad context is lvm_exec_t

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.lvm.diff
This will allow proper transition when creating pidfile.
Silence `lvmetad.socket` related AVCs.
Master PR: https://github.com/OpenXT/xenclient-oe/pull/958
> STABLE-8: OXT-1364: lvm: lvmetad context is lvm_exec_t

- recipes-core/base-files/files/fstab.early
(cherry picked from commit f057ec31a76dff9de7486a304905d4f6c6c7e90e)
> STABLE-8: fstab.early: mount the securityfs for the txt module

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.modutils.diff
During its initialization, our "txt" Linux module searches the securityfs.
Therefore, modprobe (insmod) needs to be able to do that.
> refpolicy: allow modprobe to search the securityfs to load txt

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.modutils.diff
During its initialization, our "txt" Linux module searches the securityfs.
Therefore, modprobe (insmod) needs to be able to do that.
(cherry picked from commit c4fd831185ed3420bc3732309095e6b9507aaa81)
> STABLE-8: refpolicy: allow modprobe to search the securityfs to load txt

- recipes-openxt/qemu-dm/qemu-dm/switcher.patch
acpi.patch adds this call chain:
acpi_pm1_cnt_write
xenstore_update_power
xen_input_send_shutdown
dmbus_send
When xen_input has not been initialized, dmbus_send segfaults since
input.service is NULL.  If we aren't using xen-input, then we don't need
to notify input_server.  That way we avoid the segfault.
Maybe this should be moved to xen_input_deinit?  In that case, we
wouldn't have the shutdown reason on hand - it would need to be stashed
somewhere.
OXT-1360
> qemu-dm: Avoid segfault in dmbus_send

- recipes-connectivity/openssh/files/xenclient-dom0/sshd_config
> sshd_config: use alternative auth method that handles empty passwords correctly

- recipes-core/images/xenclient-installer-image/grub.cfg
- recipes-openxt/xenclient/xenclient-dom0-tweaks/openxt.cfg
When using OpenXT UEFI installer, boot only Linux. The current main graph of the UEFI installer does not use Xen.
When booting into OpenXT, pass efi=no-rs to Xen to disable EFI runtime services. Runtime services are currently only used during the installation. Add attr=uc as well, some firmwares flag their memory incorrectly.
This allows OpenXT to install, Boot and setup MLE (including performing forward-seal) on HP 800 G1 and HP 850 G2 with UEFI, as surely other machines with similar firmware.
Other work-around have been attempted before and are documented in the ticket.
> OXT-1377: Work around sensitive EFI firmwares

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/xc-installer-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/system/xc-installer.if
While performing OTA upgrade, part2 installer scripts will fail in
seal-system because of an AVC:
avc:  denied  { mounton } for  pid=3949 comm="mount" path="/tmp/esp" dev="tmpfs" ino=26094 scontext=system_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:xc_installer_tmp_t:s0 tclass=dir permissive=0
> OXT-1393: refpolicy-mcs: Allow installer part2 to mount ESP.

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/xc-installer-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/system/xc-installer.if
While performing OTA upgrade, part2 installer scripts will fail in
seal-system because of an AVC:
avc:  denied  { mounton } for  pid=3949 comm="mount" path="/tmp/esp" dev="tmpfs" ino=26094 scontext=system_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:xc_installer_tmp_t:s0 tclass=dir permissive=0
(cherry picked from commit 4f29bf573e588e42e95f03fd9033c1306f730329)
> STABLE-8: OXT-1393: refpolicy-mcs: Allow installer part2 to mount ESP.

- recipes-openxt/tss/tpm2-tools/tpm2-fix-forward-seal.patch
Do not leak previous values on N+1 parse operation.
> OXT-1395: tpm2-tools: reset hash_set variable during parsing

- recipes-openxt/tss/tpm2-tools/tpm2-fix-forward-seal.patch
Do not leak previous values on N+1 parse operation.
(cherry picked from commit 6f1a94167540c7b9e10362c5fd62ac67df22b0ce)
> STABLE-8: OXT-1395: tpm2-tools: reset hash_set variable during parsing

- recipes-core/images/xenclient-installer-image/grub.cfg
The console used to be set on the Xen cmdline. Pass it to Linux.
> installer: Add ttyS0 console back to the cmdline

- recipes-core/images/xenclient-installer-image/grub.cfg
The console used to be set on the Xen cmdline. Pass it to Linux.
(cherry picked from commit 2a7bb2774a52b1e94bfd745c7f942cb2be316956)
> STABLE-8: installer: Add ttyS0 console back to the cmdline

- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
@jean-edouard's fix including @jandryuk's recommendations.
EV_SEPARATOR can vary between firmwares with TPM1.2 families.
This value can be read from the sysfs in all observed cases, still keep
a fallback just in case.
https://github.com/OpenXT/xenclient-oe/pull/986
> OXT-1396: openxt-ml: read ev_separator in sysfs, if possible

- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
@jean-edouard's fix including @jandryuk's recommendations.
EV_SEPARATOR can vary between firmwares with TPM1.2 families.
This value can be read from the sysfs in all observed cases, still keep
a fallback just in case.
https://github.com/OpenXT/xenclient-oe/pull/987
(cherry picked from commit 3dcce882b34a46bb925e1a909b0c31271d8b61c1)
> STABLE-8: OXT-1396: openxt-ml: read ev_separator in sysfs, if possible

- recipes-security/selinux/libselinux/libselinux_2.%.bbappend
restorecon fails with EOVERFLOW (Value too large for defined data type)
when calling lstat on files >2GB in size.  Setting _FILE_OFFSET_BITS=64
makes compilation use 64bit struct stat64 and stat64 behind the scene
without changing the source to avoid file size issues.
This is needed to support restorecon on /storage/xc-reserved and other
large VM image files.
OXT-1388
This version changes CFLAGS as opposed to TARGET_CFLAGS in https://github.com/OpenXT/xenclient-oe/pull/981
> OXT-1388: libselinux: Compile with _FILE_OFFSET_BITS=64

- recipes-extended/rsyslog/files/xenclient-dom0/rsyslog.conf
The current format looks like:
Jan  1 12:34:56.789012 xenconsoled: Network (1): message
This changes the format to:
Jan  1 12:34:56.789012 VM Network (1): message
Which drops 10 characters off each VM line.
OXT-1409
> OXT-1409: rsyslog: Use custom format for VM messages

- classes/module-signing.bbclass
This fixes module signing on a clean build when
${STAGING_KERNEL_BUILDDIR}/scripts/sign-file isn't populated.
On a clean build, do_sign_modules fails when using a specified
$KERNEL_MODULE_SIG_KEY when it cannot find sign-file.  do_sign_modules
runs before sign-file has been installed into $STAGING_KERNEL_BUILDDIR.
module-base.bbclass provides do_make_scripts which is responsible for
the installation, but that is only run when an out-of-tree module is
built.
module-base cannot be inherited into the kernel build because it creates
a dependency loop.
The kernel build dir ${B} already has sign-file, so just check for it
there in addition to the $STAGING_KERNEL_BUILDDIR.
> OXT-1403: Signed modules fix

- recipes-extended/seabios/seabios_1.9.%.bbappend
Change premirror, tarballs are now at:
https://www.seabios.org/downloads/
> OXT-1410: seabios: Change source URL

- recipes-extended/seabios/seabios_1.9.%.bbappend
Change premirror, tarballs are now at:
https://www.seabios.org/downloads/
(cherry picked from commit d125f1c790ebc80bc0f528cb16787946a1a78544)
> STABLE-8: OXT-1410: seabios: Change source URL

- recipes-openxt/xenclient/xenclient-installer_git.bb
xenclient-installer is arch-independent since it is a bunch of shell
scripts.  Mark it as such by inheriting allarch.
> xenclient-installer: Make package arch-independent

- recipes-openxt/qemu-dm/qemu-dm/qmp-v4v-char-driver.patch
Add a chardev v4v stream mode.  This bypasses the handshaking of the
datagram mode.
By default, v4v chardev runs as datagram, connecting back to QMP in dom0: `-chardev v4v,id=id[,port=5100][,domid=0][,localport=15100][,stream=on|off]`
If localport is not specified, it defaults to port + 10000.
> OXT-1407: QEMU v4v stream

- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-libxl.bb
- recipes-extended/xen/xen-version.inc
- recipes-extended/xen/xen-xsm-policy_git.bb
With the .meta files releases with XSAs, maintainance overhead is
greatly reduced if tracking stable-X.Y staging branches until the
RELEASE-X.Y.Z tag is announced.
Xen's build system does some fetching on its own when building certain
components (QEMU, firwares, mini-os, vtpm, etc). This would have to be
dealt with in time, these receipes should not need this yet.
- https://github.com/OpenXT/openxt/pull/321
> OXT-1346: xen: Fetch from git stable branch.

- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
From initial discussion on https://github.com/OpenXT/xenclient-oe/pull/984.
seal-system is called from the installer install-main:seal_system() only
on upgrade. It is executed as chroot ${DOM0_MOUNT} /usr/sbin/seal-system
-f -r ${ROOT_DEV}. seal-system is mounting ESP to grab all the files
needed for forward sealing. These were copied from the new dom0 image on
$DOM0_MOUNT into ESP in the first place copy_to_esp.
Knowning that, assume default path for the measured files and provide
two new options to seal-system:
```
-4  [object[,objects]]  List, comma ',' separated, of objects measured
in pcr4 for UEFI installations. The hash of the
first object in the list is calculated by
pesign, according to the specification.
-8  [object[,objects]]  List, comma ',' separated, of objects measured
in …
```
> OXT-1397: openxt-ml: Do not mount ESP in seal-system.

- recipes-extended/seabios/seabios_1.9.%.bbappend
First, PREMIRRORS is a little too strong to be defined at the recipe
level like so. I imagine it is more intended at providing a local.conf
override to fetch sources from a local cache. Having PREMIRRORS_prepend
makes that much more difficult.
Also, in this case, the upstream recipe has been fixed (at least was
yesterday).
This source is quite volatile. It should be recommended to fetch from a
stable mirror.
Maybe put the tarball on mirror.openxt.org and add a {PRE,}MIRRORS
statement in the default configuration file.
> OXT-1410: seabios: Remove PREMIRRORS statement.

- recipes-openxt/xenclient/xenclient-uivm-xsessionconfig/xinitrc
Not sure why that changes anything, but this is what xfce does by default,
and it ensures terminals always spawn in the foreground.
> xfwm: start as daemon instead of background

- recipes-kernel/modules/modules-1.0/xenclient-dom0/modules
dom0 doesn't provide network backends in OpenXT, ndvm does, so xen-netback is not needed.
The wacom module isn't even built for dom0.
> dom0: disable auto-loading of a couple modules

- recipes-extended/xen/files/acpi-slic-support.patch
This is a fix for libxl to support PVH.  xenmgr requires changes to generate a PVH xl.cfg.
acpi-slic-support.patch changes acpi_build_tables to modify the OEM ID
so a passed through SLIC table works for Windows activation.  It does so
by modifying the ACPI tables on the fly.  This works fine when run as
part of hvmloader, but it segfaults when the code runs in the xl process
for a PVH domain.
The xl segfault is in is_slic() trying to accessing memory in the range
0xfc00xxxx, ACPI_INFO_PHYSICAL_ADDRESS.  acpi_build_tables calls v2p to
convert pointers to the destination physical address.  In hvmloader
this is a no-op, so continued access through those pointers works.  With
xl for a PVH domain, it does an actual conversion to the destination
ACPI memory range which is invalid for the …
> OXT-1383: xen: Bypass ACPI SLIC support for PVH

- recipes-extended/seabios/seabios_1.9.%.bbappend
First, PREMIRRORS is a little too strong to be defined at the recipe
level like so. I imagine it is more intended at providing a local.conf
override to fetch sources from a local cache. Having PREMIRRORS_prepend
makes that much more difficult.
Also, in this case, the upstream recipe has been fixed (at least was
yesterday).
This source is quite volatile. It should be recommended to fetch from a
stable mirror.
Maybe put the tarball on mirror.openxt.org and add a {PRE,}MIRRORS
statement in the default configuration file.
(cherry picked from commit 5df84f3913dd20edd433611213aa6c3a4e6b40e6)
> STABLE-8: OXT-1410: seabios: Remove PREMIRRORS statement.

- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/updatemgr.te
Use the correct interface to allow read permission on
/proc/sys/vm/overcommit_memory.
While kernel_read_vm_sysctls() will give appropriate permission to find
the overcommit_memory procfs node, that last one is labelled
sysctl_vm_overcommit_t.
kernel.if defines kernel_read_vm_overcommit_sysctl() macro which allow
both kernel_search_vm_syctls() and sysctl_vm_overcommit_t
read_file_perms required by updatemgr.
> OXT-1365: refpolicy-mcs: give updatemgr overcommit read perm

- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/updatemgr.te
Use the correct interface to allow read permission on
/proc/sys/vm/overcommit_memory.
While kernel_read_vm_sysctls() will give appropriate permission to find
the overcommit_memory procfs node, that last one is labelled
sysctl_vm_overcommit_t.
kernel.if defines kernel_read_vm_overcommit_sysctl() macro which allow
both kernel_search_vm_syctls() and sysctl_vm_overcommit_t
read_file_perms required by updatemgr.
(cherry picked from commit 31bf8fd5bcd131ae49e95e9d717e611c1e3e1ae6)
> STABLE-8: OXT-1365: refpolicy-mcs: give updatemgr overcommit read perm

- classes/module-signing.bbclass
Use a lockfile to avoid racing between make_scripts and sign_modules tasks.
Also fix the error condition for the sign-file detection.
> module-signing: Fix SIGN_FILE error detection

- recipes-kernel/linux/4.14/linux-openxt_4.14.66.bb
- recipes-kernel/linux/4.14/patches/xsa270.patch
https://xenbits.xen.org/xsa/advisory-270.html
This is not upstream yet.
OXT-1421
This is on top of https://github.com/OpenXT/xenclient-oe/pull/1032. Once that is merged, it is just a single commit.
> STABLE-8: OXT-1421: XSA-270 Linux netback driver OOB access in hash handling 

- recipes-openxt/xenclient/xenclient-uivm-xsessionconfig/xinitrc
Not sure why that changes anything, but this is what xfce does by default,
and it ensures terminals always spawn in the foreground.
(cherry picked from commit 267e9ae703e81e12ee6c3d2ccc84d8eea1e0b668)
> STABLE-8: xfwm: start as daemon instead of background

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/xc-installer-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/system/xc-installer.if
This reverts commit 4f29bf573e588e42e95f03fd9033c1306f730329.
With the ESP not being mounted in seal-system, this permission is no
longer needed.
OXT-1397
> OXT-1397: Revert "refpolicy-mcs: Allow installer part2 to mount ESP."

- recipes-core/ovmf/ovmf/0003-BaseTools-makefile-adjust-to-build-in-under-bitbake.patch
- recipes-core/ovmf/ovmf_git.bbappend
- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-extended/xen/files/libxl-RFC-6of7-Build-the-domain-with-a-Linux-based-stubdomain.patch
- recipes-extended/xen/files/libxl-openxt-tweaks.patch
- recipes-extended/xen/xen-common.inc
Build and install OVMF to support UEFI mode in guests. The OVMF version produced from the upstream openembedded recipe doesn't work with Xen. The version of OVMF tagged by Xen doesn't support recent versions of Windows 10. Because of this we pick a recent revision of OVMF from upstream that is known to work (same revision is picked by Debian buster).
Guest UEFI mode has been tested with Debian Stretch and various version of Windows 10. Booting Windows 10 installer with OVMF may take several minutes during which only the "TianoCore" splash screen is displayed but afterwards Windows installs and boots without any issues.
> OXT-1431: Guest UEFI support

- recipes-openxt/xenclient/xenclient-idl_git.bb
xenclient-idl lacked a version since it was a git recipe, so bitbake
assigned it version git-r0.  When idl.git changed, dependency tracking
was thrown off since the version remained the same.  This would break
rebuilds of dependant packages since their sysroots would not be updated
with the newer version.
Set PV so the recipe is versioned and dependencies can be tracked.
OXT-1436
> OXT-1436: xenclient-idl: Add recipe version

- recipes-extended/xen/files/libxl-atapi-pt.patch
- recipes-extended/xen/files/libxl-crypto-key-dir.patch
- recipes-extended/xen/files/libxl-display-manager-support.patch
- recipes-extended/xen/files/libxl-linux-stubdom-replace-disk-with-initramfs.patch
- recipes-extended/xen/files/libxl-move-extra-qemu-args-to-the-end.patch
- recipes-extended/xen/files/libxl-openxt-helpers.patch
- recipes-extended/xen/files/libxl-openxt-qemu-args.patch
- recipes-extended/xen/files/libxl-openxt-tweaks.patch
- recipes-extended/xen/files/libxl-stubdom-options.patch
- recipes-extended/xen/files/libxl-support-hvm-readonly-disks.patch
- recipes-extended/xen/files/libxl-vwif-support.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
- recipes-openxt/qemu-dm/qemu-dm-stubdom_2.12.0.bb
There are some unneccesary changes to tools/libxl/libxl_dm.c. This removes them.  We only use qemu-xen, so we don't need to touch libxl__build_device_model_args_old used by qemu-traditional.
> OXT-1441: libxl patch cleanup

- recipes-core/images/xenclient-syncvm-image.bb
The syncvm image is read-only, so specify that.  Most visibly, this
removes a bunch of warnings about populating the udev cache when the
rootfs is read-only.
> syncvm: Specify read-only-rootfs IMAGE_FEATURES

- recipes-openxt/xctools/heimdallr_git.bb
- recipes-openxt/xenclient/dbd_git.bb
- recipes-openxt/xenclient/uid_git.bb
- recipes-openxt/xenclient/xenclient-rpcgen_git.bb
We have some git bitbake recipes missing a PV definition.  Without PV, the packages are versioned as "git-r0" and will not change if the git revision changes.  Bitbake cannot properly track dependencies to those packages. and dependent packages may fail to rebuild.
This PR only changes the 4 recipes included in my builds.
recipes-openxt/xctools/heimdallr_git.bb
recipes-openxt/xenclient/xenclient-rpcgen_git.bb
recipes-openxt/xenclient/uid_git.bb
recipes-openxt/xenclient/dbd_git.bb
OVMF is also missing a PV definition, but we only append that one.  It would unconventional to set PV in the bbappend; upstream should be fixed.
recipes-core/ovmf/ovmf_git.bbappend
Other recipes missing PV include:
recipes-devtools/bats/bats_git.bb
recipes-openxt/bats-testsuite/bats-testsuite_git.bb …
> Set PV variable

- recipes-devtools/e2fsprogs/patches/misc_create_inode.c-label_rootfs.patch
- recipes-security/selinux/libsemanage_2.7.bbappend
- Remove changes pushed upstream.
- `meta-selinux` does not maintain a pyro branch, but we do. Latest meta-selinux e2fsprogs patch-queue does not apply on pyro version, we may still used the previous patch version.
> STABLE-8: OXT-1428, OXT-1429, OXT-1430: Upgrade meta-selinux tracked revision.

- recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
- recipes-openxt/openxt/openxt-measuredlaunch/seal-system
- recipes-openxt/openxt/openxt-measuredlaunch/seal-system.conf
- recipes-openxt/openxt/openxt-measuredlaunch_1.0.bb
- recipes-openxt/tboot/tboot-1.9.6/0015-pcr-calc-Add-pcr-calculator-tool.patch
As it happens, TBoot added MLE header bit9, changing `EVTYPE_OSSINITDATA_CAP_HASH(0x40f)` calculated from that structure by the SINIT. Since `pcr-calc` currently relies on the values in the event-log of the running instance, this breaks forward-sealing to new version of TBoot.
Add option "-e event-type:hash" to override all event-type found in the existing event log with the provided hash before calculating the PCR values.
Add `/etc/openxt/seal-system.conf` configuration file, read by the `seal-system` script and used to define `FWS_EVTLOG_OVERRIDE`. `FWS_EVTLOG_OVERRIDE` allows to define a space-separated list of `event-type:hash` pairs to pass to `pcr-calc`.
Since `seal-system` is called from a chroot of the dom0 image to upgrade to, this file can be amended in later releases, should …
> OXT-1438: Allow pcr-calc to handle event-log overrides to forward-seal successfully

- recipes-extended/xen/xen-version.inc
Bump tracked version to latest micro-release.
No change to the patch-queue.
Xen log from original tracked revision:
```
062052a149 update Xen version to 4.9.3
ca65ce2b52 x86: assorted array_index_nospec() insertions
792130b9d2 VT-d/dmar: iommu mem leak fix
a6100f3ede rangeset: make inquiry functions tolerate NULL inputs
09cdeaeb60 x86/setup: Avoid OoB E820 lookup when calculating the L1TF safe address
e9192cd9ac x86/hvm/ioreq: MMIO range checking completely ignores direction flag
1f399b907f x86/vlapic: Bugfixes and improvements to vlapic_{read,write}()
5bb24b2792 x86/vmx: Avoid hitting BUG_ON() after EPTP-related domain_crash()
```
> STABLE-8: OXT-1448: xen: upgrade to 4.9.3

- recipes-openxt/tboot/tboot-1.9.6/0023-tboot-Unmask-NMI-potentially-masked-during-SENTER.patch
- recipes-openxt/tboot/tboot_1.9.6.bb
At boot time, [Xen 4.11 patches alternatives in NMI context](https://github.com/xen-project/xen/commit/5191c1ef51) to avoid
NMI or MCE happening while altering their code path. If the self-NMI has
been masked during an SENTER (and apparently it is in some cases), Xen
will panic() with:
"Timed out waiting for alternatives self-NMI to hit"
Patch TBoot to unmask NMI that may have been masked during SENTER.
Remove the reverted change introducing patching in NMI context from the
Xen patch-queue.
Thanks to Ross Philipson at Oracle for his detailed explanations on how
to solve this.
> OXT-1446: tboot: Unmask NMI for Xen 4.11 patching.

- recipes-kernel/linux/4.14/patches/blktap2.patch
`blktap_request_bounce()` sanity check on the request's page translation
result should not include the sg->offset.
Make the indentation compliant with kernel guidelines.
> blktap: Amend sanity check.

- recipes-kernel/linux/4.14/patches/blktap2.patch
blktap_request_bounce() sanity check on the request's page translation
result should not include the sg->offset.
Make the indentation compliant with kernel guidelines.
(cherry picked from commit de97de9207d0973713aed4f95b6f586a8c610fce)
> STABLE-8: blktap: Amend sanity check.

- recipes-openxt/xenclient/xenclient-dom0-tweaks/openxt.cfg
This should be considered a work-around for now, until further discussion.
- Another way to do this would be to pass the microcode module through the xenmbi structure. It seems hackish to me as it adds to the existing Xen interfaces to handle the microcode and the microcode is always the last module in this case.
- Yet another possibility would be to load the microcode in the first Xen instance, but then TBoot will not measure the loaded microcode.
- This change just instruct the later Xen to find it in the last module using the cmdline argument.
During UEFI/TBoot boostrap, xen.efi will fetch the microcode using the
openxt.cfg configuration file and write the binary blob in the last MBI
[module](https://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=xen/arch/x86/efi/efi-boot.h;h=5789d2cb70726a …
> OXT-1452: uefi/tboot: Load microcode from MBI2 modules.

- conf/distro/openxt-main.conf
packagegroup-base creates a subpackage packagegroup-base-nfs when nfs is
set in DISTRO_FEATURES.  This installs and runs rpcbind in all the
OpenXT images since nfs is set in DISTRO_FEATURES_DEFAULT.
Drop nfs from DISTRO_FEATURES to omit rpcbind from the images.
> openxt-main: Remove nfs from DISTRO_FEATURES

- recipes-graphics/xorg-xserver/xserver-xf86-config/xenclient-uivm/xorg.conf
- recipes-graphics/xorg-xserver/xserver-xf86-config_0.%.bbappend
- DontVTSwitch:
Disable switch to another "virtual terminal" (Ctrl+Alt+Fn) which can
trigger graphic glitches with xenfb2.
- DontZap:
Disable XKB action terminating X session (Ctrl+Alt+Backspace).
- BlankTime:
Set inactivity timeout before blanking the screen, 0 disables the
phase. This restore past behavior.
- Device/ShadowFB:
Enable ShadowFB explicitely. It is by default, but left in place as
it appears to slow down UIVM significantly when disabled.
~- DPMS is not implemented for fbdev, so remove the `StandbyTime`, `SuspendTime`, `OffTime`.~
Actually it is enforced with the fbdev patch... So add back the values to avoid the blanking.
- AutoAddDevices defaults to on and removes the need to set `InputDevice` sections in the configuration based on absolute paths (`/dev/input/eventX`).
- …
> OXT-1463: xorg: Partially restore former configuration.

- recipes-core/images/xenclient-initramfs-image.bb
- recipes-core/initrdscripts/initramfs-framework/bootfs
- recipes-core/initrdscripts/initramfs-framework/lvm
- recipes-core/initrdscripts/initramfs-framework/selinux
- recipes-core/initrdscripts/initramfs-framework/tpm
- recipes-core/initrdscripts/initramfs-framework/tpm2
- recipes-core/initrdscripts/initramfs-framework_%.bbappend
- recipes-openxt/xenclient/xenclient-dom0-tweaks/grub.cfg
- recipes-openxt/xenclient/xenclient-dom0-tweaks/openxt.cfg
Refactor openxt's custom initramfs init script into modules for OE's initramfs-framework init. As a result adjust grub.cfg to use 'runlevel=' to pass the runlevel to the new init system. Finally move xenclient-initramfs-image to use the new init.
OXT-580
> OXT-580: Initramfs framework

- recipes-connectivity/openssh/openssh_7.%.bbappend
The first change makes openssh-sshd-tcp-init get packaged generically.  With it, any VM could potentially install it, and the openxt-installer will use the core2-64 openssh package.  dom0's openssh is still machine specific since it uses a machine override for the sshd_config file.
The second change just adds the RDEPENDS on libv4v to the sshd, ssh & scp sub-packages since they contain the v4v variants - sshv4v, scpv4v, & sshd-v4v.
> openssh: Packaging fixes

- classes/openxt_image_types.bbclass
The VHD size calculation was mistakenly using the wrong units.  This
meant that 2GB VHDs were being generated for our images.
ROOTFS_SIZE is in KB, so ALIGN should be 2 * 1024 for 2MB in KB.  The
TARGET_VHD_SIZE_KB was mislabeled since it is really MB which is the
unit that `vhd convert` expects.  Rename the two TARGET_VHD_SIZE*
variables so the units are clear.
Finally, correct the alignment calculation.  We want to add $ALIGN - 1
to force ROOTFS_SIZE up to the next chunk for any partially chunks.
Adding $ALIGN + 1 always forces up one chunk and potentially two.
A .disk partitioned disk image will be larger that ROOTFS_SIZE
kilobytes.  Too handle that, always read the image size of the image in
case it is a .disk.vhd.
Alternative to https://github.com/OpenXT/xenclient-oe/pull/1070
> openxt_image_types: Fix .vhd size calculation

- recipes-bsp/grub/grub-efi_2.02.bbappend
grubx64.efi is a convenience symlink to grub-efi-bootx64.efi.
Unfortunately, it can get set to grub-efi-bootia32.efi if
grub-efi-native:do_deploy runs after grub-efi.  This breaks the build
with
cp: cannot stat ‘tmp-glibc/deploy/images/openxt-installer/grubx64.efi’: No such file or directory
openxt.git build scripts will copy the actual file, so don't bother
creating a symlink.
OXT-1484
This should go in after https://github.com/OpenXT/openxt/pull/334
> grub-efi: Don't create grubx64.efi symlink

- recipes-kernel/linux/4.14/patches/usbback-base.patch
We get an error in evtchn.h because domid_t is not defined at the time
of inclusion.  include/xen/xen.h automatically includes
xen/interface/xen.h when CONFIG_DOM0 is defined.  That doesn't happen
when CONFIG_DOM0 is not set leading to the domid_t error.  Rearranging
the headers allows domid_t to be already defined when evtchn.h is
included.  interfaces.c also needs an additional include.
> linux: Fix domU build of usbback

- recipes-extended/xen/files/libxl-disable-vnc-query-when-disabled.patch
- recipes-extended/xen/files/libxl-iso-hotswap.patch
OXT-1493
linux guests (ex:Ubuntu, Debian) lock the cdrom hence requiring force eject.
fix iso hotswap associated xenstore nodes:
-> mode: should be either of 'r' or 'w', here it's 'r'
-> hotplug-status: being used by upstream blktap3 to establish
connection between frontend and backend.
> fix iso hotswap for linux guests

- recipes-bsp/grub/grub-efi_2.02.bbappend
grubx64.efi is a convenience symlink to grub-efi-bootx64.efi.
Unfortunately, it can get set to grub-efi-bootia32.efi if
grub-efi-native:do_deploy runs after grub-efi.  This breaks the build
with
cp: cannot stat ‘tmp-glibc/deploy/images/openxt-installer/grubx64.efi’: No such file or directory
openxt.git build scripts will copy the actual file, so don't bother
creating a symlink.
OXT-1484
(cherry picked from commit b06338353d9e19a38968f6147bb21cb4c1fb84fe)
> Stable-8: OXT-1484: grub-efi: Don't create grubx64.efi symlink

- recipes-graphics/xorg-app/xterm_%.bbappend
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/xfce4-keyboard-shortcuts.xml
Font resizing was broken during the pyro upgrade.  xterm was no longer
built with TrueType font support and there were no X fonts installed.
It seems like only the default X fallback font was available to xterm.
Enable TrueType fonts through xft in PACKAGECONFIG to re-enable terminal
font size changing.
I tried installing xorg-minimal-fonts, but that was actively harmful.
With that package installed, any attempt to change the font through
ctrl-right click led to xterm exiting through an abort().
The default font size is set to 10 point.
> OXT-1509: Xterm resizable TrueType fonts

- recipes-openxt/rpc-proxy/rpc-proxy/rpc-proxy.initscript
2 of the 3 rpc-proxy instances are started with runcon, since we want
each process to be in its own SELinux context.
However, runcon fails when SELinux is disabled, and rpc-proxy is not
started in that case.
Fixing this by not running runcon when SELinux is disabled.
OXT-1504
> rpc-proxy: initscript: start rpc-proxy even when SELinux is disabled.

- recipes-extended/xen/files/libxl-atapi-pt.patch
- recipes-extended/xen/files/libxl-crypto-key-dir.patch
- recipes-extended/xen/files/libxl-support-hvm-readonly-disks.patch
- recipes-extended/xen/files/libxl-vwif-support.patch
This PR fixes libxl-support-hvm-readonly-disks.patch after the 4.11 uprev for read-only IDE support.  You can see this with HVM NDVM.
It also cleans up the patch to drop the changes to COLO since we don't use or support that functionality.
> Xen 4.11 Read-only IDE fix

- recipes-core/images/xenclient-initramfs-image.bb
- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-core/packagegroups/packagegroup-xenclient-installer.bb
- recipes-security/tss2/tpm2-tools_3.1.3.bb
- recipes-security/tss2/tpm2-tss_2.0.0.bb
Noticed on a recent build:
```
WARNING: tpm2-tss-2.0.0-r0 do_package: QA Issue: tpm2-tss: Files/directories were installed but not shipped in any package:
/usr/share
/usr/share/man
/usr/share/man/man7
/usr/share/man/man3
/usr/share/man/man7/tss2-tcti-mssim.7
/usr/share/man/man7/tss2-tcti-device.7
/usr/share/man/man3/Tss2_Tcti_Mssim_Init.3
/usr/share/man/man3/Tss2_Tcti_Device_Init.3
/usr/lib/udev
/usr/lib/udev/rules.d
/usr/lib/udev/rules.d/tpm-udev.rules
```
After reading the recipes, it seems they could be simplified and brought more inline with Bitbake/OE:
- Use `tpm2-tss` `./bootstrap` script only to generate the source list for `automake`.
- Do not use `tpm2-tools` `./boostrap` script at all since it calls `autoconf` without OE configuration
- Aggregate `tpm2-tss` library packages …
> OXT-1485: Attend build warnings on TSS recipes.

- recipes-extended/xen/files/libxl-avoid-creating-unusable-cdrom-vbd-xs-nodes.patch
- recipes-extended/xen/files/libxl-blktap3-do-not-destroy-in-use-tapdevs.patch
- recipes-extended/xen/files/libxl-blktap3-iso-hotswap.patch
- recipes-extended/xen/files/libxl-do-not-destroy-in-use-tapdevs.patch
- recipes-extended/xen/files/libxl-iso-hotswap.patch
- recipes-extended/xen/files/libxl-syslog.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
* xen/xl: Fix memory fault in libxl create domain.
Triggered on 64bit dom0. Refactor `libxl-avoid-creating-unusable-cdrom-vbd-xs-nodes.patch` while at it.
* xen/xl: Refactor `tapdev_is_shared` callsites.
Multiple patches seem to have accumulated some churn, try to avoid multiple calls to `tapdev_is_shared`. It seems that it should be called in the blktap{2,3} implementations.
* xen/xl: Add pid to syslog() redirections for xl.
Amend the patches redirecting logs to `syslog()` to catch more logs from `xl`. Also add the pid of the process prepended to log lines. It can be useful to identify the daemon process.
* xen/xl: Refactor xenmgr sync for firewall rules.
Reduce the timeout spent waiting for `xenmgr` to notify `xl` through Xenstore that the V4V firewall rules are applied before starting …
> OXT-1514, OXT-1515, OXT-1516, OXT-1517: xen/xl: Misc fixes and refactoring in xl/libxl.

- classes/module-signing.bbclass
With an external signing key, do_sign_modules will fail when there are
no modules.
| DEBUG: Executing shell function do_sign_modules
| Usage: scripts/sign-file [-dp] <hash algo> <key> <x509> <module> [<dest>]
|        scripts/sign-file -s <raw sig> <hash algo> <x509> <module> [<dest>]
If there are no modules, we don't have to run sign-file.  Have xargs
skip running the command in that case.
> module-signing: Handle no module case

- recipes-extended/xen/files/libxl-RFC-fix-multiple-disks.patch
- recipes-extended/xen/files/libxl-atapi-pt.patch
- recipes-extended/xen/files/libxl-avoid-creating-unusable-cdrom-vbd-xs-nodes.patch
- recipes-extended/xen/files/libxl-blktap3-support.patch
- recipes-extended/xen/files/libxl-crypto-key-dir.patch
- recipes-extended/xen/files/libxl-disable-json-updates.patch
- recipes-extended/xen/files/libxl-fix-flr.patch
- recipes-extended/xen/files/libxl-linux-stubdom-replace-disk-with-initramfs.patch
- recipes-extended/xen/files/libxl-openxt-helpers.patch
- recipes-extended/xen/files/libxl-openxt-tweaks.patch
- recipes-extended/xen/files/libxl-stubdom-options.patch
- recipes-extended/xen/files/libxl-support-hvm-readonly-disks.patch
- recipes-extended/xen/files/libxl-vif-make-ioemu-and-stubdom-mac-addresses-configurable.patch
- recipes-extended/xen/files/libxl-vwif-support.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
OXT-1123
By  emulating qemu SATA (hdtype='ahci') disk, it is possible to
add upto 6 disks to a hvm guest (guest should support AHCI).
> ahci support: provide multiple disk support in case of stubdom

- recipes-support/lvm2/lvm2/test-for-blk-file-before-creating-dm-mapper-symlink.patch
- recipes-support/lvm2/lvm2_%.bbappend
lvm expects /dev/mapper to be populated with symlinks,
but instead it contains actual blk files.
Remove the rule that creates those symlinks.
OXT-1274
> lvm udev rules: avoid trying to create bad symlinks

- recipes-security/refpolicy/refpolicy-mcs_2.%.bbappend
Turn the global_ssp policy boolean on.  SSP - Stack Smashing Protection -
requires reading urandom to get a random cookie value.  Instead of
adding permissions to individual domains, this gives all SELinux domains
permission to read /dev/urandom.
This patch was sitting in-tree but never added to SRC_URI, so never
applied.
> refpolicy: Turn global_ssp on

- conf/distro/openxt-main.conf
- recipes-extended/rsyslog/rsyslog-conf-dom0.bb
- recipes-extended/rsyslog/rsyslog_%.bbappend
I had $(sysconfdir} - note the erroneous parenthesis - so it wasn't
expanding the CONFFILES properly.  FILES was also not getting set since
${CONFFILES}_${PN} wasn't getting expanded.  This meant
/etc/rsyslog.conf was still packaged in "rsyslog".
However, /etc/rsyslog.conf was still getting installed from
rsyslog-conf-dom0.  /etc/rsyslog.conf was marked as a CONFFILE even in
the "rsyslog" package.  So when you installed rsyslog-conf-dom0, it
would rename the original to /etc/rsyslog.conf-opkg and then install the
new conf file as /etc/rsyslog.conf.  Dom0 and installer have those extra
-opkg files hanging around.
Adding BAD_RECOMMENDATIONS to both dom0 and installer avoids the *-opkg files hanging around.
NOTE: on a dirty build, I had to do some cleanalls to get rid of linger machine …
> Fixup rsyslog.conf packaging

- recipes-core/images/xenclient-dom0-image.bb
- recipes-kernel/modules/modules-1.0/xenclient-dom0/modules
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/ml-functions
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system.conf
- recipes-openxt/txt-info-module/files/sources/Kbuild
- recipes-openxt/txt-info-module/files/sources/Makefile
- recipes-openxt/txt-info-module/files/sources/txt_info.c
- recipes-openxt/txt-info-module/txt-info-module_1.0.bb
- recipes-security/tboot/tboot-1.9.9/0006-pcr-calc-Add-pcr-calculator-tool.patch
- recipes-security/tboot/tboot.inc
Patches against TBoot are to be folded into `0006-pcr-calc-Add-pcr-calculator-tool.patch`. This is to try and help the review process.
This PR adds a couple of things to handle eventlog event 0x40f emulation to pcr-calc:
- `txt_info` is a simple platform device driver module that exposes TXT configuration registers in the sysfs. This is required to match an ACM with the current platform without accessing `/dev/mem`.
- Add `-F` option to pcr-calc to read the event-log from a file instead of the sysfs. This is intended to ease testing.
- Add `-A` and `-V` to pcr-calc to pass the path to the ACM and the version of Tboot to emulate event 0x40f. While only event 0x40f is currently implemented, the required scafolding should be there to implement others. Since `-e` already allowed to replace an …
> OXT-1506: Calculate event 0x40f in pcr-calc taking ACM capabilities into account

- classes/module-signing.bbclass
We've seen an intermittent issue where xenfb2 doesn't get signed.  The
failure isn't fatal, so it is only detected at runtime.  From the
do_install log:
INSTALL /home/build/1905/openxt/build/tmp-glibc/work/xenclient_uivm-oe-linux/xenfb2/0+gitAUTOINC+fad222619c-r0/git/linux/xenfb2.ko
/bin/sh: scripts/sign-file: Permission denied
DEPMOD  4.14.66
log.do_make_scripts shows scripts/sign-file is built.  I would guess we
have a race against another module - maybe v4v?
commit 1b18ae5 fixed a race when using a explicit key to sign modules in
do_sign_modules.  Auto-generated keys are signed by the kernel
modules_install do_install, so they would not have been covered.  It
seems do_install also needs the same lockfile to avoid a race between
do_install and do_make_scripts.
Signed-off-by: Jason …
> OXT-1523: Fix auto-generated key signing race

- recipes-core/ovmf/ovmf_git.bbappend
The OVMF binary is missing the necessary driver for the Qemu emulated NIC
Bake the necessary binary from Intel into the OVMF binary
OXT-1439
Signed-off-by: Tyler McGavran <mcgavrant@ainfosec.com>
> [OVMF PXE] Add Intel E1000 binaries to OVMF image

- recipes-support/pesign/pesign_git.bb
Last commit will not deal well with OE:
https://github.com/rhboot/pesign/commit/377da9b127b89a30ef2258bc3bfaee6565484611#diff-4500fd79f783c1b3f56209dcdb8a637dR25
pesign will fail to build with:
> | x86_64-oe-linux-gcc: error: recipe-sysroot-ar: No such file or directory
> | x86_64-oe-linux-gcc: error: libdpe.a: No such file or directory
The last pesign release 0.112 was a while ago, so fix the revision to
the last known good until fixed.
OXT-1532
> OXT-1532: pesign: Set SRCREV to last known-good build.

- recipes-extended/xen/files/tboot-xen-evtlog-support.patch
The x64 uprev was missing a key patch for xen.  With the txt_op
hypercall ifdef'd out to support building xen-firmware such as
the pv-shim, the xen/common/Kconfig needs an entry so we can
optinally set CONFIG_TXT_OP to true and enable the txt_op
hypercall.
OXT-1541
> OXT-1541: [xen] Make sure xen Kconfig uses the new TXT_OP

- recipes-extended/logrotate/logrotate_%.bbappend
Don't ship the `logrotate.status` as intended.
> logrotate: Amend recipe typos.

- recipes-extended/logrotate/logrotate_%.bbappend
Don't ship the logrotate.status as intended.
(cherry picked from commit f495a5db1addc85ad9bb77eea02b9ff227a50fee)
> STABLE-9: logrotate: Amend recipe typos.

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/ml-functions
- recipes-security/tboot/tboot-1.9.9/0006-pcr-calc-Add-pcr-calculator-tool.patch
OXT-1506 and OXT-1507 introduced non-retro compatible changes that have to be mitigated when performing OTA upgrade.
The running kernel:
1. Does not have the new entries in the sysfs to access the eventlog.
2. Does not have access to he TXT configuration registers through sysfs.
The first point is mitigated by using the previous sysfs entry, this is also useful to determine which capabilities we can expect to do the forward sealing.
The second can be worked around using txt-stat that will report the required values to find the ACM that will be loaded upon reboot into the upgraded system. `acmmatch` is modified in consequence to accept value overrides.
- https://github.com/OpenXT/xenclient-oe/pull/1116 to allow OTA upgrade, with its dependencies.
- …
> STABLE-9: OXT-1540, OXT-1507 & more: Forward sealing from OpenXT 8

- recipes-bsp/shim/files/0001-Add-KEEP_DISCARDABLE_RELOC-build-option.patch
- recipes-bsp/shim/files/0002-Make-EFI_INCLUDE-path-configurable-during-make.patch
- recipes-bsp/shim/files/0003-Add-Measure-function-to-the-shim-lock-protocol.patch
- recipes-bsp/shim/files/0004-Don-t-overwrite-LoadOptions-if-NULL.patch
- recipes-bsp/shim/files/0005-Allow-32-bit-images-for-measurement-verification-via.patch
- recipes-bsp/shim/files/0006-Don-t-measure-with-Authenticode.patch
- recipes-bsp/shim/shim_git.bb
This is a first step, which switches to the upstream head that was used for the fork.
There shouldn't be any code difference.
Next step is to upgrade to v15.
OXT-1413
> shim: switch to upstream + patchqueue

- classes/kernel-module-signing.bbclass
- classes/module-signing.bbclass
- recipes-kernel/linux/linux-openxt.inc
My first build after the 4.19 uprev, I saw do_sign_modules fail for the
linux-openxt recipe:
/home/build/openxt-master/build/tmp-glibc/work-shared/xenclient-dom0/kernel-build-artifacts/scripts/sign-file: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
sign-file's path is
build/tmp-glibc/work-shared/xenclient-dom0/kernel-build-artifacts/scripts/sign-file - note there is no version, so it is from 4.14.  And it's rpath is:
/home/build/openxt-master/build/tmp-glibc/work/xenclient_dom0-oe-linux/v4v-module/gitAUTOINC+3f8a139271-r0/recipe-sysroot-native/usr/lib:/home/build/openxt-master/build/tmp-glibc/work/xenclient_dom0-oe-linux/v4v-module/gitAUTOINC+3f8a139271-r0/recipe-sysroot-native/lib
The v4v-module temp dir has been …
> module-signing: Prefer the build-tree sign-file

- recipes-bsp/shim/files/0001-Add-KEEP_DISCARDABLE_RELOC-build-option.patch
- recipes-bsp/shim/files/0002-Make-EFI_INCLUDE-path-configurable-during-make.patch
- recipes-bsp/shim/files/0003-Add-Measure-function-to-the-shim-lock-protocol.patch
- recipes-bsp/shim/files/0004-Don-t-overwrite-LoadOptions-if-NULL.patch
- recipes-bsp/shim/files/0005-Allow-32-bit-images-for-measurement-verification-via.patch
- recipes-bsp/shim/files/0006-Don-t-measure-with-Authenticode.patch
- recipes-bsp/shim/shim_git.bb
This is a first step, which switches to the upstream head that was used for the fork.
There shouldn't be any code difference.
Next step is to upgrade to v15.
OXT-1413
(cherry picked from commit ab9c700d3a9c04c016a407f021de47eaef75dd1e)
> STABLE-9: shim: switch to upstream + patchqueue

- recipes-kernel/linux/4.19/linux-openxt_4.19.32.bb
- recipes-kernel/linux/4.19/patches/xenpv-no-tty0-as-default-console.patch
None of the PV kernels used in OpenXT rely on that, yet silencing the loglevel is not desired as the serial output is often used to debug boot issues. This change does _not_ add tty0 as a default preferred console.
> linux: Don't set tty0 as preferred console for pv.

- recipes-kernel/linux/4.19/linux-openxt_4.19.32.bb
- recipes-kernel/linux/4.19/patches/xenpv-no-tty0-as-default-console.patch
None of the PV kernels used in OpenXT rely on that, yet silencing the loglevel is not desired as the serial output is often used to debug boot issues. This change does _not_ add tty0 as a default preferred console.
(cherry picked from commit ef42a9036283da7bfab5d049df383927c9dd581d)
> STABLE-9: linux: Don't set tty0 as preferred console for pv.

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/ml-functions
- recipes-security/tboot/tboot-1.9.9/0006-pcr-calc-Add-pcr-calculator-tool.patch
OXT-1506 and OXT-1507 introduced non-retro compatible changes that have to be mitigated when performing OTA upgrade.
The running kernel:
1. Does not have the new entries in the sysfs to access the eventlog.
2. Does not have access to he TXT configuration registers through sysfs.
The first point is mitigated by using the previous sysfs entry, this is also useful to determine which capabilities we can expect to do the forward sealing.
The second can be worked around using `txt-stat` that will report the required values to find the ACM that will be loaded upon reboot into the upgraded system. `acmmatch` is modified in consequence to accept value overrides.
> OXT-1507, OXT-1540 & more: Changes to forward-sealing binaries usage.

- classes/kernel-module-signing.bbclass
- classes/module-signing.bbclass
- recipes-kernel/linux/linux-openxt.inc
On a Linux uprev, module signing can fail on a dirty build when
sign-file is called with a rpath pointing into a modules sysroot.  The
module's sysroot path will be gone, so sign-file fails to run.
/home/build/openxt-master/build/tmp-glibc/work-shared/xenclient-dom0/kernel-build-artifacts/scripts/sign-file: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
For a kernel build, we should run ${B}/scripts/sign-file.  Instead of
searching for this at runtime, use a variable to set the the SIGN_FILE
location for modules and override for a kernel build.
While doing this, move 'require classes/module-signing.bbclass' into
kernel-signing.bbclass and rename to kernel-module-signing.bbclass.
That consolidates the functionality …
> STABLE-9: module-signing: Re-work sign-file selection

- recipes-support/pesign/pesign_git.bb
Last commit will not deal well with OE:
https://github.com/rhboot/pesign/commit/377da9b127b89a30ef2258bc3bfaee6565484611#diff-4500fd79f783c1b3f56209dcdb8a637dR25
pesign will fail to build with:
> | x86_64-oe-linux-gcc: error: recipe-sysroot-ar: No such file or directory
> | x86_64-oe-linux-gcc: error: libdpe.a: No such file or directory
The last pesign release 0.112 was a while ago, so fix the revision to
the last known good until fixed.
(cherry picked from commit 88c78c8d7fa38ece25dfa25d7e761f801ce70de4)
This is required to fix stable-8 builds.
> STABLE-8: OXT-1532: Set SRCREV to last known-good build.

- recipes-extended/xen/files/tboot-measure-and-launch-from-xen-efi.patch
The multiboot header going from Xen EFI to TBOOT was missing the the MULTIBOOT2_TAG_TYPE_EFI64 tag, which is a pointer to the EFI System Table. TBOOT would fail to load the ACPI tables from EFI thereby causing a failure when going to SENTER. With this tag TBOOT now recognizes the preload as EFI and loads the proper tables including the Root System Description Table (RSDT). This resolves the UEFI+TXT boot loop on both HP's and NCS systems when going into SENTER. There are still other issues with HP systems such as incorrectly reporting PCR 1 changes when powering off.  I have not tested Intel systems such as the NUC. 
OXT-1307
> Add tag MULTIBOOT2_TAG_TYPE_EFI64 from Xen EFI to TBOOT

- recipes-extended/xen/files/tboot-measure-and-launch-from-xen-efi.patch
The multiboot header going from Xen EFI to TBOOT was missing the the MULTIBOOT2_TAG_TYPE_EFI64 tag, which is a pointer to the EFI System Table. TBOOT would fail to load the ACPI tables from EFI thereby causing a failure when going to SENTER. With this tag TBOOT now recognizes the preload as EFI and loads the proper tables including the Root System Description Table (RSDT). I have tested this on both HP and Dell computers
OXT-1307
> STABLE-9: Add tag MULTIBOOT2_TAG_TYPE_EFI64 from Xen EFI to TBOOT

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
Running seal-system as sysadm_t does not have proper permission to read
/dev/mapper/xenclient-oe.  However there is no error checking for this
case, so seal-system will continue on and forward seal to an invalid
rootfs.  If we are unable to read the rootfs, abort instead of
clobbering the current sealed blobs.
> seal-system: Exit if unable to read rootfs

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
Stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1134/commits/1a80fbebedae58c0111d3b9610850e3976cf5c90
Running seal-system as sysadm_t does not have proper permission to read
/dev/mapper/xenclient-oe.  However there is no error checking for this
case, so seal-system will continue on and forward seal to an invalid
rootfs.  If we are unable to read the rootfs, abort instead of
clobbering the current sealed blobs.
(cherry picked from commit 1a80fbebedae58c0111d3b9610850e3976cf5c90)
> STABLE-9: seal-system: Exit if unable to read rootfs

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
- recipes-openxt/xenclient-config-access/xenclient-config-access/config-access.initscript
In the unmeasured case, the platform uses get-config-key
to unlock the /config partition.  In stable-8, the uuid output
is in uppercase, and in stable-9, it's lowercase. This is a
result of a change to dmidecode's product uuid output. This
commit maintains support for upgrading from older versions
of OpenXT where the UUID is uppercase.
OXT-1547
> OXT-1547: [key-functions] Maintain backwards compat

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
- recipes-openxt/xenclient-config-access/xenclient-config-access/config-access.initscript
In the unmeasured case, the platform uses get-config-key
to unlock the /config partition.  In stable-8, the uuid output
is in uppercase, and in stable-9, it's lowercase. This is a
result of a change to dmidecode's product uuid output. This
commit maintains support for upgrading from older versions
of OpenXT where the UUID is uppercase.
OXT-1547
> STABLE-9: OXT-1547: [key-functions] Maintain backwards compat

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
Calling sha256sum on the root_dev for computing pcr15 hash
can fail to compute the correct hash if there are cached writes
hanging about. The 'direct' flag bypasses the buffer cache
to read the root dev accurately.
OXT-1583
> [seal-system] Use dd and iflag=direct

- recipes-core/images/xenclient-upgrade-compat-image.bb
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
Calling sha256sum on the root_dev for computing pcr15 hash
can fail to compute the correct hash if there are cached writes
hanging about. The 'direct' flag bypasses the buffer cache
to read the root dev accurately.
OXT-1583
> STABLE-9: OXT-1583: [seal-system] Use dd and iflag=direct

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/blktap-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/input-server-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.mount.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/statusreport-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/updatemgr-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/xc-files-interfaces.patch
The changes for xenmgr to use losetup has triggered an AVC when calling
mount on /dev/loop0p1:
audit: type=1400 audit(1556562031.429:4): avc:  denied  { read } for  pid=1200 comm="mount" name="loop0p1" dev="devtmpfs" ino=14478 scontext=system_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:device_t:s0 tclass=blk_file permissive=0
This seems to be a race with udev labeling loop0p1 to
fixed_disk_device_t, but mount succeeds anyway.
Add a dontaudit to eliminate the noise.  mount already has a few rules
to deal with device_t devtmpfs files.  There isn't an existing interface to
dontaudit device_t:blk_file, so I just open-coded it.
To minimize churn, only the mount.te portions of the refpolicy-mcs patchqueue were refreshed.  This means the patches have a combination of default …
> OXT-1538: refpolicy: Silence mount AVC

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/blktap-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/input-server-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.mount.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/statusreport-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/updatemgr-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/xc-files-interfaces.patch
Stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1149
The changes for xenmgr to use losetup has triggered an AVC when calling
mount on /dev/loop0p1:
audit: type=1400 audit(1556562031.429:4): avc: denied { read } for pid=1200 comm="mount" name="loop0p1" dev="devtmpfs" ino=14478 scontext=system_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:device_t:s0 tclass=blk_file permissive=0
This seems to be a race with udev labeling loop0p1 to
fixed_disk_device_t, but mount succeeds anyway.
Add a dontaudit to eliminate the noise. mount already has a few rules
to deal with device_t devtmpfs files. There isn't an existing interface to
dontaudit device_t:blk_file, so I just open-coded it.
To minimize churn, only the mount.te portions of the refpolicy-mcs patchqueue were …
> STABLE-9: OXT-1538: refpolicy: Silence mount AVC

- classes/openxt_image_types.bbclass
IMAGE_CMD_ext3 calls oe_mkext234fs and then our _append commands disable
future file system checks.  There is nothing ext3 specific here.
Change the _append from IMAGE_CMD to oe_mkext234fs so any of ext2, 3 & 4
are usable for VM images.
NOTE: this does not change any disk formats.  I've only tested (successfully) with some custom images and not tried converting any default openxt images.
> openxt_image_types: Support ext4 disk images

- recipes-extended/xen/files/libxl-retry-qmp-pci-add.patch
- recipes-extended/xen/xen-common.inc
Recent changes in the platform have exposed a race condition
between libxl and the stubdomain. When libxl sends the qmp command
for "device_add" to QEMU, pcifront has not yet finished setting
up the sysfs entries for the passthrough GPU. This causes QEMU
to fail to find these entries, one example is
"received an error message from QMP server: Could not open
'/sys/bus/pci/devices/0000:01:00.0/config': No such file or directory"
This patch introduces a retry loop with a short timeout to give
pcifront some time to initialize the sysfs nodes before libxl
decides to error and completely fail domain creation.
OXT-1571
> OXT-1571: [libxl] Retry on pci add failure for PT GPU

- recipes-extended/xen/files/libxl-retry-qmp-pci-add.patch
- recipes-extended/xen/xen-common.inc
Recent changes in the platform have exposed a race condition
between libxl and the stubdomain. When libxl sends the qmp command
for "device_add" to QEMU, pcifront has not yet finished setting
up the sysfs entries for the passthrough GPU. This causes QEMU
to fail to find these entries, one example is
"received an error message from QMP server: Could not open
'/sys/bus/pci/devices/0000:01:00.0/config': No such file or directory"
This patch introduces a retry loop with a short timeout to give
pcifront some time to initialize the sysfs nodes.
OXT-1571
> STABLE-9: OXT-1571: [libxl] Retry on pci add failure for PT GPU

- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
efifb devices.  This successfully shows the ncurses measurement
failure screens on boot.
OXT-1593
> OXT-1593: [init] Load i915 driver to accommodate multiple

- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
efifb devices.  This successfully shows the ncurses measurement
failure screens on boot.
OXT-1593
> STABLE-9: OXT-1593: [init] Load i915 driver to accommodate multiple

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
On fresh installation:
```
stages/Install-fresh: line 1: getenforce: not found
+ [  == Enforcing ]
```
Install-fresh will source the key-functions to setup encryption.
> OXT-1581: keymgmt: Getenforce is not in the installer.

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
- recipes-openxt/openxt-keymanagement/openxt-keymanagement_1.0.bb
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts/tpm-functions
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts_1.0.bb
This PR is groundwork for OXT-1594.  It makes `seal-system` forward seal according to /config/config.pcrs.  It does not change the pcr selection.
It is now flexible and will seal against any selection of PCRs.  If the selection set is empty, then seal-system fails (`seal-system: forward seal of key failed`) since tpm2_sealdata fails (`ERROR: Unable to run tpm2_sealdata`).  We can also drop out PCR 15 which has the rootfs measurement.  Is that too flexible?
There are also some other cleanups I noticed along the way.
> OXT-1594: Forward Seal according to /config/config.pcrs

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
On fresh installation:
> stages/Install-fresh: line 1: getenforce: not found
> + [  == Enforcing ]
Install-fresh will source the key-functions to setup encryption.
(cherry picked from commit a3b063ba917f6262cf756604487cc1a42a365cb4)
> S9: OXT-1581: keymgmt: Getenforce is not in the installer.

- classes/openxt_image_types.bbclass
This is the stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1152
IMAGE_CMD_ext3 calls oe_mkext234fs and then our _append commands disable
future file system checks.  There is nothing ext3 specific here.
Change the _append from IMAGE_CMD to oe_mkext234fs so any of ext2, 3 & 4
are usable for VM images.
(cherry picked from commit 3e8ea24b087670d489222eafda9ccd273e907d3d)
> S9: openxt_image_types: Support ext4 disk images

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
- recipes-openxt/openxt-keymanagement/openxt-keymanagement_1.0.bb
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts/tpm-functions
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts_1.0.bb
This is the stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1158
This PR is groundwork for OXT-1594. It makes seal-system forward seal according to /config/config.pcrs. It does not change the pcr selection.
It is now flexible and will seal against any selection of PCRs. If the selection set is empty, then seal-system fails (seal-system: forward seal of key failed) since tpm2_sealdata fails (ERROR: Unable to run tpm2_sealdata). We can also drop out PCR 15 which has the rootfs measurement. Is that too flexible?
There are also some other cleanups I noticed along the way.
> S9: OXT-1594: Forward Seal according to /config/config.pcrs

- recipes-kernel/linux/4.19/defconfigs/xenclient-dom0/defconfig
- recipes-kernel/linux/4.19/defconfigs/xenclient-ndvm/defconfig
- recipes-kernel/linux/4.19/defconfigs/xenclient-stubdomain/defconfig
- recipes-kernel/linux/4.19/defconfigs/xenclient-syncvm/defconfig
- recipes-kernel/linux/4.19/defconfigs/xenclient-uivm/defconfig
- recipes-kernel/linux/4.19/linux-openxt_4.19.44.bb
- recipes-kernel/linux/4.19/patches/acpi-video-delay-init.patch
- recipes-kernel/linux/4.19/patches/blktap2.patch
- recipes-kernel/linux/4.19/patches/bridge-carrier-follow-prio0.patch
- recipes-kernel/linux/4.19/patches/extra-mt-input-devices.patch
- recipes-kernel/linux/4.19/patches/pci-pt-flr.patch
- recipes-kernel/linux/4.19/patches/pci-pt-move-unaligned-resources.patch
- recipes-kernel/linux/4.19/patches/usbback-base.patch
- recipes-kernel/linux/4.19/patches/xen-txt-add-xen-txt-eventlog-module.patch
(cherry picked from commit a8bf68a8cf0a7fcc0ba387df35d23456530836c5)
OXT-1605
> [Stable-9] Uprev the Linux 4.19 kernel from 4.19.32 to 4.19.44

- recipes-core/base-files/files/fstab.early
- recipes-core/base-files/files/xenclient-dom0/fstab
- recipes-core/base-files/files/xenclient-ndvm/fstab
- recipes-core/base-files/files/xenclient-uivm/fstab
- recipes-core/base-files/files/xenclient-uivm/fstab.early
- recipes-core/initscripts/initscripts-1.0/udev-volatiles.sh
- recipes-core/initscripts/initscripts-1.0/xenclient-dom0/volatiles
- recipes-core/initscripts/initscripts-1.0/xenclient-ndvm/volatiles
- recipes-core/initscripts/initscripts-1.0/xenclient-uivm/volatiles
- recipes-core/initscripts/initscripts_1.0.bbappend
In openxt-installer and other MACHINE that do not have a specific /etc/default/volatile:
fstab.early already mounts a tmpfs on /run.
/var/lock is a symlink to /run/lock (created with populate-volatile.sh), so trying to mount a separate tmpfs on /var/lock will fail with:
> Mounting early filesystems...
> mount: mount point /var/lock is a symbolic link to nowhere
Avoid machine specific configuration.
/var/lock used to be a 1M partition, make it a symlink an simplify things.
Keeping /var/lock separated would avoid a rogue software to fill up /run in a DoS attempt, but things that have access to /var/lock probably already have access to /run (or subdirectory) in UGO perms or SELinux policy.
> OXT-1565: base-files: /var/lock -> /run/lock

- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-extended/ipxe/ipxe_%.bbappend
- recipes-extended/xen/files/hvmloader-legacy-seabios-optionroms.patch
- recipes-extended/xen/files/libxl-seabios-ipxe.patch
- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-libxl.bb
With Xen 4.12, etherboot is no longer built with hvmloader.
The expectation is to use a separate ipxe ROM and pass it along
to hvmloader via libxl. This patch completes the codepath for
seabios so that we can pass along a ROM from ipxe.bb to use
for guest pxe booting.
OXT-1627
> OXT-1627: [hvmloader] Pass ipxe ROM to hvmloader

- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-extended/ipxe/ipxe_%.bbappend
- recipes-extended/xen/files/hvmloader-legacy-seabios-optionroms.patch
- recipes-extended/xen/files/libxl-seabios-ipxe.patch
- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-libxl.bb
With Xen 4.12, etherboot is no longer built with hvmloader.
The expectation is to use a separate ipxe ROM and pass it along
to hvmloader via libxl. This patch completes the codepath for
seabios so that we can pass along a ROM from ipxe.bb to use
for guest pxe booting.
OXT-1627
> STABLE-9: OXT-1627: [hvmloader] Pass ipxe ROM to hvmloader

- recipes-extended/xen/files/memory-scrub-on-domain-shutdown.patch
- recipes-extended/xen/xen-common.inc
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/grub.cfg
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/openxt.cfg
Recent versions of Xen have reworked page scrubbing so that it
is now asynchronous, called from the idle loop. For client
virtualization, this is a concern since it is possible for Xen
to never schedule the loop to run under the correct conditions,
leaving unscrubbed pages from old domains hanging about. While
Xen will scrub pages before giving them to a new domain, this
in-between state where scrubbing is not guaranteed is a concern.
This commit reintroduces page scrubbing synchronously when a domain
is shutdown, and uses the bootscrub=1 flag to scrub pages on
platform boot.
OXT-1494
> OXT-1494: [xen] Force synchronous page scrub

- recipes-extended/xen/files/memory-scrub-on-domain-shutdown.patch
- recipes-extended/xen/xen-common.inc
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/grub.cfg
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/openxt.cfg
Recent versions of Xen have reworked page scrubbing so that it
is now asynchronous, called from the idle loop. For client
virtualization, this is a concern since it is possible for Xen
to never schedule the loop to run under the correct conditions,
leaving unscrubbed pages from old domains hanging about. While
Xen will scrub pages before giving them to a new domain, this
in-between state where scrubbing is not guaranteed is a concern.
This commit reintroduces page scrubbing synchronously when a domain
is shutdown, and uses the bootscrub=1 flag to scrub pages on
platform boot.
OXT-1494
(cherry picked from commit 58c4ab989f6d457c6a195276d5621840a07a15c0)
> STABLE-9: OXT-1494: [xen] Force synchronous page scrub

- recipes-core/base-files/files/fstab.early
- recipes-core/base-files/files/xenclient-dom0/fstab
- recipes-core/base-files/files/xenclient-ndvm/fstab
- recipes-core/base-files/files/xenclient-uivm/fstab
- recipes-core/base-files/files/xenclient-uivm/fstab.early
- recipes-core/initscripts/initscripts-1.0/udev-volatiles.sh
- recipes-core/initscripts/initscripts-1.0/xenclient-dom0/volatiles
- recipes-core/initscripts/initscripts-1.0/xenclient-ndvm/volatiles
- recipes-core/initscripts/initscripts-1.0/xenclient-uivm/volatiles
- recipes-core/initscripts/initscripts_1.0.bbappend
In openxt-installer and other MACHINE that do not have a specific /etc/default/volatile:
fstab.early already mounts a tmpfs on /run.
/var/lock is a symlink to /run/lock (created with populate-volatile.sh), so trying to mount a separate tmpfs on /var/lock will fail with:
> Mounting early filesystems...
> mount: mount point /var/lock is a symbolic link to nowhere
Avoid machine specific configuration.
/var/lock used to be a 1M partition, make it a symlink an simplify things.
Keeping /var/lock separated would avoid a rogue software to fill up /run in a DoS attempt, but things that have access to /var/lock probably already have access to /run (or subdirectory) in UGO perms or SELinux policy.
Master PR: https://github.com/OpenXT/xenclient-oe/pull/1142
> S9: OXT-1565: base-files: /var/lock -> /run/lock

- recipes-extended/xen/files/libxl-disable-json-updates.patch
- recipes-extended/xen/files/libxl-disable-vnc-query-when-disabled.patch
- recipes-extended/xen/files/libxl-fix-flr.patch
- recipes-extended/xen/files/libxl-iso-hotswap.patch
- recipes-extended/xen/files/libxl-openxt-helpers.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
OXT-1623
This check was missed when upgrading from xen-4.11
Signed-off-by: Mahantesh Salimath <salimathm@ainfosec.com>
> S9: OXT-1623: libxl: add back stubdom check for helper kill

- recipes-core/ovmf/ovmf_git.bbappend
The mirror URL points to the latest version:
- 24.1 released on 6/27/2019.
The `sha256sum` appended to this recipe was for version:
- 23.5.2 released on 2/6/2019.
> OXT-1633: ovmf: Amend sha256sum for PREBOOT.EXE 24.1

- recipes-core/ovmf/ovmf_git.bbappend
The mirror URL points to the latest version:
- 24.1 released on 6/27/2019.
The `sha256sum` appended to this recipe was for version:
- 23.5.2 released on 2/6/2019.
> S9: OXT-1633: ovmf: Amend sha256sum for PREBOOT.EXE 24.1

- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/xinitrc
XDG_RUNTIME_DIR is a standard enironment variable that software expects
to be set.  Set it, export it, and create the underlying directory.
More info can be found here:
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
This silences the uim_helper_get_pathname messages from surf in uivm:
VM uivm (3): uim_helper_get_pathname() failed
libuim tries to mkdir(/root/.uim.d/socket), but /root is not writable.
It failes, printing the message.  With XDG_RUNTIME_DIR set, it can
mkdir($XDG_RUNTIME_DIR/uim/socket) which avoids the message.
OXT-1562
> OXT-1562: xinitrc: Create & export XDG_RUNTIME_DIR

- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/xinitrc
This is the stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1201
XDG_RUNTIME_DIR is a standard enironment variable that software expects
to be set.  Set it, export it, and create the underlying directory.
More info can be found here:
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
This silences the uim_helper_get_pathname messages from surf in uivm:
VM uivm (3): uim_helper_get_pathname() failed
libuim tries to mkdir(/root/.uim.d/socket), but /root is not writable.
It failes, printing the message.  With XDG_RUNTIME_DIR set, it can
mkdir($XDG_RUNTIME_DIR/uim/socket) which avoids the message.
OXT-1562
(cherry picked from commit 3d7758679ae382a91aefbd6621511dfd41272573)
> S9: OXT-1562: xinitrc: Create & export XDG_RUNTIME_DIR

- recipes-support/libnl/libnl/revert-rtnl-link-change.patch
- recipes-support/libnl/libnl_3.2.29.bbappend
OXT-1636
Unchecking the Enable Networking button under Network icon is broken.
With the network disabled, guests (with wired networking) are still able to access the internet.
This is essentially because NetworkManager fails to bring the brbridged interface down.
NetworkManager uses libnl to bring an interface up or down, in case of bringing brbridged down,
libnl gives an error (-NLE_OPNOTSUPP) of operation not supported.
In stable-7 branch this feature is working. libnl version in stable-7 is 3.2.25
The current version is 3.2.29. The change that is causing this issue is the first argument
that is passed to the function build_link_msg(), it used to be RTM_NEWLINK, now for brbridged
it is essentially RTM_SETLINK. This PR reverts this change to fix our issue.
Looking at the description for …
> S9 : OXT-1636 : libnl : fix disabling of network

- recipes-core/base-files/files/xenclient-syncvm/fstab
- recipes-core/base-files/files/xenclient-syncvm/fstab.early
- recipes-core/images/xenclient-syncvm-image.bb
- recipes-openxt/libicbinn/pyicbinn_git.bb
- recipes-openxt/xenclient-syncvm-tweaks/xenclient-syncvm-tweaks-1.0/network-config.initscript
- recipes-openxt/xenclient-syncvm-tweaks/xenclient-syncvm-tweaks-1.0/volatiles
The syncvm image is a little broken.  This PR provides some fixes.
syncvm was using the default SELinux fstab.early, but syncvm doesn't run SELinux.  Additionally, the regular fstab was incorrect.  Fix up both of those.  One symptom was sshd failed to start, so you couldn't sshv4v in.
We also have some fixes for setting up volatiles.
sync-client wasn't running since pyicbinn couldn't import importlib.  Fix that dependency.
> SyncVM fixes

- recipes-core/base-files/files/xenclient-syncvm/fstab
- recipes-core/base-files/files/xenclient-syncvm/fstab.early
- recipes-core/images/xenclient-syncvm-image.bb
- recipes-openxt/libicbinn/pyicbinn_git.bb
- recipes-openxt/xenclient-syncvm-tweaks/xenclient-syncvm-tweaks-1.0/network-config.initscript
- recipes-openxt/xenclient-syncvm-tweaks/xenclient-syncvm-tweaks-1.0/volatiles
This is the stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1195
The syncvm image is a little broken. This PR provides some fixes.
syncvm was using the default SELinux fstab.early, but syncvm doesn't run SELinux. Additionally, the regular fstab was incorrect. Fix up both of those. One symptom was sshd failed to start, so you couldn't sshv4v in.
We also have some fixes for setting up volatiles.
sync-client wasn't running since pyicbinn couldn't import importlib. Fix that dependency.
> S9: SyncVM fixes

- recipes-extended/libtirpc/libtirpc_1.1.4.bb
With pyicbinn linked with -Bsymbolic, sync-client segfaulted with:
VM syncvm (5): [ 18.669233] python[555]: segfault at 0 ip 0000000000000000 sp 00007ffe5a6c1328 error 14 in python2.7[400000+1000]
VM syncvm (5): [ 18.669247] Code: Bad RIP value.
Upreving libtirpc to 1.1.4 avoids the segfault.
> S9: OXT-1628: Uprev libtirpc to 1.1.4

- recipes-support/console-setup/console-setup-ckbcomp-native_1.192.bb
The debian ftp mirror no longer hosts the 1.188 tarball, so
update to the 1.192 version which is present instead.
> OXT-1645: console-setup: uprev to 1.192; fixes build

- recipes-support/console-setup/console-setup-ckbcomp-native_1.192.bb
The debian ftp mirror no longer hosts the 1.188 tarball, so
update to the 1.192 version which is present instead.
(cherry picked from commit ba0b88f4cc73b5f72e51ce8d47d6a97b20d110bc)
> STABLE-9: OXT-1645: console-setup: uprev to 1.192; fixes build

- recipes-openxt/txt-info-module/files/sources/Kbuild
Remove meaningless statement (copy-paste/replace) in KBuild.
> txt-info: Remove useless statement in KBuild

- recipes-core/eudev/eudev/disable-cdrom-lock.patch
- recipes-core/eudev/eudev_%.bbappend
OXT-1577
Currently udev locks the cdrom device and on pressing the physical eject button the cd-tray doesn't open. Typically udev should recieve an event (DISK_EJECT_REQUEST) on pressing the physical eject button, but in OpenXT it doesn't. The only way now to fix this is to not lock the cdrom device.
cdrom_id is used by udev to get device information and capabilities, this info is used to create symlinks like /dev/cdrom or /dev/dvd. Also, cdrom_id is used to lock the device. This PR removes the argument to lock the device. Locking was basically done to recieve DISK_EJECT_REQUEST event, as this event is not getting triggered there is no use of locking.
Note: If mounted, care should be taken to unmount the device before pressing eject button.
Signed-off-by: Mahantesh Salimath …
> OXT-1577: udev: fix cdrom eject by disabling locking of cdrom devices

- recipes-core/eudev/eudev/disable-cdrom-lock.patch
- recipes-core/eudev/eudev_%.bbappend
OXT-1577
Currently udev locks the cdrom device and on pressing the physical eject button the cd-tray doesn't open. Typically udev should recieve an event (DISK_EJECT_REQUEST) on pressing the physical eject button, but in OpenXT it doesn't. The only way now to fix this is to not lock the cdrom device.
cdrom_id is used by udev to get device information and capabilities, this info is used to create symlinks like /dev/cdrom or /dev/dvd. Also, cdrom_id is used to lock the device. This PR removes the argument to lock the device. Locking was basically done to recieve DISK_EJECT_REQUEST event, as this event is not getting triggered there is no use of locking.
Note: If mounted, care should be taken to unmount the device before pressing eject button.
Signed-off-by: Mahantesh Salimath …
> S9: OXT-1577: udev: fix cdrom eject by disabling locking of cdrom devices

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/ml-functions
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/grub.cfg
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/openxt.cfg
OpenEmbedded classes and recipes follow the convention that an image's
init image is called initrd when built into the image. In order to
better use OpenEmbedded's existing tooling it is helpful to follow then
naming convention of the init image.
This is a cross cutting change that must be made in a single commit. As
a result this make the appropriate changes across the supporting files
for both openxt-measuredlaunch and xenclient-dom0-tweaks.
This is tied to OpenXT/installer#114
> cross recipe: renaming initramfs.gz to initrd

- recipes-extended/xen/xen-version.inc
The commit tracked in `stable-4.12` is post `4.12.0` and is referenced as `4.12.1-pre`. Reflect that on the recipe version number.
> xen: Amend version number.

- recipes-openxt/libargo/files/13-argo.rules
- recipes-openxt/libargo/libargo_git.bb
Stop calling restorecon on the /dev/argo_{dgram,stream} device nodes.
udev already labels the devices properly when they are created, so
restorecon is unnecessary.
This means uivm won't call have
udevd[99]: failed to execute '/sbin/restorecon' '/sbin/restorecon /dev/v4v_stream': No such file or directory
udevd[99]: failed to execute '/sbin/restorecon' '/sbin/restorecon /dev/v4v_dgram': No such file or directory
OXT-1535
> libargo: Don't call restorecon from udev

- recipes-core/initscripts/initscripts-1.0/udev-volatiles.sh
I just saw "SELinux `/sbin/restorecon' tool is missing." in the uivm
logs.  It is indeed missing since uivm doesn't run SELinux.  This means
udev-volatiles bailed early without creating /run/lock.
/etc/init.d/functions already has a restore() function to only call
restorecon when it is present.  Switch to using that instead of bailing
early from the script.
> udev-volatiles: Conditionally call restorecon

- recipes-core/images/xenclient-syncvm-image.bb
- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
- recipes-extended/xen/blktap3.bb
sycnvm included finish.sh, rmnologin.sh & tapback-daemon initscripts - all of which are unneeded.
finish.sh & rmnologin.sh are just removed.
For tapback, we can create a new subpackage out of blktap3 containing tapback and the initscript (renamed from tapback-daemon to just tapback).  This new package must be installed in dom0 to keep things working.  This means tapback is no longer installed in syncvm or the installer.
> Initscript cleanup

- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/admin/vhdutils.te
vhd-util, provided by blktap3, logs to syslog using UNIX/DGRAM socket.
The log now reported is:
```
vhd-util: vhd_util_read_key: using keyfile /config/platform-crypto-keys/ea4f1606-cb49-4788-861f-a68a1168e1ff,aes-xts-plain,512.key, Size (bytes) 64
```
Additional logs is added if `vhd-util` fails.
> OXT-1670: refpolicy: Let vhd-util log to syslog.

- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/admin/vhdutils.te
vhd-util, provided by blktap3, logs to syslog using UNIX/DGRAM socket.
The log now reported is:
```
vhd-util: vhd_util_read_key: using keyfile /config/platform-crypto-keys/ea4f1606-cb49-4788-861f-a68a1168e1ff,aes-xts-plain,512.key, Size (bytes) 64
```
Additional logs is added if `vhd-util` fails.
> S9: OXT-1670: refpolicy: Let vhd-util create UNIX/DGRAM sockets.

- recipes-support/console-setup/console-setup-ckbcomp-native_1.191.bb
Instead of tarballs from the Debian package repository,
which changes every Debian release.
OXT-1645
> console-setup: switch to fetching from the git repository

- recipes-support/console-setup/console-setup-ckbcomp-native_1.191.bb
Instead of tarballs from the Debian package repository,
which changes every Debian release.
Also, switch back to version 1.191.
OXT-1645
(cherry picked from commit 17def59b26d9936bc494584ac012d4b6ebcbeaf4)
> S9: console-setup: switch to fetching from the git repository

- recipes-core/ovmf/ovmf_git.bbappend
> ovmf: update PREBOOT.EXE shasum to match latest version

- recipes-core/ovmf/ovmf_git.bbappend
> S9: ovmf: update PREBOOT.EXE shasum to match latest version

- recipes-extended/xen/files/libxl-blktap3-support.patch
- recipes-extended/xen/files/libxl-iso-hotswap.patch
- recipes-extended/xen/files/libxl-vwif-support.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
- recipes-openxt/xenclient-toolstack/xenclient-toolstack/xenclient-dom0/vif
- recipes-openxt/xenclient-toolstack/xenclient-toolstack/xenclient-ndvm/vif
- recipes-openxt/xenclient-toolstack/xenclient-toolstack/xenclient-nilfvm/vif
Upstream xen lets the xen hotplug scripts write the xenstore hotplug-status node.  I believe the idea is that the node is only written connected once the device is actually hooked up in the backend.  For instance, a vif is only connected once attached to a bridge.
Moving the write of hotplug-status out of libxl removes a little bit of our libxl patch queue.
Goes along with https://github.com/OpenXT/toolstack/pull/37
> Move writing hotplug-status from libxl to xen hotplug scripts

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.modutils.diff
upstream already fixes this:
https://github.com/SELinuxProject/refpolicy/commit/05cd55fb515bf282c61bcd3fb8637a663955f28f#diff-ace9bc8479c90380ba33eaaed3dfc997R105
```
denied  { search } for  pid=332 comm="modprobe" name="events" dev="tracefs" ino=1041 scontext=system_u:system_r:kmod_t:s0 tcontext=system_u:object_r:tracefs_t:s0 tclass=dir permissive=1
```
> OXT-1429: refpolicy-mcs: Let modutils search tracefs.

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.modutils.diff
upstream already fixes this:
https://github.com/SELinuxProject/refpolicy/commit/05cd55fb515bf282c61bcd3fb8637a663955f28f#diff-ace9bc8479c90380ba33eaaed3dfc997R105
```
denied  { search } for  pid=332 comm="modprobe" name="events" dev="tracefs" ino=1041 scontext=system_u:system_r:kmod_t:s0 tcontext=system_u:object_r:tracefs_t:s0 tclass=dir permissive=1
```
> S9: OXT-1429: refpolicy-mcs: Let modutils search tracefs.

- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
qemu can go into an infinite loop if it tries to send a message bigger than the destination's ring size or available space.  argo_send() returns EMSGSIZE & argo_chr_write() returns 0.  The chardev code thinks nothing was sent, so it calls back into argo_chr_write() and the process repeats with no progress made.  Change argo_chr_write() to scale back the write size when receiving EMSGSIZE.
Also use the Xen provided define to check for invalid domids.
> qemu chardev-argo fixes

- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
argo can return EMSGSIZE when a messages is too big to fit in the
destination ring.  In current code, QEMU will enter an infinite loop and
spam the log.  argo_send returns -1, and then argo_chr_write writes an
error message and returns 0.  The 0 return makes QEMU think there is
still len bytes to send.  Some code paths may just drop the message, but
for the QMP monitor, it will try to resend in a loop without making
progress.
The new code will try backing off the write size until a single
argo_send() succeeds.  Calling argo_send with write_len == 0 is avoided
since that will return zero.  Instead -1 is returned with -EMSGSIZE
which will be returned to the called.  In that case, the monitor code
will drop the message.
While space could become available, we don't know when.  Returning an …
> S9: qemu chardev-argo fixes

- recipes-core/images/xenclient-initramfs-image.bb
- recipes-core/initrdscripts/initramfs-framework/functions
- recipes-core/initrdscripts/initramfs-framework_%.bbappend
This PR introduces a functions module which provides a `break` function to interrupt module processing as well a `log` function to send log messages to the kernel log buffer so they can be written to disk stored logs.
> Introduce initramfs-framework functions module

- recipes-openxt/openxt-keymanagement/openxt-keymanagement/key-functions
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/ml-functions
- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts/pcr1-fix.sh
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts/tpm-functions
Remove code duplication between the different scripts used to perform sealing/unsealing operations by implementing common behaviors in `xenclient-tpm-scripts` and using the existing `tpm-functions` files in dependent scripts. Duplicate implementations were starting to drift apart (OXT-1665, OXT-1666).
Helper introduced in `tpm-functions`:
- tpm_get_syspath: print sysfs path to TPM device.
- tpm_get_ev_separator: print EV_SEPARATOR value.
- tpm_list_pcrs: list PCR values (1.2 && 2.0)
- tpm_pcrlist_save: Sanity check and save PCR id to file.
- tpm_pcrs_to_opts: Convert list of PCR ids to list of options suitable to use with TSS tools.
- tpm_pcr_value_normalize: Normalize PCR values across TSS version.
- tpm_get_hash_algorithm: Print default hash algorithm for platform.
This also changes the …
> OXT-1664: Refactor code duplication between packages.

- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
The call to unbind vtcon1 (frame buffer device) leaves the system
without an attached console during console mode boot.  When booting into
console mode and after entering the recovery password, this means that
the old frame buffer contents (the dialog output about resealing or
continuing boot) if left as the output on the display.  The boot output
is not displayed.
Console mode output formerly worked, but it seems to have changed when
fbcon switched from a module to a kernel built-in.  There was always an
unbind, but there used to be an rmmod as well.  My guess is `rmmod
fbcon` triggered the kernel to re-attached the dummy console.  Without
the module, we just leave an unattached console.
Even when "unbound" you could blindly log in and run `echo -n 1 >
/sys/class/vtconsole/vtcon1/bind` …
> OXT-1662: init.root-ro: Leave console bound during boot

- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
This is the stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1261
The call to unbind vtcon1 (frame buffer device) leaves the system
without an attached console during console mode boot.  When booting into
console mode and after entering the recovery password, this means that
the old frame buffer contents (the dialog output about resealing or
continuing boot) if left as the output on the display.  The boot output
is not displayed.
Console mode output formerly worked, but it seems to have changed when
fbcon switched from a module to a kernel built-in.  There was always an
unbind, but there used to be an rmmod as well.  My guess is `rmmod
fbcon` triggered the kernel to re-attached the dummy console.  Without
the module, we just leave an unattached console.
Even when "unbound" …
> S9: OXT-1662: init.root-ro: Leave console bound during boot

- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/openxt.cfg
This is the stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1263
commit c11da6014c6e1fb33ec2ba951edfb69765653a69 "[efi] Turn on efi
runtime services in the kernel" reverted setting of "runlevel=3" to the
older "3" (originally done in commit
e2a14f972b9ad022633f5e4db7964a7498b5c5f9 "dom0-tweaks: change runlevel
declaration" for the initramfs-framework conversion).  This breaks
booting console mode since we don't run in init level 3, so surfman
starts and a getty isn't started.  (autostart is not set, so VM aren't
started).
Correct the runlevel setting.
(cherry picked from commit 82969ac0e3ba110cb4124a91786bf71f2e7dec3f)
> S9: Update openxt.cfg to set runlevel for UEFI boot

- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/openxt.cfg
commit c11da6014c6e1fb33ec2ba951edfb69765653a69 "[efi] Turn on efi
runtime services in the kernel" reverted setting of "runlevel=3" to the
older "3" (originally done in commit
e2a14f972b9ad022633f5e4db7964a7498b5c5f9 "dom0-tweaks: change runlevel
declaration" for the initramfs-framework conversion).  This breaks
booting console mode since we don't run in init level 3, so surfman
starts and a getty isn't started.  (autostart is not set, so VM aren't
started).
Correct the runlevel setting.
> Update openxt.cfg to set runlevel for UEFI boot

- recipes-extended/xen/files/argo-quiet-xsm-check-during-init.patch
The recent change to quiet the AVC issued when a domain does not have
XSM argo enabled unfortunately omitted a change to add initialization
logic to the dummy policy, so when running with the dummy policy active,
it results in a crash in Xen on boot.
This change adds the needed initialization.
Fixes OXT-1692.
> xen: Add missing dummy XSM init code to quiet Argo XSM check patch

- recipes-extended/xen/blktap3.bb
- recipes-extended/xen/blktap3/fix-encryption.patch
Upstream commits broke our vhd encryption implementation. The
patch header in this commit provides in-depth detail of each
problem and their proposed solution.
OXT-1688
> OXT-1688: [blktap3] Fix blktap3 vhd encryption

- recipes-extended/xen/blktap3.bb
- recipes-extended/xen/blktap3/fix-encryption.patch
Upstream commits broke our vhd encryption implementation. The
patch header in this commit provides in-depth detail of each
problem and their proposed solution.
OXT-1688
> STABLE-9: OXT-1688: [blktap3] Fix blktap3 vhd encryption

- recipes-extended/xen/files/block-vbd3
- recipes-extended/xen/files/libxl-block-scripts-log-to-syslog.patch
- recipes-extended/xen/files/volatiles.99_xen
- recipes-extended/xen/files/xen-vbd3-backend.rules
- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-libxl.bb
- recipes-extended/xen/xen.bb
- recipes-openxt/xenclient-toolstack/xenclient-toolstack_git.bb
When creating a stubdom that wants access to use a raw partition,
the custom xenclient-toolstack block scripts fail.  Using the
scripts from upstream fixes the issue.
Package the legacy udev rules separately for backwards compatibility.
Also, the patch for `xen-hotplug-common.sh` was applied to silence
selinux warnings from the custom logger and now we use syslog
OXT-1356
Signed-off-by: Tim Konick <konickt@ainfosec.com>
> libxl: Use upstream hotplug block scripts

- recipes-security/refpolicy/refpolicy-mcs-2.%/policy/modules/services/blktap.if
commit 861b0d7772012f73dcd266ce02a448f6b4e44dd0 "refpolicy-mcs: blktap
devnodes labeling" placed the blktap nodes within a xen_device_t labeled
directory.  This requires new xen_device_t permissions to actually
access the files.
Notably, non-stubdom domains can no longer start because qemu cannot
access the disk:
qemu-8: qemu-system-i386: -drive file=/dev/xen/blktap-2/tapdev9,if=none,id=ahcidisk-0,format=raw,cache=writeback: Could not open '/dev/xen/blktap-2/tapdev9': Permission denied
...
kernel:[  125.534414] audit: type=1400 audit(1569432775.150:4): avc:  denied  { search } for  pid=2872 comm="qemu-system-i38" name="blktap-2" dev="devtmpfs" ino=13085 scontext=system_u:system_r:qemu_t:s0:c236 tcontext=system_u:object_r:xen_device_t:s0 tclass=dir permissive=0
Give xen_device_t:dir search …
> refpolicy-mcs: Give dev_search_xen perms to blktap_rw_blk_file

- recipes-extended/xen/files/0001-tools-helpers-Introduce-cmp-fd-file-inode-utility.patch
- recipes-extended/xen/files/0002-Linux-locking.sh-Use-cmp-fd-file-inode-for-lock-chec.patch
- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-libxl.bb
- recipes-extended/xen/xen.bb
Add cmp-fd-file-inode tool to remove dependency on perl.
We put it in its own package and make xen-scripts-common depend on it.
We can't just include it in the xen-scripts-common package because
cmp-fd-file-inode is built in xen-lixl.bb and xen-scripts-common is
built in xen.bb.
This removes the perl dependency in https://github.com/OpenXT/xenclient-oe/pull/1255
> xen: Remove locking.sh dependency on perl

- recipes-extended/xen/blktap3/fix-run-time-errors-and-memory-leaks.patch
LIBBLOCKCRYPTO_NAME exists in vhd-util-copy.c as well as the other
places.  Update that copy as well.  Otherwise, you'll receive an error:
"failed to load crypto support library"
> blktap3: Update another LIBBLOCKCRYPTO_NAME variable

- recipes-extended/xen/blktap3/fix-run-time-errors-and-memory-leaks.patch
Stable-9 version of https://github.com/OpenXT/xenclient-oe/pull/1271
LIBBLOCKCRYPTO_NAME exists in vhd-util-copy.c as well as the other
places.  Update that copy as well.  Otherwise, you'll receive an error:
"failed to load crypto support library"
> S9: blktap3: Update another LIBBLOCKCRYPTO_NAME variable

- classes/openxt-vm-common.bbclass
Bitbake, starting with https://github.com/openembedded/bitbake/commit/0cdc5b81fc1f5e5281a525a657e420ebc3bb9e90, will throw warnings on coding style:
> python should use 4 spaces indentation
Honor the standard.
> class: Use 4-space indentation.

- classes/always_rebuild_xc_git_recipes.bbclass
This was maybe intended to have `PSTAGING_DISABLED` for OpenXT recipes (`SRC_URI` has `OPENXT_GIT_MIRROR` source). This is not used and it is not quite clear what `PSTAGING` was.
This class is not inherited anywhere, it will still be parsed by bitbake when the layer is added though. Since it is no longer used, it should be removed.
> class: Remove always_rebuild... class.

- recipes-core/ovmf/ovmf_git.bbappend
Use the currently available mirror for version 24.2.
Attend [recent build failure](http://openxt-builder.ainfosec.com:8010/#/builders/1/builds/7039) when `PREBOOT.EXE` is not in download cache yet.
> ovmf: New mirror available for PREBOOT.EXE.

- recipes-core/ovmf/ovmf_git.bbappend
Use the currently available mirror for version 24.2.
Master PR: https://github.com/OpenXT/xenclient-oe/pull/1288
> S9: ovmf: New mirror available for PREBOOT.EXE.

- recipes-core/ovmf/ovmf_git.bbappend
24.2 mirror changed again since 24.3 is provided.
Also add the md5sum of the archive, making this easier to check with the website.
This changed sometime since yesterday with 24.2 now being provided at https://downloadmirror.intel.com/29166/eng/PREBOOT.EXE.
`E3522X2.EFI` hasn't changed in the new version, this is the only file extracted from the archive.
```
7862a12529539905d4f57c94920d52b4  PREBOOT.0/APPS/EFI/EFIx64/E3522X2.EFI
```
> ovmf: Upgrade PREBOOT.EXE to 24.3.

- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
RFC since we may want to drop the debugging fprintfs, but they are useful for testing.
----
We've observed a hang where qemu is blocked in argo_send for a QMP
RTC_CHANGE event.  This seems to happen with NTP time updates on Windows
10.
qmp_helper, when not connected, sits blocked in an accept() call and
does not service its Argo connection.  That means events like the above
will fill up the argo ring.  qemu's argo socket is blocking, so when an
additional event comes in, argo_send blocks in the kernel and qemu
hangs.
We already have some connected state logic for QMP, so re-use that.
When not connected, just drop the writes.  Normal writes happen as
response to requests while a client is connected, and a client will stay
connected until it receives its response.  Events may come through …
> qemu: Avoid QMP events filling the argo ring

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/network-daemon-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.contrib.xen.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/sysutils-interfaces.diff
There are a few typos in some patches that left some leading '+' characters, likely from reject files.
For some reason, building the policy does not fail almost all of the time.
> refpolicy: Fix typos in patches.

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/network-daemon-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.contrib.xen.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/sysutils-interfaces.diff
There are a few typos in some patches that left some leading '+'
characters, likely from reject files.
For some reason, building the policy does not fail almost all of the
time.
(cherry picked from commit 4c403d0bc4bf09ee8c48c6b44c933d9d8b180e25)
> S9: refpolicy: Fix typos in patches.

- recipes-core/ovmf/ovmf_git.bbappend
New mirror provided since 24.3 release.
The E1000 driver provided in 24.3 is the same as 24.2, so there is no reason to update for now. This is the only file extracted and used by this recipe.
Adding `md5sum` for easier verification when consulting the download web-page.
> S9: ovmf: Update PREBOOT.EXE 24.2 mirror.

- recipes-core/packagegroups/packagegroup-xenclient-dom0.bb
With package dependency tracking, we shouldn't be explicitly installing
libraries.  Just install executables and let their dependencies bring in
their needed libraries.
For the dropped libraries:
xen-xl -> xen-libxenguest, xen-libxenlight, xen-libxlutil
xen-xenstat -> xen-libxenstat
surfman -> libedid
rpc-proxy -> libxchargo -> libargo
> packagegroup-dom0: Remove explicit lib depends

- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
We've observed a hang where qemu is blocked in argo_send for a QMP
RTC_CHANGE event.  This seems to happen with NTP time updates on Windows
10.
qmp_helper, when not connected, sits blocked in an accept() call and
does not service its Argo connection.  That means events like the above
will fill up the argo ring.  qemu's argo socket is blocking, so when an
additional event comes in, argo_send blocks in the kernel and qemu
hangs.
We already have some connected state logic for QMP, so re-use that.
When not connected, just drop the writes.  Normal writes happen as
response to requests while a client is connected, and a client will stay
connected until it receives its response.  Events may come through while
a client is connected or not.  With a client connected, it's up to the
client to handle …
> S9: qemu: Avoid QMP events filling the argo ring

- recipes-extended/xen/files/hvmloader-legacy-seabios-optionroms.patch
- recipes-extended/xen/files/libxl-avoid-creating-unusable-cdrom-vbd-xs-nodes.patch
- recipes-extended/xen/files/libxl-disable-json-updates.patch
- recipes-extended/xen/files/libxl-openxt-tweaks.patch
- recipes-extended/xen/files/libxl-xenmgr-support.patch
I noticed some unnecessary changes in our libxl patches which are removed in this series.
@crogers1 Is there a particular reason for changing "/local/domain/N/control" to rw perms https://github.com/OpenXT/xenclient-oe/commit/db804d91b4d16e498ef8656094ddfc403933c546#diff-83c581625019ac0b6ff2913055c602acR52?  You introduced it originally, but I don't think it's necessary.
> xen-libxl patch cleanup

- recipes-extended/qemu-dm/qemu-dm/acpi-pm-feature.patch
6dde8833f7de "xen: Remove duplicate xenstore writes" changed a domain's
control xenstore directory to read-only.  This broke stubdom qemu's
ability to write to "control/hvm-powerbutton-enable".  Without that
node, xenmgr wouldn't use the acpi shutdown paths.
Switch to writing hvm-powerbutton-enable and hvm-shutdown in the
device-model directory of qemu-dm's domain.  That is either the stubdom
or dom0.  Logically it makes sense to put this device-model information
underneath the device-model instead of the guest.  It also side steps
the permission issue.
This needs a corresponding change to xenmgr.
Goes along with https://github.com/OpenXT/manager/pull/175
> qemu-dm: acpi-pm: Use device-model xenstore directory

- recipes-extended/xen/xen-hypervisor.bb
Right now, do_compile only regenerates the .config file.  The hypervisor
is actually built in do_install since it is called implicitly as a
dependency on install.  Add an explicit call to build xen in do_compile.
> xen: Build hypevisor in do_compile

- recipes-connectivity/openssh/files/sshd_config
The zeus upgrade removed the machine-specific sshd config for dom0.
This commits brings back the relevant settings.
Those are required notably after an unattended install.
More info there:
https://github.com/OpenXT/xenclient-oe/pull/951
https://github.com/OpenXT/xenclient-oe/pull/979
> openssh: post-zeus fixup

- recipes-core/busybox/busybox_%.bbappend
- recipes-core/busybox/files/poweroff.cfg
The stubdom uses the busybox poweroff command to shutdown, but it is
currently missing.  In that case, the /init script ends and the kernel
panics instead of shutting down.  Install poweroff to restore graceful
shutdown.
> busybox: Enable poweroff command

- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/keymap-agent
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/nm-applets-agent
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/resize-agent
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/ui-functions
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/uim-toolbar-gtk-agent
Running Shellcheck reveals UIM toolbar would never display due to a typo in a variable name.
Amend the other warnings as well in a separate commit.
> uivm-agents: Amend shellcheck warnings.

- recipes-core/ovmf/ovmf_git.bbappend
The URL changed with the release of 24.5.
https://downloadcenter.intel.com/download/29334/Ethernet-Intel-Ethernet-Connections-Boot-Utility-Preboot-Images-and-EFI-Drivers
Remain on 24.3 to fix the build until someone upgrades to 24.5 and tests with the available drivers in 24.5.
> ovmf: Point SRC_URI to the correct URL.

- recipes-bsp/grub/grub-efi_2.%.bbappend
The cfg file is used by grub-mkimage to let grub know where to find its configuration.
For the iso installer, the default one pointing to the ESP for grub.cfg will not work.
> grub-efi: Amend FILESEXTRAPATH to use local cfg

- recipes-openxt/xenclient-nws/xenclient-nws_git.bb
These files are moved to the nws subdirectory.
Use OE default variables for paths.
- https://github.com/OpenXT/network/pull/18
> nws: Amend path to versioned files

- recipes-openxt/xenmgr-data/xenmgr-data_git.bb
This recipe is in bad shape.
At least fix the make invocation, the rest needs a lot more work (see
existing comment).
> xenmgr-data: Call oe_runmake not make

- recipes-openxt/xenclient-idl/xenclient-idl_git.bb
When installing the RPC .xml descriptions, they are fetched from the
sources, which should be ${S}, not ${WORKDIR}/git.
This breaks EXTERNALSRC otherwise.
> idl: Fetch files from ${S}

- classes/openxt-image-disk.bbclass
Use correct spelling for command.
OXT-1746
Signed-off-by: Rich Persaud  <rich.persaud@baesystems.com>
> OXT-1746: openxt-image: fix bbfatal typo for disk signature

- recipes-openxt/xenclient-cryptdisks/xenclient-cryptdisks/crypttab
Change swap file encryption from default cipher (plain dm-crypt) to the
cipher used for the config partition (aes-xts-plain64). Options specified
here are passed from cryptdisks.initscript to cryptsetup on each boot.
OXT-1489
Signed-off-by: Rich Persaud <rich.persaud@baesystems.com>
> OXT-1489 : cryptsetup: set parameters for swap file encryption

- recipes-security/tss2/tpm2-tss_2.0.0.bb
Fixes the OpenXT build on Devuan Beowulf with default shell.
> tpm2-tss: OXT-1689: remove bash-isms from recipe

- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts/tpm-functions
This function, on an un-owned tpm2, throws an error:
[: -eq: unary operator expected
When the tpm2 is un-owned, `grep -q` return 1.  The conditional is
skipped, and state is still "" when it gets to the inversion on the way
out of the function.  Initialize the state to 0 to avoid this issue.
The tpm1 path is fine since it always sets state.
> tpm-functions: Fix tpm_is_owned for tpm2

- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
The domid option is not current allowed since it is not listed in
qemu_chardev_opts.  qemu fails with "Invalid parameter 'domid'".
Add domid into qemu_chardev_opts so it is accepted as a option.
We also need to bind a connected ring pointed at the remote domid.
Otherwise when the remote tries to reply, it'll fail since the ring is
bound to dom0.
hypervisor: (XEN) d23v0 argo: vm23 connection refused, src (vm23:13ed) dst (vm32:3afd)
VM Windows10-dm (32): qemu-system-i386: [argo-chardrv] failed to connect argo socket - err: 111
> qemu-dm: Wire up chardev-argo domid option

- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/create-ndvm
On a system with multiple NICs, create-ndvm provisions multiple NDVMs.
Since the OpenXT default NDVM is now HVM, do the same here.
OXT-1686
Signed-off-by: Rich Persaud <rich.persaud@baesystems.com>
Requires: https://github.com/OpenXT/manager/pull/176
> OXT-1686 : create-ndvm: use HVM NDVM template

- recipes-openxt/xenclient-rpcgen/xenclient-rpcgen_git.bb
Copy files from $B an $S where appropriate.
Referencing `$WORKDIR` does not sit well with `externalsrc` and should be avoided.
> rpcgen: Fix paths in do_install

- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
VM startup is always delayed 5 seconds when libxl fails to connect to
QMP.  Logs show:
libxl_qmp.c:530:qmp_next:Domain 1:timeout
libxl_qmp.c:823:libxl__qmp_initialize:Domain 1:Failed to connect to QMP
The root cause is a mismatch between the argo chardev being connected,
but the qmp monitor still being closed.  qmp-helper defaults to open
(skipping sending "live"), argo chardev receives the message, but the
qmp monitor is disabled.  The request isn't processed and request times
out.  qmp helpers sends "dead" and the argo chardev is closed which
brings the monitor and chardev into sync.  When the next connection
comes in, argo transitions to connected and the monitor is started by
qemu_chr_be_event(chr, CHR_EVENT_OPENED).
The oneline fix is
-+    *be_opened = false;
++    *be_opened = …
> qemu: Fix initial qmp timeout issues

- recipes-extended/xen/files/kconfig-grant-table-v2-interface.patch
The patch context is now incorrect due to a change in upstream commit
46bde0561b4a6eca4deee2dc1797086353e95be9. This fixes a paren error
causing our patch to fail to apply.
> [xen] Update kconfig-grant-table patch

- recipes-extended/xen/files/ocaml-makefiles-sysroot.patch
- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-ocaml-libs.bb
- recipes-openxt/dbd/dbd_git.bb
- recipes-openxt/xenclient-toolstack/xenclient-toolstack_git.bb
- Amend quoting in xen OCaml tools build-system to pass down arguments provided through `$(CC)`.
- Use `oe_runmake` to inherit the `EXTRA_OEMAKE` definitions from `ocaml.bbclass`.
Require:
- https://github.com/OpenXT/uid/pull/4
- https://github.com/OpenXT/toolstack/pull/42
- https://github.com/OpenXT/manager/pull/178
- https://github.com/OpenXT/meta-openxt-ocaml-platform/pull/20
> S9: OXT-1787: ocaml/findlib: fix toolchain cross environment

- recipes-extended/xen/files/ocaml-makefiles-sysroot.patch
- recipes-extended/xen/xen-common.inc
- recipes-extended/xen/xen-ocaml-libs.bb
- recipes-openxt/dbd/dbd_git.bb
- Remove `ocaml-cc.sh` wrapper by quoting `$(CC)`
- `dbd` can now build with `-j`
- https://github.com/OpenXT/uid/pull/5
- https://github.com/OpenXT/toolstack/pull/43
- https://github.com/OpenXT/manager/pull/179
- https://github.com/OpenXT/meta-openxt-ocaml-platform/pull/21
> OXT-1787: ocaml/findlib: fix toolchain cross environment

- recipes-extended/xen/files/allow-stubdoms-cacheattr-control.patch
stable-4.12 received new commits.
- 1336ca1774 x86/hvm: set 'ipat' in EPT for special pages
changes the context of allow-stubdoms-cacheattr-control.patch. Refresh
the patch in consequence. The changes upstream should not affect the
changes introduced by the patch.
Fixes automatic builds.
> xen: refresh on top of stable-4.12

- recipes-openxt/dbd/dbd_git.bb
commit 3b15d672292d "dbd: Unify and rewrite recipe" changed the
packaging of db-* tools.  Previously, dbd included those tools, but now
they aren't included in dom0.  Make dbd RRECOMMENDS dbd-tools so they
are once again installed.
> dbd: make dbd RRECOMMENDS dbd-tools

- recipes-extended/qemu-dm/qemu-dm/atapi-pass-through.patch
- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
This change was pushed to master and affected https://github.com/OpenXT/linux-xen-argo.
The recipes have not been switched to track sub-project revisions yet, so `zeus` builds will break.
Given the scope of this change and since OpenXT does not maintain a versioned release in its `zeus` branch at the moment I recommend this change to be cherry-picked in `zeus`.
> xen_argo_ring_t is no longer automatically exposed to userspace via a libargo include, so don't base the ring size calculation on it; use the ARGO_RING_OVERHEAD macro for the calculation.
> char-argo.c now needs its own include of xen.h rather than relying
on transitive inclusion.
> OXT-1694: ZEUS: qemu-dm: updates following switch to dedicated Linux argo header

- classes/kernel-module-signing.bbclass
The contents of the signing key are important to knowing if sstate can
be re-used.  There have been cases where the modules and kernel keys &
signatures have gotten out of sync.  Ensure the key is added to the
sstate to make modules depend on it.
I'm put some scripts that I've used in the past to check module signatures here.  They are a little rough, but they do the job:
https://gist.github.com/jandryuk/62f18d802eb705f5ecf4ecd866318f3a
> kernel-module-signing: Add signing key to SSTATE_HASH

- classes/kernel-module-signing.bbclass
The contents of the signing key are important to knowing if sstate can
be re-used.  There have been cases where the modules and kernel keys &
signatures have gotten out of sync.  Ensure the key is added to the
sstate to make modules depend on it.
(cherry picked from commit ffaba32262d9557c6b75f08c8fd553b2cd67fb24)
> zeus: kernel-module-signing: Add signing key to SSTATE_HASH

- recipes-extended/xen/files/unmap-shared-info.patch
Refresh context following upstream change:
b402e2a14b IOMMU: hold page ref until after deferred TLB flush
Build fix.
> xen: refresh unmap-shared-info context

- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
Currently, the measured launch failure messages persist in the
framebuffer since nothing clears the framebuffer.  When shutting down,
OpenXT switches back to the framebuffer, you see the old mesage.
Use dialog to clear the screen since the messages are stale.
> init.root-ro: Clear framebuffer after unlock

- recipes-extended/xen/files/xen-translate.patch
DEBUG=y enables stricter type checking for mfn and gfn types.
xen-translate needs some fixups to correct their use.  Otherwise it will
not build under DEBUG=y.
> xen: fix xen-translate.patch under DEBUG=y

- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/openxt.cfg
console=hvc0,tty0 is incorrect.  It should be two separate console
arguments.  This fixes kernel output during a UEFI console boot.
> dom0-tweaks: Correct UEFI kernel consoles

- recipes-kernel/linux/5.4/patches/blktap2.patch
This PR addresses some hangs and locking issues with blktap.
- Starts previously stopped blk-mq queues to ensure progress.
- Fixes hangs in argo_poll with locking and better "work" determination.
- Converts from spin locks to mutex and a blocking blk-mq queue.
- Drops queue locking.
> Blktap fixes

- classes/multilib-allarch.bbclass
- recipes-connectivity/networkmanager-certs/networkmanager-certs.bb
- recipes-core/initrdscripts/initramfs-stubdomain_1.0.bb
- recipes-core/udev/udev-extraconf-dom0_1.0.bb
- recipes-devtools/bats-suite/bats-suite_git.bb
- recipes-devtools/bats/bats_git.bb
- recipes-extended/rsyslog/rsyslog-conf-dom0.bb
- recipes-kernel/linux-firmware/linux-firmware_git.bb
- recipes-openxt/argo/argo-module-headers_git.bb
- recipes-openxt/idl/xenclient-idl_git.bb
- recipes-openxt/xen-legacy-block-scripts/xen-legacy-block-scripts_1.0.bb
- recipes-openxt/xen-tap-scripts/xen-tap-scripts_1.0.bb
- recipes-openxt/xen-vif-scripts/xen-vif-scripts-dom0_1.0.bb
- recipes-openxt/xen-vif-scripts/xen-vif-scripts-ndvm_1.0.bb
- recipes-openxt/xenclient-installer/xenclient-installer_git.bb
- recipes-openxt/xenclient-repo-certs/xenclient-repo-certs_1.0.bb
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig_0.0.2.bb
- recipes-security/selinux/selinux-load_1.0.bb
- recipes-support/lvm2/lvm2-conf-initramfs_1.0.bb
commit b840fe8eff90 added multilib to the openxt-main distro, but an
unnoticed side effect was that allarch no longer worked.
allarch.bbclass doesn't set PACKAGE_ARCH to "all" when MULTILIB_VARIANTS
is set, so the rest of allarch.bbclass doesn't take effect.
Work around this by manually setting PACKAGE_ARCH="all" and then
inheriting allarch.  There could be a problem if any of these packages
depended on further arch specific packages, but none of ours do.
Wrap it into the small multilib-allarch.bbclass to centralize the
change.
> Restore allarch after addition of MULTILIB

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.fstools.diff
`/usr/sbin/tune2fs\.e2fsprogs` should be mentioned in fstools.fc to be labelled properly.
> fc/fstools: fix real path for e2fsprogs

- recipes-openxt/xctools/audio-helper_git.bb
- Add the missing `RDEPENDS` on `dbd-tools`
- Do not override ASNEEDED as Yocto will take care of it
- Comply with the recommended styleguide.
- https://github.com/OpenXT/xctools/pull/65
(this is due to `ASNEEDED = ""`, at the configuration step, libdl isn't passed in the `LDFLAGS`, this is handled in the refactored autotools by relying on libargo pkgconfig for the `LDFLAGS`)
> audio-helper: recipe minor adjustments

- recipes-extended/qemu-dm/qemu-dm/nic-link-state-propagation.patch
- recipes-extended/qemu-dm/qemu-dm/qmp-argo-char-driver.patch
Attend minor log output issues:
- missing CR after reporting a Xenstore watch has been registered
- log `errno` value should `argo_socket` fail instead of the error code.
Split from initial submission: https://github.com/OpenXT/xenclient-oe/pull/1382
> qemu: small log output improvments 

- recipes-openxt/xenclient-installer/xenclient-installer_git.bb
package the custom answerfiles provided by the layer.
When using `externalsrc` and `rmwork`, the tmpdir where the answer files are placed by `do_unpack` and used in `do_deploy`, will be wiped. This can lead to issues when the recipe used is targeting an image that needs `do_deploy` to re-run under `externalsrc`, `do_unpack` is not always re-run.
Placing the files in the package tracked by the sstate seems to resolve this issue.
> installer/answer: package custom answerfiles

- conf/machine/xenclient-dom0.conf
- conf/machine/xenclient-ndvm.conf
- recipes-openxt/txt-info-module/txt-info-module_1.0.bb
157ee22b modules: use KERNEL_MODULE_AUTOLOAD
introduced a regression where txt and txt_info end up not being loaded.
txt being in-tree, add it to the MACHINE configuration.
txt-info should be txt_info.
xen-netback is build-in, remove KERNEL_MODULE_AUTOLOAD.
> txt: amend module autoloading in dom0

- recipes-openxt/vusb/files/xenclient-vusb.initscript
The vusb initscript doesn't actually stop vusb-daemon since the
executable name is vusb-daemon, which pidof won't match with
vusb_daemon.  Fix the name string, but also consolidate on pkill which
combines the equivalent of kill & pidof.
> vusb: Fix initscript stop

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.mount.diff
If mount is seeing device_t, something is wrong - Print the avc.
After the dunfell uprev, mount may have started failing from this
permission issue when trying to extract the kernel from a partitioned
disk.  This was seen with the usbvm in PV mode.  ndvm may also show it,
but it defaults to HVM.  An xenmgr change should fix this, so drop this
dontaudit.
This reverts commit a76ead77ddbe29abd40637d2aebeddee337e27e8.
This goes along with https://github.com/OpenXT/manager/pull/183
> Revert "refpolicy: Silence mount AVC"

- recipes-connectivity/networkmanager/networkmanager-1.18.4/always-use-existing-connections.patch
- recipes-connectivity/networkmanager/networkmanager_1.18.4.bbappend
profiles. Networkmanager core logic always generates default
connection profiles for managed devices. These fail to match
any on-disk (db) saved connection profiles we may have from
a previous boot and therefore create duplicate entries,
ignoring any of the modified settings.
This patch will allow NM to try to match on existing connection
profiles during its initialization. This fixes a regression where we
are unable to save modifications to network settings across
reboots.
OXT-1816
> [networkmanager] Always use existing connection

- recipes-connectivity/networkmanager/files/db_to_nm.awk
- recipes-connectivity/networkmanager/files/nm_to_db.awk
when writing or reading a connection profile from the db.
According to networkmanager:
"When [permissions] is not empty, the connection can be active
only when one of the specified users is logged into an active session."
This commit ensures that wireless connections will automatically connect
to the SSID that is stored in the connection profile by keeping
'permissions' empty.
OXT-1817
> [networkmanager] Prune 'permissions' node

- recipes-core/images/xenclient-initramfs-image.bb
- recipes-core/initrdscripts/initramfs-framework_%.bbappend
- recipes-openxt/trousers/trousers_0.3.14.bb
- recipes-security/tpm-tools/files/tpm-tools-quote-standalone.patch
- recipes-security/tpm-tools/files/tpm-tools-standalone.patch
- recipes-security/tss2/tpm2-tools_3.1.3.bb
This series shrinks the compressed initramfs.gz size from 25MB to 11MB.
> Shrink dom0 initramfs

- classes/module-signing.bbclass
do_sign_module will change a module file inode, which in turn can trigger Pseudo to fail in linux-openxt:do_package.
Pseudo log will look like the following on .ko binaries:
Setup complete, sending SIGUSR1 to pid 1271422.
creat for '.../build-0/tmp-glibc/work/xenclient_dom0-oe-linux/linux-openxt/5.4.106-r0/image/lib/modules/5.4.106/kernel/lib/stPopED2'
replaces existing 64496726 ['.../build-0/tmp-glibc/work/xenclient_dom0-oe-linux/linux-openxt/5.4.106-r0/image/lib/modules/5.4.106/kernel/lib/crc-ccitt.ko'].
inode mismatch: '.../build-0/tmp-glibc/work/xenclient_dom0-oe-linux/linux-openxt/5.4.106-r0/image/lib/modules/5.4.106/kernel/arch/x86/crypto/aesni-intel.ko' ino 63584941 in db, 63585005 in request.
Explicitely sign the modules in the fakeroot environment to avoid corrupting the …
> layer: run sign_module in fakeroot

- recipes-kernel/linux/5.4/patches/usbback-base.patch
commit 50d475269b3f "linux: make usbback run in an HVM backend" added a
memory allocation to fast_flush_area, but failed to free it leaking
memory.  Add the corresponding kfree to plug the leak.
> linux: usbback: Fix memory leak

- classes/image-qa-module-sigs.bbclass
- classes/openxt-image.bbclass
image-check-module-sigs.bbclass checks the signatures of modules
installed in an image to ensure they are valid for the associated
kernel.  Usually this is /boot/bzImage, but it will check in deploy dir
for stubdomain's external kernel.
This adds ~7 seconds to dom0 image creation, but it's nicer to check during
the build than have an install that fails to boot properly.
Tie it in to openxt-image so the check is always performed.
The installer doesn't have signed modules, so there is a workaround (if [[ $output =~ "Can't find system certificate list " ]]; then) to skip the check in that case.
pipefail is enabled so we get the exit value of `openssl smime -verify` on failure and not the (always successful) exit status of `sed -n …
> Add image-check-module-sigs.bbclass

- classes/image-qa-module-sigs.bbclass
- classes/module-signing.bbclass
This came about because reviewing PRs https://github.com/OpenXT/xenclient-oe/pull/1395 and https://github.com/OpenXT/xenclient-oe/pull/1401 illustrated the fragility of the offline signing support.
Introduce KERNEL_MODULE_OFFLINE_SIGNING to force the user to make an
explicit choice to perform offline signing.  Silently creating
un-bootable images isn't user friendly.  This variable forces them to
make the choice.
Add various checks for invalid configurations to enforce using the
variable.
> Introduce KERNEL_MODULE_OFFLINE_SIGNING

- classes/image-qa-module-sigs.bbclass
set -o pipefail is a bashism and fails when the system shell is dash.
Replace the pipefail with a 2-step implementation to catch the openssl
smime verify exit code, and then process the output.
> image-qa-module-sigs: Remove bashism

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.system.init.diff
/run/ifstate is no longer labeled properly after the dunfell uprev.
Busybox changed from directly modifying /run/ifstate, to creating
/run/ifstate.new and then renaming.
Update for the new filename to get the desired etc_runtime_t label.
> refpolicy: Fix /run/ifstate labeling

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
- recipes-openxt/xenclient-tpm-scripts/xenclient-tpm-scripts/tpm-functions
For TPM1.2, /sys/class/tpm/tpm0/pcrs is [formatted with](https://elixir.bootlin.com/linux/v5.4.131/source/drivers/char/tpm/tpm-sysfs.c#L118): 'PCR-%02d: %02X %02X...'
The use of grep does not account for the 0 padding for PCRs below 10, which breaks forward seal on UEFI/TPM1.2 systems. The bug is mostly silent (apart from failing to unseal after upgrading/forward-sealing):
- tpm_get_pcr returns an empty string for PCR 8
- `! contains_only "$pcr8" "0"` is used to detect a UEFI measured   installation. `contains_only` will return true for   an empty-string given for the PCR value, for any character value.
- In turn, `seal-system` calls `calculate_drtm_pcr` for legacy installations, using `/boot/system/grub/grub.cfg` and setting SRTM to 0.
This leads to PCR18 and PCR19 not being predicted …
> tpm-scripts: fix tpm_get_pcr grep format

- recipes-core/initscripts/initscripts-1.0/functions-dbus
Commit:
2ef30c8c initscripts: dbus wait for service providers
Did not handle its purpose correctly.
dbus-send will not return an error code regardless of the method_call result as long as the method was called successfully. Since the signature returns a boolean this is easy to grep.
The timeout is expected to be roughly in seconds, but the loop does not wait, so add that.
> initscripts: fix dbus wait helpers

- recipes-openxt/manager/xenmgr/xenmgr.initscript
Xenmgr can be configured to not autostart VMs at startup, this used to be handled by the initscript by checking "autostart" on the kernel cmdline.
Commit: ae940b14 xenmgr: cleanup initscript introduced a regression on a knee-jerk change from "autostart" to "no-autostart" being checked on the command line, yet the configuration files used at bootstrap were not changed.
This is in any case a regression that would affect any customised openxt.cfg or grub.cfg, making it not worth it.
Restore the original behavior: normal operation boot entries add "autostart" to the kernel cmdline, "no-autostart" is the default.
Regression introduced by: https://github.com/OpenXT/xenclient-oe/pull/1410 (https://github.com/OpenXT/xenclient-oe/pull/1410#discussion_r670423609)
> xenmgr: regression on cmdline argument autostart

- recipes-support/vim/vim-tiny_8.2.bbappend
vim-tiny's PACKAGECONFIG defaults to enabling graphical support when
DISTRO_FEATURES contains x11, which openxt-main contains.  This pulls in
x11 and gtk3.  gtk3 especially brings in lots of dependencies like mesa
and drm.  Graphical mode is unnecessary as our VMs don't have guis aside
from uivm, and even there vim isn't exposed for graphical use.
As an example, this reduces the size of syncvm-image rootfs from 155MB
to 99MB (52MB -> 34MB for the .ext3.vhd.gz).
It drops dom0 rootfs 487MB -> 459MB (186MB -> 178MB .ext3.gz) as dom0
still keeps some of the drm libraries for vGlass.
> vim-tiny: Remove graphical (x11/gtk3) mode

- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/blktap-interfaces.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.admin.alsa.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.kernel.devices.diff
- recipes-security/refpolicy/refpolicy-mcs-2.%/patches/policy.modules.kernel.storage.diff
Two fixes:
The first restores sysadm's ability to list /dev/xen/blktap-2.  A side effect of this is that sysadm can read/write the /dev/xen/blktap-2/tapdev* nodes.  This was not allowed in stable-9 because those nodes were labeled xen_device_t.  sysadm can already mount the tapdevs, so I think this is okay.  Since OpenXT was open sourced, there's existed: storage_rw_blktap(sysadm_t), so I think this was intended.  sysadm_t can modify the .vhds directly anyway.
The second fixes some avc denials with writing /config/asound{,.new} on shutdown.
> refpolicy fixes

- recipes-extended/xen/files/libxl-openxt-qemu-args.patch
libxl-RFC-5of7-Handle-Linux-stubdomain-specific-QEMUoptions.patch moved
-no-shutdown as "There is currently no way to access the QMP socket in
the stubdom".
libxl-openxt-qemu-args.patch introduces a way to access QMP, but it did
not re-add -no-shutdown.
Without -no-shutdown, QEMU exits when the VM stops.  libxl expects QEMU
to still be running to issues "stop" and "quit" commands.  When QEMU is
gone, we get 10 seconds (2 x 5) of delay while libxl waits for the
timeouts. By re-adding "-no-shutdown" we avoid this shutdown delay.
On other issue with QEMU exiting is that it closes up its vGlass
connection which results in a slew of "xen:grant_table: WARNING: g.e.
0x1200 still in use!" since those grants are still mapped by vGlass in
dom0.  By having QEMU wait for an explicit quit, vGlass …
> xen: Run qemu with -no-shutdown to avoid timeout

- recipes-openxt/manager/xenmgr_git.bb
xenmgr-data is the HTML+JS UI from toolstack-data.git.  xenmgr just
doesn't depend on it.  It's unclear why it was added in the first place.
Remove it from depends.
> xenmgr: Remove depends on xenmgr-data

- recipes-extended/qemu-dm/qemu-dm.inc
- recipes-extended/qemu-dm/qemu-dm/hvm-param-dm-domain.patch
This disables some unused configure options to save 2+MB off QEMU.
It also trims down hvm-param-dm-domain.patch to remove the no-longer-needed hunk.
> Qemu cleanup

- recipes-extended/qemu-dm/qemu-dm/atapi-pass-through.patch
Remove the hardcoded dom0 and allow specifying a domid (and port) to the
atapi-pt code.  Then we can point it at USB VM.
pt_argo_probe_device doesn't work as-is with a domid & port since it
calls pt_argo_open_common.  It would need to duplicate parsing options
like pt_argo_open.  Just remove it and let the open itself fail.
> qemu-dm: Add atapi-pt-argo domid and port

- recipes-openxt/libicbinn/pyicbinn_git.bb
libicbinn_resolved is a static library, so security_flags specifying
-fPIC causes a link error.  libicbinn_resolved is a weird wrapping of
libicbinn.  python has shared library support, so we can just use that
to link against libicbinn itself.
Update the recipe to depend against libicbinn.
OXT-1697
OXT-447
Goes along with https://github.com/OpenXT/icbinn/pull/7
> pyicbinn: link against libicbinn not libicbinn_resolved

- recipes-extended/xen/blktap3/blktap3-handle-EINTR-in-tap-ctl-IPC.patch
- recipes-extended/xen/xen-tools-blktap3.inc
Sometimes, noticed with NDVM & stubdom, tap-ctl list shows processes
lingering in state 0x2.  Logs show:
xl: tap-err:tap_ctl_read_raw: failure reading data 0/544
xl: tap-err:tap_ctl_send_and_receive: failed to receive 'close' message
xl: [4274] libxl_blktap3.c:175:libxl__device_destroy_tapdisk:Failed to destroy tap device id 4163 minor 4
...
tapdisk[4163]: ERROR: errno -32 at tapdisk_ctl_conn_send_event: close: failure sending message at offset 0/544
select() gets EINTR and doesn't continue.  This patch retries on EINTR and
fixes the issue.
https://github.com/xapi-project/blktap/issues/352
> xen: blktap3: fix tapdisk process in state 0x2

- recipes-openxt/manager/rpc-proxy/rpc-proxy.rules
syncvm (and any users of domstore) need to be able to call
org.freedesktop.DBus.Hello.  Without it, the db-*-dom0 calls get blocked
by rpc-proxy.  Allow that when domstore-read access is given so things
just work.
syncvm's sync-client also calls org.freedesktop.DBus.GetOwnerName in
Domstore.__init__()
db_obj = bus.get_object(DOMSTORE_SERVICE, DOMSTORE_OBJECT)
allow that as well.
> rpc-proxy: Fixup rules for syncvm

- recipes-security/tboot/tboot-1.9.12/0006-pcr-calc-Add-pcr-calculator-tool.patch
acmmatch is segfaulting on microcode_intel.bin and its date symlink.
They are not acms, but sanity check error handling has problems.
If get_acm_header() fails, acm->header is NULL when we jump to fail_map.
Change munmap() to use p, which is the valid pointer from mmap().  This
is the part that avoids the segfault.
Also if mmap() fails, go to fail_sanity.  There is nothing to munmap in
that case.
> tboot: Fix acmmatch segfault on microcode

- recipes-core/jamvm/jamvm_git.bbappend
- recipes-devtools/bats-suite/bats-suite_git.bb
- recipes-devtools/bats/bats_git.bb
- recipes-extended/xen/xen-xsm-policy_git.bb
- recipes-openxt/argo/argo.inc
- recipes-openxt/heimdallr/heimdallr_git.bb
- recipes-openxt/idl/idl.inc
- recipes-openxt/libicbinn/icbinn.inc
- recipes-openxt/libxcdbus/libxcdbus_git.bb
- recipes-openxt/libxenbackend/libxenbackend_git.bb
- recipes-openxt/manager/manager.inc
- recipes-openxt/network/network.inc
- recipes-openxt/openxt-ocaml-libs/openxt-ocaml-libs_git.bb
- recipes-openxt/surfman/surfman.inc
- recipes-openxt/sync-client/sync-client_git.bb
- recipes-openxt/sync-wui/sync-wui_git.bb
- recipes-openxt/uid/uid_git.bb
- recipes-openxt/vusb/vusb-daemon_git.bb
- recipes-openxt/xclibs/xclibs.inc
- recipes-openxt/xctools/xctools.inc
- recipes-openxt/xenclient-installer/xenclient-installer_git.bb
- recipes-openxt/xenmgr-data/xenmgr-data_git.bb
- recipes-security/libseccomp/libseccomp_2.4.3.bb
- recipes-security/tss2/tpm2-tools_3.1.3.bb
- recipes-security/tss2/tpm2-tss_2.0.0.bb
- recipes-support/pesign/pesign_git.bb
Github git protocol fetches are failing with:
> The unauthenticated git protocol on port 9418 is no longer supported.
> Please see
> https://github.blog/2021-09-01-improving-git-protocol-security-github/
> for more information.
Follow oe-core's lead and switch to explicitly specifying protocol=https
for fetching.
> Update github SRC_URI to use https

- recipes-core/varstored/varstored_git.bb
The append redirects may get called repeatedly if re-builds are
triggered without cleaning.  This will created larger and larger db.auth
files.  At runtime, varstored will fail to load them with:
"Auth file '/usr/share/varstored/db.auth' is too large: 57829"
The guest sits spinning in OVMF, and the display doesn't initialize,
showing "Guest has not initialized the display (yet)."
Clear the files first with '>' before appending more.
> varstored: Create fresh {KEK,db}.list

- recipes-kernel/linux/5.10/patches/blktap2.patch
I saw a dom0 kernel backtrace in console mode, I think while shutting down.  I put some hand copied info from that BUG into the commit message here: https://github.com/OpenXT/xenclient-oe/commit/c122ed5ddcab7ea2ef0b7800e67d16c5f13a5e15
I'm not sure what caused it, but the call stack seems to indicated that an already un-linked delayed_work struct might have been called a second time.  Since I didn't find any existing cancel_delayed_work call, this PR reorganizes code and adds one.
It was developed against 5.4, so it "Can't automatically merge" at this time.  At this time, I want to see if there is any feedback.  I'll put it in 5.10 locally for a little bit of testing.
> blktap2: cancel_delayed_work

- classes/multilib-allarch.bbclass
- conf/distro/openxt-main.conf
- recipes-connectivity/networkmanager-certs/networkmanager-certs.bb
- recipes-core/initrdscripts/initramfs-stubdomain_1.0.bb
- recipes-core/udev/udev-extraconf-dom0_1.0.bb
- recipes-devtools/bats-suite/bats-suite_git.bb
- recipes-devtools/bats/bats_git.bb
- recipes-extended/rsyslog/rsyslog-conf-dom0.bb
- recipes-extended/xen/files/0001-tools-firmware-Build-firmware-as-ffreestanding.patch
- recipes-extended/xen/xen-common.inc
- recipes-kernel/linux-firmware/linux-firmware_git.bb
- recipes-openxt/argo/argo-module-headers_git.bb
- recipes-openxt/idl/xenclient-idl_git.bb
- recipes-openxt/xen-legacy-block-scripts/xen-legacy-block-scripts_1.0.bb
- recipes-openxt/xen-tap-scripts/xen-tap-scripts_1.0.bb
- recipes-openxt/xen-vif-scripts/xen-vif-scripts-dom0_1.0.bb
- recipes-openxt/xen-vif-scripts/xen-vif-scripts-ndvm_1.0.bb
- recipes-openxt/xenclient-installer/xenclient-installer_git.bb
- recipes-openxt/xenclient-repo-certs/xenclient-repo-certs_1.0.bb
- recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig_0.0.2.bb
- recipes-security/selinux/selinux-load_1.0.bb
Backport the xen hvmloader freestanding patch and remove the need to build multilib.  It's a lot of extra building for one component, so it's nice to skip it.  Then revert the distro and multilib-allarch changes to clean up further.
> Remove multilib

- recipes-core/images/xenclient-ndvm-image.bb
- recipes-openxt/network/xenclient-nws_git.bb
network-slave execs brctl, carrier-detect, iptables, and NetworkManager,
so it has direct runtime dependencies on them.  Add them to RDEPENDS.
With that, carrier-detect is not a build depends, so drop it from
DEPENDS.
Since they are set as RDEPENDS, drop the runtime deps from the ndvm
image recipe.
> ndvm: Use RDEPEND with network-slave

- recipes-security/tboot/tboot-1.9.12/0006-pcr-calc-Add-pcr-calculator-tool.patch
It is an error to be unable to find the tpm 2.0 sysfs event log, so
return failure.  Without this, seal-system keeps running with empty pcr
17, 18 & 19, which are invalid forward seal values.
The sysfs event log can be missing when the txt_op hypercall number
mismatches between Xen and Linux.
> tboot: pcr-calc: Error without evtlog

- recipes-kernel/linux/5.15/patches/usbback-base.patch
We have warnings like this for va_start, va_arg and va_copy:
include/linux/stdarg.h:6: warning: "va_start" redefined
6 | #define va_start(v, l) __builtin_va_start(v, l)
gcc/x86_64-oe-linux/9.3.0/include/stdarg.h:47: note: this is the location of the previous definition
47 | #define va_start(v,l) __builtin_va_start(v,l)
usbback should not be including the compiler's stdarg, since it should
be using Linux's definitions.  Drop the compiler inclusion.
> linux: usbback: Remove stdarg.h include

- recipes-kernel/linux/5.15/patches/blktap2.patch
https://github.com/OpenXT/xenclient-oe/commit/072a39ded084eea085ae3658312828af715ac3c9 didn't full solve the crash it was trying to.  Turns out you can repro by SIGKILL-ing a tapdisk process.  The destroy work calls cleanup_queue() -> blk_cleanup_queues(), and it crashes when blk_cleanup_queues() runs a second time.  
(blktap_device_destroy seems wonky.  It leaves the device open if there are still any openers, or if it is locked.  Locked implying that it is the final opener.  This means closing the final opener doesn't close the device and relies on destroy_work or an IOCTL to remove.  I feel like this should be done better, but I'm not sure.  Maybe destroy_work should just go away and leave cleanup tied to ioctl?)
There are also two small cleanups to remove a duplicate queue pointer and …
> Blktap2 fixes

- recipes-openxt/xenclient-root-ro/xenclient-root-ro/init.root-ro
Over time after upgrades and forward seal operations, PCRS_GOOD
can become outdated. When you do encounter a measurement failure,
it doesn't always provide an admin/developer accurate PCR values
for debugging what PCR measurement failed.
This commit writes the latest known-good PCR values on each successful
unlock of the encrypted partition when booting.
Signed-off-by: Chris Rogers <crogers122@gmail.com>
> [mle] Write PCRS_GOOD on successful unlock

- recipes-openxt/xenclient-installer/xenclient-installer_git.bb
The build user & group id are leaking into the control.tar.bz2 tarball. Specify the owner and group as root to avoid this.
It doesn't have a practical impact in normal OpenXT use since the installer runs as root.
> installer: Generate root-owned control.tar.bz2

- recipes-security/tss2/tpm2-tools/tpm2-nvlist-drop-ntoh.patch
- recipes-security/tss2/tpm2-tools_3.1.3.bb
tpm2_write_tboot_policy() has code to check the TPM NV indices to avoid
excessive writes.  When tpm-tools was upreved to 3.x, it gained an
incorrect change which did an endian swap on the attributes value.  This
broke tpm2_write_tboot_policy's attribute check since the scripts
attributes are in the correct host endian.
Commit introducing the problem: https://github.com/tpm2-software/tpm2-tools/commit/b2c32c630501c5ac1559e1651963e5d94b4a4c64
Fixed upstream in: https://github.com/tpm2-software/tpm2-tools/commit/b2c32c630501c5ac1559e1651963e5d94b4a4c64
This is a backport of the upstream fix.  With it in place,
tpm2_write_tboot_policy correctly checks NV attributes again.
> tpm2-tools: Fix attributes

- recipes-extended/xen/files/libxl-openxt-helpers.patch
"tools/libxl: Replace deprecated -soundhw on QEMU command line" was backported to stable-4.16 in commit	e85e2a3c17b6.  This change to soundhw code has quilt applying libxl-openxt-helpers.patch with a huge offset.  From do_patch:
Applying patch libxl-openxt-helpers.patch
patching file tools/libs/light/libxl_dm.c
Hunk #2 succeeded at 841 with fuzz 2 (offset -677 lines).
Hunk #3 succeeded at 2280 (offset 17 lines).
Hunk #4 succeeded at 2440 (offset 17 lines).
patching file tools/libs/light/libxl_domain.c
patching file tools/libs/light/libxl_internal.h
The -677 offset is patching libxl__build_device_model_args_old() instead of libxl__build_device_model_args_new().  linux stubdoms use libxl__build_device_model_args_new(), so audio-helper won't get flagged for starting.
Fixup the patch to apply …
> xen: Fixup libxl-openxt-helpers.patch

- recipes-extended/rsyslog/rsyslog-conf-dom0/rsyslog.conf
These messages are not actionable and just spammy from WebKit.  Drop them.
> rsyslog-conf-dom0: Drop uivm Memory pressure relief

- recipes-extended/xen/blktap3.bb
- recipes-extended/xen/blktap3/0001-tap-ctl-Default-to-read-only-opening.patch
- recipes-extended/xen/files/0001-convert-block-tap-for-shared.patch
- recipes-openxt/vhd-scripts/vhd-scripts/vhd-copy
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/create-ndvm
- recipes-openxt/xenclient-dom0-tweaks/xenclient-dom0-tweaks/firstboot.sh
Change the default for `tap-ctl create` to read-only, the former -R option.  Add a new -W option to use when read-write is desired.
Now that tap-ctl defaults to read-only, we need to specify -W when opening writable .vhds.  For the read-only cases, explicity add -R to highlight the use.
OpenXT is changing to hash .vhds directly.  To do so, we need to only open .vhds as read-only as read-write can modify the metadata even if the contents do not change.  To avoid user error, default to read-only so explicit action is needed which will potentially modify the .vhd.
> Default to read-only blktap

- recipes-bsp/grub/files/grub-xen.cfg
- recipes-bsp/grub/grub-xen-conf.bb
- recipes-bsp/grub/grub-xen-pv64_2.04.bb
- recipes-bsp/grub/grub-xen-pvh_2.04.bb
- recipes-bsp/grub/grub-xen.inc
- recipes-core/images/xenclient-ndvm-image.bb
- recipes-core/images/xenclient-syncvm-image.bb
- recipes-core/images/xenclient-uivm-image.bb
- recipes-openxt/manager/xenmgr_git.bb
This switches to using grub as a PVH/PV64 boot loader for booting VMs.  It removes extracting kernels from disk images, though that functionality still remains.
grub2 doesn't support a 32bit version, and PV32 shouldn't be used these days, AFAIUI.
https://github.com/OpenXT/manager/pull/205 changes the templates to use grub-xen-pvh/pv64.  I think this could go in first without the templates change and things would keep working.
> Add grub-xen-pvh & grub-xen-pv64

- recipes-bsp/grub/grub-xen.inc
After the recent grub updates in oe-core, we have faults on startup in the two pv-grubs.
grub-xen-pv64:
(XEN) d17v0 Unhandled invalid opcode fault/trap [#6, ec=ffffffff] (XEN) domain_crash_sync called from entry.S: fault at ffff82d0402fdfc8 x86_64/entry.S#create_bounce_frame+0x14f/0x167
grub-xen-pvh:
(XEN) MMIO emulation failed (1): d13v0 32bit @ 0000:ffffffff ->
(XEN) d13v0 Triple fault - invoking HVM shutdown action 1
GCC is generating a .text.unlikely section with terminate_arg.cold(), and that is placed ahead of the normal _start code in the text segment. The entry points still point at the beginning of the text segment, which faults as it is terminate_arg.cold().
Passing -fno-reorder-functions inhibits use of .text.unlikely, so terminate_arg.cold() is left in the main .text section. …
> grub-xen: Fix binary layout to avoid faulting

- conf/layer.conf
- recipes-extended/monit/monit/dom0-cfg
- recipes-extended/monit/monit/volatiles
- recipes-extended/monit/monit_%.bbappend
- recipes-security/refpolicy/refpolicy-mcs/patches/monit-volatiles.patch
- recipes-security/refpolicy/refpolicy-mcs/policy/modules-upstream.conf
- recipes-security/refpolicy/refpolicy-mcs_git.bbappend
This adds monit to dom0.  It will monitor vglass, disman & ivcdaemon and restart them as necessary.
We want to run more frequently than the default monit interval of 30 seconds, so we use every 2 seconds.  There is also a 12 second delay at startup to give things a change to start.  I did this via dom0-cfg to avoid overriding monitrc which would require keeping in sync... Maybe this was a bad choice and monitrc should just be overridden.
refpolicy needs tweaks to work with volatiles and actually start the daemons.
Goes with https://gitlab.com/vglass/meta-vglass/-/merge_requests/20
> Add monit to monitor vglass

- recipes-security/tboot/tboot-1.9.12/0010-Add-support-for-launching-64-bit-PE-kernels.patch
I made these two changes while working on the Xen 4.14 & 4.16 uprevs.  I got OpenXT's UEFI -> xen -> tboot -> xen running in QEMU so I could debug it.
[tboot/pe: Fix PE load address calculation](https://github.com/OpenXT/xenclient-oe/commit/9bcd088fdb35205c12c8fd190a682f139b090362) is a bug fix.  `efi_memmap_get_highest_sized_ram()`'s return value isn't checked,so the uninitialized ram_size is used.
[tboot/PE: Or-in PAE flag to cr4](https://github.com/OpenXT/xenclient-oe/commit/872e442d5d685be5f22df14df52e9e633495ab09) fixes running tboot under QEMU.  My QEMU instance didn't emulate enough of CR4 that it faulted when trying to set all the values.  In particular, QEMU doesn't support TXT(SMX), so that can't be set in cr4.  This change makes it a little more proper to just or-in the desired …
> tboot fixes

- recipes-openxt/xen-vif-scripts/xen-vif-scripts-ndvm/vif
When this vif script runs, it can race with network-slave with both executing iptables commands.  iptables tries to grab a lock to synchronize access, but by default it fails the command if the lock cannot be grabbed:
"Another app is currently holding the xtables lock." "Perhaps you want to use the -w option?"
The `-w` flag to iptables makes it wait for the lock.  This is important so we don't lose iptables commands that define chains used for other commands.  For instance, this was seen:
network-slave: exception: "cannot add rule -A FORWARD -i brbridged -o brbridged -m physdev --physdev-in eth0 -j FORWARD_brbridged : iptables v1.8.4 (legacy): Couldn't load target FORWARD_brbridged':No such file or directory\n\nTry iptables -h' or 'iptables --help' for more information.\n" while …
> xen-vif-scripts-ndvm: Trim down the script

- recipes-core/base-files/files/openxt-installer/fstab
- recipes-core/base-files/files/xenclient-dom0/fstab
- recipes-core/initscripts/initscripts-1.0/mountefi.sh
- recipes-core/initscripts/initscripts_1.0.bbappend
Installation is currently broken (after the Linux 6.1 uprev I believe) because efivarfs is not mounted, so efibootmgr fails to write the boot variables.
The first patch fixes the problem.  It manually mounts efivarfs for the installer.
The second patch removes efivarfs from /etc/fstab.  dom0's is mounted early in /init from the initramfs-framework.  With the first patch, the installer manually mounts it in the same fashion.  The fstab entries are therefore unnecessary.  They were always problematic on legacy boots, so just drop them from fstab.
If the second patch is deemed unnecessary, then only the first patch can be taken to fix the issue.
> Fix installer efivarfs mounting and drop efivars from fstab

- classes/openxt_image_types.bbclass
- recipes-connectivity/networkmanager/networkmanager-1.18.4/fix-compatibility-with-network-slave.patch
- recipes-openxt/idl/xenclient-rpcgen_git.bb
- recipes-openxt/manager/libxenmgr-core_git.bb
- recipes-openxt/manager/manager.inc
- recipes-openxt/manager/rpc-proxy_git.bb
- recipes-openxt/manager/updatemgr_git.bb
- recipes-openxt/manager/upgrade-db_git.bb
- recipes-openxt/manager/xec_git.bb
- recipes-openxt/manager/xenmgr_git.bb
- recipes-openxt/network/xenclient-nwd_git.bb
- recipes-openxt/network/xenclient-nws_git.bb
- recipes-openxt/xclibs/libxch-rpc_git.bb
- recipes-openxt/xclibs/libxchdb_git.bb
- recipes-openxt/xclibs/libxchutils_git.bb
- recipes-openxt/xclibs/libxchwebsocket_git.bb
- recipes-openxt/xclibs/udbus-intro_git.bb
- recipes-openxt/xclibs/udbus_git.bb
- recipes-openxt/xctools/compleat_git.bb
This PR set upgrades the Glasgow Haskell Compiler to version 8.10.7.  It provides the necessary updates to haskell packages, dependencies, and binaries to compile and run with GHC 8.10.7.  This includes an extensive set of API and logic changes to OpenXT haskell binaries.  It also deprecates and removes unused code to reduce the maintenance burden in the future.  Each individual commit provides a more detailed explanation of the encompassed changes.
Links to all the PRs in this changeset can be found below:
https://github.com/OpenXT/meta-openxt-haskell-platform/pull/23
https://github.com/OpenXT/meta-openxt-ocaml-platform/pull/25
https://github.com/OpenXT/bordel/pull/66
https://github.com/OpenXT/idl/pull/46
https://github.com/OpenXT/manager/pull/207 …
> Uprev to GHC 8.10.7

- recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/ml-functions
- recipes-security/tboot/tboot-1.9.12/0006-pcr-calc-Add-pcr-calculator-tool.patch
Intel doesn't really post SINIT modules anymore.  Also, with Converged BootGuard and TXT (CBnT), the BIOS-provided ACM doesn't double duty for both BootGuard and TXT.  It's something like there can be only a single BIOS ACM.  Since it has to be there for BootGuard, it also does TXT.
Since there may not be an SINIT ACM on on disk to match against, we can't rely on it to parse the ACM caps.  Instead (kinda ugly) grep it out of txt-stat output.  It's logged there by tboot and we just need a single 32bit value.
pcr-calc is updated to accept ACM caps on the command line.
> Support BIOS SINIT modules

- recipes-core/varstored/varstored_git.bb
- recipes-security/refpolicy/refpolicy-mcs/policy/modules/system/stubdom-helpers.fc
- recipes-security/refpolicy/refpolicy-mcs/policy/modules/system/stubdom-helpers.te
With the uprev of varstored, the location of the auth files moved to /var/lib/varstored.  Update the installation and refpolicy to accomodate.
Without this, varstored logs:
Auth file '/var/lib/varstored/dbx.auth' is missing! Auth file '/var/lib/varstored/db.auth' is missing! Auth file '/var/lib/varstored/KEK.auth' is missing! Auth file '/var/lib/varstored/PK.auth' is missing!
> varstored/refpolicy: Fix auth files location
